type QuestionData = {
  category: "verbal" | "math_logic" | "spatial";
  difficulty: number;
  stem: string;
  options: { label: string; text: string }[];
  correctLabel: string;
  tags: string[];
};

export const mathLogicQuestions2: QuestionData[] = [
  // ============================================================
  // ARITHMETIC (~30 questions)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 23 × 7?",
    options: [
      { label: "A", text: "151" },
      { label: "B", text: "161" },
      { label: "C", text: "171" },
      { label: "D", text: "141" },
      { label: "E", text: "181" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 196 ÷ 14?",
    options: [
      { label: "A", text: "12" },
      { label: "B", text: "13" },
      { label: "C", text: "14" },
      { label: "D", text: "15" },
      { label: "E", text: "16" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 85 + 67?",
    options: [
      { label: "A", text: "142" },
      { label: "B", text: "152" },
      { label: "C", text: "162" },
      { label: "D", text: "148" },
      { label: "E", text: "156" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 432 - 187?",
    options: [
      { label: "A", text: "235" },
      { label: "B", text: "255" },
      { label: "C", text: "245" },
      { label: "D", text: "225" },
      { label: "E", text: "265" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 16 × 9?",
    options: [
      { label: "A", text: "134" },
      { label: "B", text: "154" },
      { label: "C", text: "144" },
      { label: "D", text: "124" },
      { label: "E", text: "164" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 17 × 13?",
    options: [
      { label: "A", text: "211" },
      { label: "B", text: "231" },
      { label: "C", text: "201" },
      { label: "D", text: "221" },
      { label: "E", text: "241" },
    ],
    correctLabel: "D",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 3/8 + 1/4?",
    options: [
      { label: "A", text: "1/2" },
      { label: "B", text: "5/8" },
      { label: "C", text: "3/4" },
      { label: "D", text: "7/8" },
      { label: "E", text: "4/8" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 15% of 240?",
    options: [
      { label: "A", text: "32" },
      { label: "B", text: "34" },
      { label: "C", text: "36" },
      { label: "D", text: "38" },
      { label: "E", text: "40" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 2.5 × 3.2?",
    options: [
      { label: "A", text: "7.0" },
      { label: "B", text: "7.5" },
      { label: "C", text: "8.0" },
      { label: "D", text: "8.5" },
      { label: "E", text: "6.5" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 1000 ÷ 8?",
    options: [
      { label: "A", text: "120" },
      { label: "B", text: "130" },
      { label: "C", text: "125" },
      { label: "D", text: "115" },
      { label: "E", text: "135" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is 7/12 - 3/8?",
    options: [
      { label: "A", text: "5/24" },
      { label: "B", text: "7/24" },
      { label: "C", text: "1/6" },
      { label: "D", text: "1/4" },
      { label: "E", text: "1/3" },
    ],
    correctLabel: "A",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is 0.075 × 400?",
    options: [
      { label: "A", text: "28" },
      { label: "B", text: "30" },
      { label: "C", text: "32" },
      { label: "D", text: "35" },
      { label: "E", text: "25" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },

  // ============================================================
  // NUMBER SERIES (~30 questions)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What comes next? 5, 10, 15, 20, ___",
    options: [
      { label: "A", text: "22" },
      { label: "B", text: "24" },
      { label: "C", text: "25" },
      { label: "D", text: "30" },
      { label: "E", text: "28" },
    ],
    correctLabel: "C",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What comes next? 3, 6, 12, 24, ___",
    options: [
      { label: "A", text: "36" },
      { label: "B", text: "48" },
      { label: "C", text: "30" },
      { label: "D", text: "42" },
      { label: "E", text: "54" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What comes next? 100, 90, 80, 70, ___",
    options: [
      { label: "A", text: "65" },
      { label: "B", text: "50" },
      { label: "C", text: "55" },
      { label: "D", text: "60" },
      { label: "E", text: "75" },
    ],
    correctLabel: "D",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What comes next? 2, 4, 8, 16, ___",
    options: [
      { label: "A", text: "24" },
      { label: "B", text: "20" },
      { label: "C", text: "32" },
      { label: "D", text: "28" },
      { label: "E", text: "36" },
    ],
    correctLabel: "C",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What comes next? 1, 4, 9, 16, ___",
    options: [
      { label: "A", text: "20" },
      { label: "B", text: "25" },
      { label: "C", text: "24" },
      { label: "D", text: "36" },
      { label: "E", text: "22" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What comes next? 2, 6, 18, 54, ___",
    options: [
      { label: "A", text: "108" },
      { label: "B", text: "162" },
      { label: "C", text: "72" },
      { label: "D", text: "216" },
      { label: "E", text: "144" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What comes next? 1, 1, 2, 3, 5, 8, ___",
    options: [
      { label: "A", text: "11" },
      { label: "B", text: "12" },
      { label: "C", text: "13" },
      { label: "D", text: "14" },
      { label: "E", text: "10" },
    ],
    correctLabel: "C",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What comes next? 3, 7, 15, 31, ___",
    options: [
      { label: "A", text: "47" },
      { label: "B", text: "55" },
      { label: "C", text: "63" },
      { label: "D", text: "59" },
      { label: "E", text: "51" },
    ],
    correctLabel: "C",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What comes next? 1, 3, 6, 10, 15, ___",
    options: [
      { label: "A", text: "18" },
      { label: "B", text: "20" },
      { label: "C", text: "21" },
      { label: "D", text: "24" },
      { label: "E", text: "22" },
    ],
    correctLabel: "C",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What comes next? 4, 9, 16, 25, ___",
    options: [
      { label: "A", text: "30" },
      { label: "B", text: "36" },
      { label: "C", text: "49" },
      { label: "D", text: "34" },
      { label: "E", text: "42" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What comes next? 2, 3, 5, 7, 11, 13, ___",
    options: [
      { label: "A", text: "15" },
      { label: "B", text: "16" },
      { label: "C", text: "17" },
      { label: "D", text: "19" },
      { label: "E", text: "21" },
    ],
    correctLabel: "C",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What comes next? 1, 2, 4, 7, 11, 16, ___",
    options: [
      { label: "A", text: "20" },
      { label: "B", text: "22" },
      { label: "C", text: "24" },
      { label: "D", text: "21" },
      { label: "E", text: "23" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What comes next? 0, 1, 1, 2, 4, 7, 13, ___",
    options: [
      { label: "A", text: "20" },
      { label: "B", text: "22" },
      { label: "C", text: "24" },
      { label: "D", text: "26" },
      { label: "E", text: "18" },
    ],
    correctLabel: "C",
    tags: ["number-series"],
  },

  // ============================================================
  // WORD PROBLEMS (~30 questions)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A shirt costs $25. If it is on sale for 20% off, what is the sale price?",
    options: [
      { label: "A", text: "$15" },
      { label: "B", text: "$18" },
      { label: "C", text: "$20" },
      { label: "D", text: "$22" },
      { label: "E", text: "$5" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If a train travels at 60 mph for 3 hours, how far does it go?",
    options: [
      { label: "A", text: "120 miles" },
      { label: "B", text: "150 miles" },
      { label: "C", text: "180 miles" },
      { label: "D", text: "200 miles" },
      { label: "E", text: "160 miles" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A pizza is cut into 8 slices. If you eat 3 slices, what fraction is left?",
    options: [
      { label: "A", text: "3/8" },
      { label: "B", text: "5/8" },
      { label: "C", text: "1/2" },
      { label: "D", text: "4/8" },
      { label: "E", text: "6/8" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If there are 24 students in a class and 1/3 are absent, how many are present?",
    options: [
      { label: "A", text: "8" },
      { label: "B", text: "12" },
      { label: "C", text: "16" },
      { label: "D", text: "18" },
      { label: "E", text: "20" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A rectangle has a length of 12 cm and a width of 5 cm. What is its area?",
    options: [
      { label: "A", text: "50 cm²" },
      { label: "B", text: "60 cm²" },
      { label: "C", text: "34 cm²" },
      { label: "D", text: "70 cm²" },
      { label: "E", text: "55 cm²" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A car uses 8 gallons of fuel to travel 240 miles. How many miles per gallon does it get?",
    options: [
      { label: "A", text: "25" },
      { label: "B", text: "28" },
      { label: "C", text: "30" },
      { label: "D", text: "32" },
      { label: "E", text: "35" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If 3 workers can paint a house in 12 days, how long would it take 4 workers?",
    options: [
      { label: "A", text: "8 days" },
      { label: "B", text: "9 days" },
      { label: "C", text: "10 days" },
      { label: "D", text: "6 days" },
      { label: "E", text: "16 days" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A store marks up items by 40%. If an item costs the store $50, what is the selling price?",
    options: [
      { label: "A", text: "$65" },
      { label: "B", text: "$70" },
      { label: "C", text: "$75" },
      { label: "D", text: "$80" },
      { label: "E", text: "$90" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "The ratio of boys to girls in a class is 3:5. If there are 40 students, how many boys are there?",
    options: [
      { label: "A", text: "12" },
      { label: "B", text: "15" },
      { label: "C", text: "18" },
      { label: "D", text: "20" },
      { label: "E", text: "24" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A rectangular garden is 15 m long and 8 m wide. How many meters of fencing are needed to surround it?",
    options: [
      { label: "A", text: "38 m" },
      { label: "B", text: "42 m" },
      { label: "C", text: "46 m" },
      { label: "D", text: "50 m" },
      { label: "E", text: "120 m" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "An item's price increased by 25%, then decreased by 20%. What is the net percentage change from the original?",
    options: [
      { label: "A", text: "5% increase" },
      { label: "B", text: "0% (no change)" },
      { label: "C", text: "5% decrease" },
      { label: "D", text: "10% increase" },
      { label: "E", text: "2% increase" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Two pipes fill a tank. Pipe A fills it in 6 hours, Pipe B in 4 hours. How long to fill it together?",
    options: [
      { label: "A", text: "2 hours" },
      { label: "B", text: "2.4 hours" },
      { label: "C", text: "3 hours" },
      { label: "D", text: "5 hours" },
      { label: "E", text: "2.5 hours" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },

  // ============================================================
  // LOGIC / DEDUCTION (~30 questions)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "All roses are flowers. All flowers need water. Therefore:",
    options: [
      { label: "A", text: "All water is for roses" },
      { label: "B", text: "All roses need water" },
      { label: "C", text: "Some flowers are not roses" },
      { label: "D", text: "Water makes flowers" },
      { label: "E", text: "Roses don't need water" },
    ],
    correctLabel: "B",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If it rains, the ground gets wet. The ground is wet. Can we conclude it rained?",
    options: [
      { label: "A", text: "Yes, definitely" },
      { label: "B", text: "No, never" },
      { label: "C", text: "Not necessarily — other things can wet the ground" },
      { label: "D", text: "Only if it's cloudy" },
      { label: "E", text: "Only in summer" },
    ],
    correctLabel: "C",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "Tom is taller than Sam. Sam is taller than Pete. Who is shortest?",
    options: [
      { label: "A", text: "Tom" },
      { label: "B", text: "Sam" },
      { label: "C", text: "Pete" },
      { label: "D", text: "Tom and Sam are equal" },
      { label: "E", text: "Cannot be determined" },
    ],
    correctLabel: "C",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If all cats have tails, and Whiskers is a cat, what can we conclude?",
    options: [
      { label: "A", text: "Whiskers has no tail" },
      { label: "B", text: "Whiskers has a tail" },
      { label: "C", text: "Whiskers is not a cat" },
      { label: "D", text: "Some cats don't have tails" },
      { label: "E", text: "Nothing can be concluded" },
    ],
    correctLabel: "B",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "Monday comes before Tuesday. Wednesday comes after Tuesday. Which day is in the middle?",
    options: [
      { label: "A", text: "Monday" },
      { label: "B", text: "Tuesday" },
      { label: "C", text: "Wednesday" },
      { label: "D", text: "Thursday" },
      { label: "E", text: "Sunday" },
    ],
    correctLabel: "B",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "All managers are employees. Some employees are part-time. Which MUST be true?",
    options: [
      { label: "A", text: "All managers are part-time" },
      { label: "B", text: "Some managers are part-time" },
      { label: "C", text: "No managers are part-time" },
      { label: "D", text: "All employees are managers" },
      { label: "E", text: "None of the above must be true" },
    ],
    correctLabel: "E",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If A > B, B > C, and C > D, which is true?",
    options: [
      { label: "A", text: "D > A" },
      { label: "B", text: "B > D" },
      { label: "C", text: "C > A" },
      { label: "D", text: "D > B" },
      { label: "E", text: "A = D" },
    ],
    correctLabel: "B",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "In a race, Amy finished ahead of Ben but behind Carol. Dan finished ahead of Carol. Who won?",
    options: [
      { label: "A", text: "Amy" },
      { label: "B", text: "Ben" },
      { label: "C", text: "Carol" },
      { label: "D", text: "Dan" },
      { label: "E", text: "Cannot be determined" },
    ],
    correctLabel: "D",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "No reptiles have fur. All snakes are reptiles. Therefore:",
    options: [
      { label: "A", text: "Some snakes have fur" },
      { label: "B", text: "All animals with fur are snakes" },
      { label: "C", text: "No snakes have fur" },
      { label: "D", text: "Some reptiles have fur" },
      { label: "E", text: "Snakes are not reptiles" },
    ],
    correctLabel: "C",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If the statement 'All birds can fly' is FALSE, which MUST be true?",
    options: [
      { label: "A", text: "No birds can fly" },
      { label: "B", text: "At least one bird cannot fly" },
      { label: "C", text: "Most birds cannot fly" },
      { label: "D", text: "Only penguins cannot fly" },
      { label: "E", text: "Birds used to fly but no longer can" },
    ],
    correctLabel: "B",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "If 'No A are B' and 'All C are A,' which MUST be true?",
    options: [
      { label: "A", text: "All C are B" },
      { label: "B", text: "Some B are C" },
      { label: "C", text: "No C are B" },
      { label: "D", text: "Some A are B" },
      { label: "E", text: "All B are C" },
    ],
    correctLabel: "C",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Five people sit in a row. Eve is next to Frank. Frank is not next to Grace. Grace sits at one end. Holly is next to Grace. Who sits in the middle?",
    options: [
      { label: "A", text: "Eve" },
      { label: "B", text: "Frank" },
      { label: "C", text: "Grace" },
      { label: "D", text: "Holly" },
      { label: "E", text: "Ian" },
    ],
    correctLabel: "D",
    tags: ["logic"],
  },

  // ============================================================
  // ALGEBRA & EQUATIONS (~25 questions)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If x + 7 = 15, what is x?",
    options: [
      { label: "A", text: "6" },
      { label: "B", text: "7" },
      { label: "C", text: "8" },
      { label: "D", text: "9" },
      { label: "E", text: "22" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If 3x = 27, what is x?",
    options: [
      { label: "A", text: "7" },
      { label: "B", text: "8" },
      { label: "C", text: "9" },
      { label: "D", text: "10" },
      { label: "E", text: "3" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If x - 12 = 8, what is x?",
    options: [
      { label: "A", text: "4" },
      { label: "B", text: "16" },
      { label: "C", text: "20" },
      { label: "D", text: "24" },
      { label: "E", text: "18" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If 2x + 5 = 19, what is x?",
    options: [
      { label: "A", text: "5" },
      { label: "B", text: "6" },
      { label: "C", text: "7" },
      { label: "D", text: "8" },
      { label: "E", text: "12" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If x/4 + 3 = 10, what is x?",
    options: [
      { label: "A", text: "24" },
      { label: "B", text: "28" },
      { label: "C", text: "32" },
      { label: "D", text: "36" },
      { label: "E", text: "40" },
    ],
    correctLabel: "B",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If 5(x - 2) = 30, what is x?",
    options: [
      { label: "A", text: "6" },
      { label: "B", text: "7" },
      { label: "C", text: "8" },
      { label: "D", text: "10" },
      { label: "E", text: "4" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "If x² - 5x + 6 = 0, what are the solutions?",
    options: [
      { label: "A", text: "x = 1 and x = 6" },
      { label: "B", text: "x = 2 and x = 3" },
      { label: "C", text: "x = -2 and x = -3" },
      { label: "D", text: "x = 0 and x = 5" },
      { label: "E", text: "x = 1 and x = 5" },
    ],
    correctLabel: "B",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "If 3x + 2y = 16 and x = 2, what is y?",
    options: [
      { label: "A", text: "3" },
      { label: "B", text: "4" },
      { label: "C", text: "5" },
      { label: "D", text: "6" },
      { label: "E", text: "7" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },

  // ============================================================
  // PERCENTAGES & RATIOS (~25 questions)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 50% of 84?",
    options: [
      { label: "A", text: "40" },
      { label: "B", text: "42" },
      { label: "C", text: "44" },
      { label: "D", text: "48" },
      { label: "E", text: "52" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 25% of 200?",
    options: [
      { label: "A", text: "25" },
      { label: "B", text: "40" },
      { label: "C", text: "50" },
      { label: "D", text: "75" },
      { label: "E", text: "100" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If 30 out of 100 students passed, what percentage passed?",
    options: [
      { label: "A", text: "3%" },
      { label: "B", text: "13%" },
      { label: "C", text: "30%" },
      { label: "D", text: "33%" },
      { label: "E", text: "70%" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A population grows from 500 to 650. What is the percentage increase?",
    options: [
      { label: "A", text: "20%" },
      { label: "B", text: "25%" },
      { label: "C", text: "30%" },
      { label: "D", text: "35%" },
      { label: "E", text: "15%" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "The ratio of red to blue marbles is 2:3. If there are 50 marbles total, how many are red?",
    options: [
      { label: "A", text: "15" },
      { label: "B", text: "20" },
      { label: "C", text: "25" },
      { label: "D", text: "30" },
      { label: "E", text: "35" },
    ],
    correctLabel: "B",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If 60% of a number is 90, what is the number?",
    options: [
      { label: "A", text: "120" },
      { label: "B", text: "130" },
      { label: "C", text: "140" },
      { label: "D", text: "150" },
      { label: "E", text: "160" },
    ],
    correctLabel: "D",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A map has a scale of 1:50,000. If two cities are 4 cm apart on the map, how far apart are they in reality?",
    options: [
      { label: "A", text: "1 km" },
      { label: "B", text: "2 km" },
      { label: "C", text: "5 km" },
      { label: "D", text: "20 km" },
      { label: "E", text: "200 km" },
    ],
    correctLabel: "B",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A product's price is reduced by 15%, then by another 10%. What is the total percentage reduction?",
    options: [
      { label: "A", text: "25%" },
      { label: "B", text: "23.5%" },
      { label: "C", text: "22%" },
      { label: "D", text: "24%" },
      { label: "E", text: "20%" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "In a mixture of 60 liters, the ratio of milk to water is 2:1. How much water must be added to make the ratio 1:2?",
    options: [
      { label: "A", text: "40 liters" },
      { label: "B", text: "50 liters" },
      { label: "C", text: "60 liters" },
      { label: "D", text: "80 liters" },
      { label: "E", text: "30 liters" },
    ],
    correctLabel: "C",
    tags: ["ratio"],
  },

  // ============================================================
  // DATA INTERPRETATION (~20 questions)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A class has test scores: 70, 80, 90, 80, 80. What is the mode?",
    options: [
      { label: "A", text: "70" },
      { label: "B", text: "80" },
      { label: "C", text: "90" },
      { label: "D", text: "75" },
      { label: "E", text: "85" },
    ],
    correctLabel: "B",
    tags: ["data-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is the average of 10, 20, 30, 40, and 50?",
    options: [
      { label: "A", text: "25" },
      { label: "B", text: "30" },
      { label: "C", text: "35" },
      { label: "D", text: "40" },
      { label: "E", text: "45" },
    ],
    correctLabel: "B",
    tags: ["data-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is the median of: 3, 7, 2, 9, 5?",
    options: [
      { label: "A", text: "3" },
      { label: "B", text: "5" },
      { label: "C", text: "7" },
      { label: "D", text: "9" },
      { label: "E", text: "2" },
    ],
    correctLabel: "B",
    tags: ["data-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Sales data for 4 quarters: Q1=$120K, Q2=$150K, Q3=$130K, Q4=$200K. What is the average quarterly sales?",
    options: [
      { label: "A", text: "$140K" },
      { label: "B", text: "$145K" },
      { label: "C", text: "$150K" },
      { label: "D", text: "$155K" },
      { label: "E", text: "$160K" },
    ],
    correctLabel: "C",
    tags: ["data-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A survey shows: 40% prefer coffee, 35% prefer tea, the rest prefer juice. What percentage prefer juice?",
    options: [
      { label: "A", text: "15%" },
      { label: "B", text: "20%" },
      { label: "C", text: "25%" },
      { label: "D", text: "30%" },
      { label: "E", text: "35%" },
    ],
    correctLabel: "C",
    tags: ["data-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A student's scores are 85, 92, 78, 96, and 89. What score is needed on the 6th test to average 90?",
    options: [
      { label: "A", text: "96" },
      { label: "B", text: "98" },
      { label: "C", text: "100" },
      { label: "D", text: "94" },
      { label: "E", text: "92" },
    ],
    correctLabel: "C",
    tags: ["data-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Company revenue grew 10% each year for 3 years from $100K. What is the revenue after 3 years (rounded)?",
    options: [
      { label: "A", text: "$130K" },
      { label: "B", text: "$131K" },
      { label: "C", text: "$133K" },
      { label: "D", text: "$140K" },
      { label: "E", text: "$121K" },
    ],
    correctLabel: "C",
    tags: ["data-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "In a dataset: 2, 4, 4, 6, 8. What is the range?",
    options: [
      { label: "A", text: "4" },
      { label: "B", text: "6" },
      { label: "C", text: "8" },
      { label: "D", text: "2" },
      { label: "E", text: "5" },
    ],
    correctLabel: "B",
    tags: ["data-interpretation"],
  },

  // ============================================================
  // MORE MIXED MATH (~25 questions to reach 180)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 13 × 11?",
    options: [
      { label: "A", text: "133" },
      { label: "B", text: "143" },
      { label: "C", text: "153" },
      { label: "D", text: "123" },
      { label: "E", text: "113" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What comes next? 7, 14, 21, 28, ___",
    options: [
      { label: "A", text: "32" },
      { label: "B", text: "35" },
      { label: "C", text: "42" },
      { label: "D", text: "33" },
      { label: "E", text: "36" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A bag has 6 red and 4 blue balls. What fraction are red?",
    options: [
      { label: "A", text: "2/5" },
      { label: "B", text: "3/5" },
      { label: "C", text: "1/2" },
      { label: "D", text: "4/5" },
      { label: "E", text: "1/3" },
    ],
    correctLabel: "B",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If a square has a perimeter of 36 cm, what is its area?",
    options: [
      { label: "A", text: "64 cm²" },
      { label: "B", text: "81 cm²" },
      { label: "C", text: "72 cm²" },
      { label: "D", text: "49 cm²" },
      { label: "E", text: "100 cm²" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What comes next? 5, 8, 13, 20, 29, ___",
    options: [
      { label: "A", text: "38" },
      { label: "B", text: "40" },
      { label: "C", text: "36" },
      { label: "D", text: "42" },
      { label: "E", text: "35" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A shop sells 3 apples for $2. How much do 12 apples cost?",
    options: [
      { label: "A", text: "$6" },
      { label: "B", text: "$7" },
      { label: "C", text: "$8" },
      { label: "D", text: "$9" },
      { label: "E", text: "$10" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "All even numbers are divisible by 2. 48 is even. Therefore:",
    options: [
      { label: "A", text: "48 is odd" },
      { label: "B", text: "48 is divisible by 2" },
      { label: "C", text: "48 is prime" },
      { label: "D", text: "48 is not a number" },
      { label: "E", text: "Nothing can be concluded" },
    ],
    correctLabel: "B",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If 4x - 3 = 17, what is x?",
    options: [
      { label: "A", text: "3" },
      { label: "B", text: "4" },
      { label: "C", text: "5" },
      { label: "D", text: "6" },
      { label: "E", text: "7" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What comes next? 1, 8, 27, 64, ___",
    options: [
      { label: "A", text: "100" },
      { label: "B", text: "125" },
      { label: "C", text: "128" },
      { label: "D", text: "216" },
      { label: "E", text: "81" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A train leaves at 9:15 AM traveling at 80 mph. Another leaves the same station at 10:00 AM at 100 mph going the same direction. When does the second train catch the first?",
    options: [
      { label: "A", text: "12:00 PM" },
      { label: "B", text: "1:00 PM" },
      { label: "C", text: "1:00 PM" },
      { label: "D", text: "12:30 PM" },
      { label: "E", text: "1:30 PM" },
    ],
    correctLabel: "A",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 75% of 80?",
    options: [
      { label: "A", text: "50" },
      { label: "B", text: "55" },
      { label: "C", text: "60" },
      { label: "D", text: "65" },
      { label: "E", text: "70" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If 2x = 18, what is x?",
    options: [
      { label: "A", text: "7" },
      { label: "B", text: "8" },
      { label: "C", text: "9" },
      { label: "D", text: "10" },
      { label: "E", text: "6" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "If 'Some A are B' and 'All B are C,' which MUST be true?",
    options: [
      { label: "A", text: "All A are C" },
      { label: "B", text: "Some A are C" },
      { label: "C", text: "All C are A" },
      { label: "D", text: "No A are C" },
      { label: "E", text: "All C are B" },
    ],
    correctLabel: "B",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is the sum of all integers from 1 to 20?",
    options: [
      { label: "A", text: "190" },
      { label: "B", text: "200" },
      { label: "C", text: "210" },
      { label: "D", text: "220" },
      { label: "E", text: "180" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A clock shows 3:15. What is the angle between the hour and minute hands?",
    options: [
      { label: "A", text: "0°" },
      { label: "B", text: "7.5°" },
      { label: "C", text: "15°" },
      { label: "D", text: "22.5°" },
      { label: "E", text: "90°" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next term? 2, 5, 11, 23, ___",
    options: [
      { label: "A", text: "35" },
      { label: "B", text: "41" },
      { label: "C", text: "46" },
      { label: "D", text: "47" },
      { label: "E", text: "45" },
    ],
    correctLabel: "D",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "How many different 3-letter arrangements can be made from the letters A, B, C, D (no repeats)?",
    options: [
      { label: "A", text: "12" },
      { label: "B", text: "24" },
      { label: "C", text: "36" },
      { label: "D", text: "64" },
      { label: "E", text: "6" },
    ],
    correctLabel: "B",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A triangle has sides of 3, 4, and 5. What type of triangle is it?",
    options: [
      { label: "A", text: "Equilateral" },
      { label: "B", text: "Isosceles" },
      { label: "C", text: "Right" },
      { label: "D", text: "Obtuse" },
      { label: "E", text: "Acute" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "If the probability of rain on any given day is 0.3, what is the probability it does NOT rain for 2 consecutive days?",
    options: [
      { label: "A", text: "0.40" },
      { label: "B", text: "0.49" },
      { label: "C", text: "0.42" },
      { label: "D", text: "0.51" },
      { label: "E", text: "0.70" },
    ],
    correctLabel: "B",
    tags: ["logic"],
  },

  // ============================================================
  // ADDITIONAL MATH (86 more to reach 180)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 19 × 6?",
    options: [
      { label: "A", text: "104" },
      { label: "B", text: "114" },
      { label: "C", text: "124" },
      { label: "D", text: "94" },
      { label: "E", text: "134" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 225 ÷ 15?",
    options: [
      { label: "A", text: "13" },
      { label: "B", text: "14" },
      { label: "C", text: "15" },
      { label: "D", text: "16" },
      { label: "E", text: "17" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What comes next? 10, 20, 30, 40, ___",
    options: [
      { label: "A", text: "45" },
      { label: "B", text: "50" },
      { label: "C", text: "55" },
      { label: "D", text: "60" },
      { label: "E", text: "48" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What comes next? 1, 3, 5, 7, ___",
    options: [
      { label: "A", text: "8" },
      { label: "B", text: "9" },
      { label: "C", text: "10" },
      { label: "D", text: "11" },
      { label: "E", text: "12" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If you buy 5 items at $3 each, how much do you spend?",
    options: [
      { label: "A", text: "$8" },
      { label: "B", text: "$12" },
      { label: "C", text: "$15" },
      { label: "D", text: "$18" },
      { label: "E", text: "$20" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "All dogs are animals. Spot is a dog. Therefore:",
    options: [
      { label: "A", text: "Spot is not an animal" },
      { label: "B", text: "Spot is an animal" },
      { label: "C", text: "All animals are dogs" },
      { label: "D", text: "Spot is a cat" },
      { label: "E", text: "Nothing can be concluded" },
    ],
    correctLabel: "B",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 10% of 350?",
    options: [
      { label: "A", text: "25" },
      { label: "B", text: "30" },
      { label: "C", text: "35" },
      { label: "D", text: "40" },
      { label: "E", text: "45" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If x + 9 = 21, what is x?",
    options: [
      { label: "A", text: "10" },
      { label: "B", text: "11" },
      { label: "C", text: "12" },
      { label: "D", text: "13" },
      { label: "E", text: "30" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is the average of 6, 8, and 10?",
    options: [
      { label: "A", text: "6" },
      { label: "B", text: "7" },
      { label: "C", text: "8" },
      { label: "D", text: "9" },
      { label: "E", text: "10" },
    ],
    correctLabel: "C",
    tags: ["data-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A circle has a radius of 5. What is its diameter?",
    options: [
      { label: "A", text: "5" },
      { label: "B", text: "10" },
      { label: "C", text: "15" },
      { label: "D", text: "20" },
      { label: "E", text: "25" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 18 × 15?",
    options: [
      { label: "A", text: "250" },
      { label: "B", text: "260" },
      { label: "C", text: "270" },
      { label: "D", text: "280" },
      { label: "E", text: "290" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 5/6 × 3/4?",
    options: [
      { label: "A", text: "5/8" },
      { label: "B", text: "15/24" },
      { label: "C", text: "8/10" },
      { label: "D", text: "3/5" },
      { label: "E", text: "1/2" },
    ],
    correctLabel: "A",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What comes next? 64, 32, 16, 8, ___",
    options: [
      { label: "A", text: "2" },
      { label: "B", text: "4" },
      { label: "C", text: "6" },
      { label: "D", text: "0" },
      { label: "E", text: "1" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What comes next? 2, 6, 12, 20, 30, ___",
    options: [
      { label: "A", text: "36" },
      { label: "B", text: "38" },
      { label: "C", text: "40" },
      { label: "D", text: "42" },
      { label: "E", text: "44" },
    ],
    correctLabel: "D",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A recipe needs 2 cups of flour for 12 cookies. How much flour for 30 cookies?",
    options: [
      { label: "A", text: "4 cups" },
      { label: "B", text: "5 cups" },
      { label: "C", text: "6 cups" },
      { label: "D", text: "3 cups" },
      { label: "E", text: "7 cups" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A cyclist travels 45 km in 3 hours. What is the average speed?",
    options: [
      { label: "A", text: "12 km/h" },
      { label: "B", text: "13 km/h" },
      { label: "C", text: "14 km/h" },
      { label: "D", text: "15 km/h" },
      { label: "E", text: "16 km/h" },
    ],
    correctLabel: "D",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Alice is older than Bob. Carol is younger than Bob. Dave is older than Alice. Who is youngest?",
    options: [
      { label: "A", text: "Alice" },
      { label: "B", text: "Bob" },
      { label: "C", text: "Carol" },
      { label: "D", text: "Dave" },
      { label: "E", text: "Cannot be determined" },
    ],
    correctLabel: "C",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Some teachers are musicians. All musicians are creative. Which MUST be true?",
    options: [
      { label: "A", text: "All teachers are creative" },
      { label: "B", text: "Some teachers are creative" },
      { label: "C", text: "No teachers are creative" },
      { label: "D", text: "All creative people are teachers" },
      { label: "E", text: "None of the above" },
    ],
    correctLabel: "B",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If 35% of a class of 60 students are left-handed, how many are left-handed?",
    options: [
      { label: "A", text: "18" },
      { label: "B", text: "19" },
      { label: "C", text: "20" },
      { label: "D", text: "21" },
      { label: "E", text: "22" },
    ],
    correctLabel: "D",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If 3(x + 4) = 27, what is x?",
    options: [
      { label: "A", text: "3" },
      { label: "B", text: "4" },
      { label: "C", text: "5" },
      { label: "D", text: "6" },
      { label: "E", text: "7" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the median of: 12, 8, 15, 3, 22?",
    options: [
      { label: "A", text: "8" },
      { label: "B", text: "12" },
      { label: "C", text: "15" },
      { label: "D", text: "10" },
      { label: "E", text: "11" },
    ],
    correctLabel: "B",
    tags: ["data-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is 23² - 17²?",
    options: [
      { label: "A", text: "220" },
      { label: "B", text: "230" },
      { label: "C", text: "240" },
      { label: "D", text: "250" },
      { label: "E", text: "260" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What comes next? 1, 4, 10, 22, 46, ___",
    options: [
      { label: "A", text: "88" },
      { label: "B", text: "92" },
      { label: "C", text: "94" },
      { label: "D", text: "90" },
      { label: "E", text: "96" },
    ],
    correctLabel: "C",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A factory produces 200 units/day with a 5% defect rate. How many non-defective units in 5 days?",
    options: [
      { label: "A", text: "900" },
      { label: "B", text: "950" },
      { label: "C", text: "940" },
      { label: "D", text: "960" },
      { label: "E", text: "1000" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "If x² = 169, what are the possible values of x?",
    options: [
      { label: "A", text: "13 only" },
      { label: "B", text: "-13 only" },
      { label: "C", text: "13 and -13" },
      { label: "D", text: "12 and -12" },
      { label: "E", text: "14 and -14" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A group of 10 people has an average age of 25. When 2 people leave, the average drops to 23. What was the average age of the 2 who left?",
    options: [
      { label: "A", text: "31" },
      { label: "B", text: "33" },
      { label: "C", text: "35" },
      { label: "D", text: "37" },
      { label: "E", text: "29" },
    ],
    correctLabel: "C",
    tags: ["data-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 7 × 8?",
    options: [
      { label: "A", text: "48" },
      { label: "B", text: "54" },
      { label: "C", text: "56" },
      { label: "D", text: "64" },
      { label: "E", text: "42" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What comes next? 4, 8, 12, 16, ___",
    options: [
      { label: "A", text: "18" },
      { label: "B", text: "20" },
      { label: "C", text: "22" },
      { label: "D", text: "24" },
      { label: "E", text: "28" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If a box has 20 items and you remove 7, how many remain?",
    options: [
      { label: "A", text: "11" },
      { label: "B", text: "12" },
      { label: "C", text: "13" },
      { label: "D", text: "14" },
      { label: "E", text: "15" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 20% of 150?",
    options: [
      { label: "A", text: "25" },
      { label: "B", text: "30" },
      { label: "C", text: "35" },
      { label: "D", text: "40" },
      { label: "E", text: "45" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 22 × 18?",
    options: [
      { label: "A", text: "386" },
      { label: "B", text: "396" },
      { label: "C", text: "406" },
      { label: "D", text: "416" },
      { label: "E", text: "376" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What comes next? 1, 2, 6, 24, 120, ___",
    options: [
      { label: "A", text: "240" },
      { label: "B", text: "480" },
      { label: "C", text: "600" },
      { label: "D", text: "720" },
      { label: "E", text: "360" },
    ],
    correctLabel: "D",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Two numbers have a sum of 50 and a difference of 14. What is the larger number?",
    options: [
      { label: "A", text: "28" },
      { label: "B", text: "30" },
      { label: "C", text: "32" },
      { label: "D", text: "34" },
      { label: "E", text: "36" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If it takes 6 people 4 hours to do a job, how long does it take 8 people?",
    options: [
      { label: "A", text: "2 hours" },
      { label: "B", text: "3 hours" },
      { label: "C", text: "3.5 hours" },
      { label: "D", text: "4.5 hours" },
      { label: "E", text: "5 hours" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "The ratio of cats to dogs in a shelter is 5:3. If there are 40 animals, how many are dogs?",
    options: [
      { label: "A", text: "12" },
      { label: "B", text: "15" },
      { label: "C", text: "18" },
      { label: "D", text: "20" },
      { label: "E", text: "25" },
    ],
    correctLabel: "B",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What comes next? 3, 4, 7, 11, 18, 29, ___",
    options: [
      { label: "A", text: "40" },
      { label: "B", text: "43" },
      { label: "C", text: "45" },
      { label: "D", text: "47" },
      { label: "E", text: "50" },
    ],
    correctLabel: "D",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A bacteria population doubles every 3 hours. Starting with 100, how many after 12 hours?",
    options: [
      { label: "A", text: "800" },
      { label: "B", text: "1200" },
      { label: "C", text: "1600" },
      { label: "D", text: "2400" },
      { label: "E", text: "3200" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "If log₁₀(x) = 3, what is x?",
    options: [
      { label: "A", text: "30" },
      { label: "B", text: "100" },
      { label: "C", text: "300" },
      { label: "D", text: "1000" },
      { label: "E", text: "10000" },
    ],
    correctLabel: "D",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 156 + 244?",
    options: [
      { label: "A", text: "380" },
      { label: "B", text: "390" },
      { label: "C", text: "400" },
      { label: "D", text: "410" },
      { label: "E", text: "420" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "Sarah has 15 candies and gives away 1/3. How many does she give away?",
    options: [
      { label: "A", text: "3" },
      { label: "B", text: "4" },
      { label: "C", text: "5" },
      { label: "D", text: "6" },
      { label: "E", text: "7" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If a jacket costs $80 after a 20% discount, what was the original price?",
    options: [
      { label: "A", text: "$90" },
      { label: "B", text: "$96" },
      { label: "C", text: "$100" },
      { label: "D", text: "$104" },
      { label: "E", text: "$110" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "In a group, 3/5 prefer tea. If 21 prefer tea, how many are in the group?",
    options: [
      { label: "A", text: "30" },
      { label: "B", text: "35" },
      { label: "C", text: "40" },
      { label: "D", text: "42" },
      { label: "E", text: "45" },
    ],
    correctLabel: "B",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If 2x + 3y = 18 and y = 4, what is x?",
    options: [
      { label: "A", text: "2" },
      { label: "B", text: "3" },
      { label: "C", text: "4" },
      { label: "D", text: "5" },
      { label: "E", text: "6" },
    ],
    correctLabel: "B",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A 10% salt solution and a 30% salt solution are mixed to get 20 liters of 18% solution. How much of the 10% solution is used?",
    options: [
      { label: "A", text: "8 liters" },
      { label: "B", text: "10 liters" },
      { label: "C", text: "12 liters" },
      { label: "D", text: "14 liters" },
      { label: "E", text: "16 liters" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What comes next? 1, 1, 2, 6, 24, 120, ___",
    options: [
      { label: "A", text: "240" },
      { label: "B", text: "360" },
      { label: "C", text: "480" },
      { label: "D", text: "600" },
      { label: "E", text: "720" },
    ],
    correctLabel: "E",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 300 - 156?",
    options: [
      { label: "A", text: "134" },
      { label: "B", text: "144" },
      { label: "C", text: "154" },
      { label: "D", text: "164" },
      { label: "E", text: "174" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If 5x = 45, what is x?",
    options: [
      { label: "A", text: "7" },
      { label: "B", text: "8" },
      { label: "C", text: "9" },
      { label: "D", text: "10" },
      { label: "E", text: "5" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A rectangle's length is twice its width. If the perimeter is 36 cm, what is the width?",
    options: [
      { label: "A", text: "4 cm" },
      { label: "B", text: "5 cm" },
      { label: "C", text: "6 cm" },
      { label: "D", text: "8 cm" },
      { label: "E", text: "9 cm" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 125% of 80?",
    options: [
      { label: "A", text: "90" },
      { label: "B", text: "95" },
      { label: "C", text: "100" },
      { label: "D", text: "105" },
      { label: "E", text: "110" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If you flip a coin 3 times, how many possible outcomes are there?",
    options: [
      { label: "A", text: "3" },
      { label: "B", text: "6" },
      { label: "C", text: "8" },
      { label: "D", text: "9" },
      { label: "E", text: "12" },
    ],
    correctLabel: "C",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is the next prime number after 89?",
    options: [
      { label: "A", text: "91" },
      { label: "B", text: "93" },
      { label: "C", text: "95" },
      { label: "D", text: "97" },
      { label: "E", text: "99" },
    ],
    correctLabel: "D",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A car depreciates 20% per year. If bought for $25,000, what is it worth after 2 years?",
    options: [
      { label: "A", text: "$14,000" },
      { label: "B", text: "$15,000" },
      { label: "C", text: "$16,000" },
      { label: "D", text: "$17,000" },
      { label: "E", text: "$18,000" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "How many minutes are in 2.5 hours?",
    options: [
      { label: "A", text: "120" },
      { label: "B", text: "130" },
      { label: "C", text: "140" },
      { label: "D", text: "150" },
      { label: "E", text: "160" },
    ],
    correctLabel: "D",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 1000 - 357?",
    options: [
      { label: "A", text: "633" },
      { label: "B", text: "643" },
      { label: "C", text: "653" },
      { label: "D", text: "663" },
      { label: "E", text: "743" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A store sells an item for $60, making a 20% profit. What did the store pay for it?",
    options: [
      { label: "A", text: "$45" },
      { label: "B", text: "$48" },
      { label: "C", text: "$50" },
      { label: "D", text: "$52" },
      { label: "E", text: "$54" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is √144 + √25?",
    options: [
      { label: "A", text: "15" },
      { label: "B", text: "17" },
      { label: "C", text: "19" },
      { label: "D", text: "13" },
      { label: "E", text: "11" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "In how many ways can 5 books be arranged on a shelf?",
    options: [
      { label: "A", text: "25" },
      { label: "B", text: "60" },
      { label: "C", text: "120" },
      { label: "D", text: "240" },
      { label: "E", text: "720" },
    ],
    correctLabel: "C",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is 0.125 expressed as a fraction in lowest terms?",
    options: [
      { label: "A", text: "1/8" },
      { label: "B", text: "1/6" },
      { label: "C", text: "1/4" },
      { label: "D", text: "3/8" },
      { label: "E", text: "1/5" },
    ],
    correctLabel: "A",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What comes next? 50, 45, 40, 35, ___",
    options: [
      { label: "A", text: "25" },
      { label: "B", text: "28" },
      { label: "C", text: "30" },
      { label: "D", text: "32" },
      { label: "E", text: "33" },
    ],
    correctLabel: "C",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What comes next? 100, 81, 64, 49, ___",
    options: [
      { label: "A", text: "25" },
      { label: "B", text: "36" },
      { label: "C", text: "40" },
      { label: "D", text: "32" },
      { label: "E", text: "16" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If a meeting starts at 2:45 PM and lasts 1 hour 35 minutes, when does it end?",
    options: [
      { label: "A", text: "4:10 PM" },
      { label: "B", text: "4:15 PM" },
      { label: "C", text: "4:20 PM" },
      { label: "D", text: "4:25 PM" },
      { label: "E", text: "4:30 PM" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "If 2^n = 512, what is n?",
    options: [
      { label: "A", text: "7" },
      { label: "B", text: "8" },
      { label: "C", text: "9" },
      { label: "D", text: "10" },
      { label: "E", text: "11" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "Jane has twice as many apples as Mark. Mark has 6 apples. How many does Jane have?",
    options: [
      { label: "A", text: "8" },
      { label: "B", text: "10" },
      { label: "C", text: "12" },
      { label: "D", text: "14" },
      { label: "E", text: "3" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A sequence follows the rule: multiply by 2 then subtract 1. Starting from 3, what is the 4th term?",
    options: [
      { label: "A", text: "17" },
      { label: "B", text: "19" },
      { label: "C", text: "21" },
      { label: "D", text: "33" },
      { label: "E", text: "37" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Three dice are rolled. What is the probability that all three show the same number?",
    options: [
      { label: "A", text: "1/36" },
      { label: "B", text: "1/6" },
      { label: "C", text: "6/216" },
      { label: "D", text: "1/216" },
      { label: "E", text: "3/216" },
    ],
    correctLabel: "C",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 12 × 12?",
    options: [
      { label: "A", text: "124" },
      { label: "B", text: "134" },
      { label: "C", text: "144" },
      { label: "D", text: "154" },
      { label: "E", text: "164" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 7/9 - 1/3?",
    options: [
      { label: "A", text: "4/9" },
      { label: "B", text: "5/9" },
      { label: "C", text: "2/3" },
      { label: "D", text: "1/3" },
      { label: "E", text: "6/9" },
    ],
    correctLabel: "A",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "How many diagonals does a hexagon have?",
    options: [
      { label: "A", text: "6" },
      { label: "B", text: "7" },
      { label: "C", text: "8" },
      { label: "D", text: "9" },
      { label: "E", text: "12" },
    ],
    correctLabel: "D",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If you share 20 cookies equally among 4 friends, how many does each get?",
    options: [
      { label: "A", text: "3" },
      { label: "B", text: "4" },
      { label: "C", text: "5" },
      { label: "D", text: "6" },
      { label: "E", text: "7" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Points scored in 6 games: 12, 18, 14, 22, 16, 20. What is the mean?",
    options: [
      { label: "A", text: "16" },
      { label: "B", text: "17" },
      { label: "C", text: "18" },
      { label: "D", text: "19" },
      { label: "E", text: "20" },
    ],
    correctLabel: "B",
    tags: ["data-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "The sum of 3 consecutive even numbers is 66. What is the largest?",
    options: [
      { label: "A", text: "20" },
      { label: "B", text: "22" },
      { label: "C", text: "24" },
      { label: "D", text: "26" },
      { label: "E", text: "28" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 8 × 9?",
    options: [
      { label: "A", text: "63" },
      { label: "B", text: "72" },
      { label: "C", text: "81" },
      { label: "D", text: "64" },
      { label: "E", text: "54" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What comes next? 6, 12, 18, 24, ___",
    options: [
      { label: "A", text: "28" },
      { label: "B", text: "30" },
      { label: "C", text: "32" },
      { label: "D", text: "36" },
      { label: "E", text: "26" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A pen costs $2. How much do 7 pens cost?",
    options: [
      { label: "A", text: "$12" },
      { label: "B", text: "$13" },
      { label: "C", text: "$14" },
      { label: "D", text: "$15" },
      { label: "E", text: "$16" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 14 × 16?",
    options: [
      { label: "A", text: "204" },
      { label: "B", text: "214" },
      { label: "C", text: "224" },
      { label: "D", text: "234" },
      { label: "E", text: "244" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What comes next? 0, 3, 8, 15, 24, ___",
    options: [
      { label: "A", text: "33" },
      { label: "B", text: "35" },
      { label: "C", text: "37" },
      { label: "D", text: "30" },
      { label: "E", text: "32" },
    ],
    correctLabel: "B",
    tags: ["number-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "An investment doubles every 5 years. If you invest $1000, how much after 15 years?",
    options: [
      { label: "A", text: "$4000" },
      { label: "B", text: "$6000" },
      { label: "C", text: "$8000" },
      { label: "D", text: "$3000" },
      { label: "E", text: "$16000" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If statement P implies statement Q, and Q is false, what can we conclude?",
    options: [
      { label: "A", text: "P is true" },
      { label: "B", text: "P is false" },
      { label: "C", text: "P could be true or false" },
      { label: "D", text: "Q is true" },
      { label: "E", text: "Nothing can be concluded" },
    ],
    correctLabel: "B",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is 15% of 15% of 10000?",
    options: [
      { label: "A", text: "225" },
      { label: "B", text: "250" },
      { label: "C", text: "150" },
      { label: "D", text: "300" },
      { label: "E", text: "175" },
    ],
    correctLabel: "A",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "If f(x) = 2x + 3 and g(x) = x², what is g(f(2))?",
    options: [
      { label: "A", text: "25" },
      { label: "B", text: "36" },
      { label: "C", text: "49" },
      { label: "D", text: "64" },
      { label: "E", text: "11" },
    ],
    correctLabel: "C",
    tags: ["algebra"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "Which number is NOT a factor of 24?",
    options: [
      { label: "A", text: "3" },
      { label: "B", text: "4" },
      { label: "C", text: "5" },
      { label: "D", text: "6" },
      { label: "E", text: "8" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A test has 40 questions. To pass, you need 70%. What is the minimum number of correct answers to pass?",
    options: [
      { label: "A", text: "26" },
      { label: "B", text: "27" },
      { label: "C", text: "28" },
      { label: "D", text: "29" },
      { label: "E", text: "30" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A number leaves remainder 2 when divided by 3, and remainder 3 when divided by 5. What is the smallest such positive number?",
    options: [
      { label: "A", text: "8" },
      { label: "B", text: "13" },
      { label: "C", text: "17" },
      { label: "D", text: "23" },
      { label: "E", text: "28" },
    ],
    correctLabel: "A",
    tags: ["logic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 11 × 11?",
    options: [
      { label: "A", text: "111" },
      { label: "B", text: "121" },
      { label: "C", text: "131" },
      { label: "D", text: "110" },
      { label: "E", text: "132" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If a number is increased by 50% and then decreased by 50%, the result is what percentage of the original?",
    options: [
      { label: "A", text: "100%" },
      { label: "B", text: "75%" },
      { label: "C", text: "50%" },
      { label: "D", text: "90%" },
      { label: "E", text: "80%" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is the least common multiple (LCM) of 12 and 18?",
    options: [
      { label: "A", text: "24" },
      { label: "B", text: "36" },
      { label: "C", text: "48" },
      { label: "D", text: "54" },
      { label: "E", text: "72" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
];
