type QuestionData = {
  category: "verbal" | "math_logic" | "spatial";
  difficulty: number;
  stem: string;
  options: { label: string; text: string }[];
  correctLabel: string;
  tags: string[];
};

export const mathLogicQuestions: QuestionData[] = [
  // ============================================================
  // ARITHMETIC (~25 questions)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 15 × 8?",
    options: [
      { label: "A", text: "105" },
      { label: "B", text: "120" },
      { label: "C", text: "130" },
      { label: "D", text: "115" },
      { label: "E", text: "125" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 144 ÷ 12?",
    options: [
      { label: "A", text: "11" },
      { label: "B", text: "13" },
      { label: "C", text: "12" },
      { label: "D", text: "14" },
      { label: "E", text: "10" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 37 + 48?",
    options: [
      { label: "A", text: "75" },
      { label: "B", text: "85" },
      { label: "C", text: "95" },
      { label: "D", text: "80" },
      { label: "E", text: "90" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 256 - 179?",
    options: [
      { label: "A", text: "87" },
      { label: "B", text: "67" },
      { label: "C", text: "77" },
      { label: "D", text: "83" },
      { label: "E", text: "73" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 9 × 11?",
    options: [
      { label: "A", text: "89" },
      { label: "B", text: "101" },
      { label: "C", text: "99" },
      { label: "D", text: "91" },
      { label: "E", text: "109" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 200 ÷ 8?",
    options: [
      { label: "A", text: "30" },
      { label: "B", text: "20" },
      { label: "C", text: "28" },
      { label: "D", text: "25" },
      { label: "E", text: "22" },
    ],
    correctLabel: "D",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 63 + 78?",
    options: [
      { label: "A", text: "131" },
      { label: "B", text: "141" },
      { label: "C", text: "151" },
      { label: "D", text: "139" },
      { label: "E", text: "149" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 23 × 17?",
    options: [
      { label: "A", text: "381" },
      { label: "B", text: "401" },
      { label: "C", text: "391" },
      { label: "D", text: "371" },
      { label: "E", text: "411" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 1,024 ÷ 16?",
    options: [
      { label: "A", text: "62" },
      { label: "B", text: "68" },
      { label: "C", text: "72" },
      { label: "D", text: "64" },
      { label: "E", text: "56" },
    ],
    correctLabel: "D",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 45 × 32?",
    options: [
      { label: "A", text: "1,440" },
      { label: "B", text: "1,340" },
      { label: "C", text: "1,540" },
      { label: "D", text: "1,380" },
      { label: "E", text: "1,420" },
    ],
    correctLabel: "A",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 3,456 ÷ 48?",
    options: [
      { label: "A", text: "68" },
      { label: "B", text: "74" },
      { label: "C", text: "72" },
      { label: "D", text: "76" },
      { label: "E", text: "70" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 125 × 24?",
    options: [
      { label: "A", text: "2,800" },
      { label: "B", text: "3,000" },
      { label: "C", text: "2,900" },
      { label: "D", text: "3,100" },
      { label: "E", text: "3,200" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 7,938 ÷ 63?",
    options: [
      { label: "A", text: "128" },
      { label: "B", text: "122" },
      { label: "C", text: "126" },
      { label: "D", text: "132" },
      { label: "E", text: "118" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 89 × 13?",
    options: [
      { label: "A", text: "1,167" },
      { label: "B", text: "1,147" },
      { label: "C", text: "1,137" },
      { label: "D", text: "1,157" },
      { label: "E", text: "1,177" },
    ],
    correctLabel: "D",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is 347 × 29?",
    options: [
      { label: "A", text: "10,163" },
      { label: "B", text: "10,063" },
      { label: "C", text: "9,963" },
      { label: "D", text: "10,263" },
      { label: "E", text: "10,363" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is 15,625 ÷ 125?",
    options: [
      { label: "A", text: "115" },
      { label: "B", text: "130" },
      { label: "C", text: "120" },
      { label: "D", text: "125" },
      { label: "E", text: "135" },
    ],
    correctLabel: "D",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 56 ÷ 7?",
    options: [
      { label: "A", text: "6" },
      { label: "B", text: "9" },
      { label: "C", text: "8" },
      { label: "D", text: "7" },
      { label: "E", text: "10" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 14 × 6?",
    options: [
      { label: "A", text: "74" },
      { label: "B", text: "84" },
      { label: "C", text: "78" },
      { label: "D", text: "80" },
      { label: "E", text: "86" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 2.5 × 3.6?",
    options: [
      { label: "A", text: "8.5" },
      { label: "B", text: "9.5" },
      { label: "C", text: "8.0" },
      { label: "D", text: "9.0" },
      { label: "E", text: "10.0" },
    ],
    correctLabel: "D",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 1,000 - 387?",
    options: [
      { label: "A", text: "623" },
      { label: "B", text: "613" },
      { label: "C", text: "603" },
      { label: "D", text: "633" },
      { label: "E", text: "593" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is 12³?",
    options: [
      { label: "A", text: "1,728" },
      { label: "B", text: "1,628" },
      { label: "C", text: "1,828" },
      { label: "D", text: "1,428" },
      { label: "E", text: "1,528" },
    ],
    correctLabel: "A",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 81 ÷ 9?",
    options: [
      { label: "A", text: "7" },
      { label: "B", text: "8" },
      { label: "C", text: "9" },
      { label: "D", text: "10" },
      { label: "E", text: "11" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is 0.75 × 240?",
    options: [
      { label: "A", text: "170" },
      { label: "B", text: "180" },
      { label: "C", text: "190" },
      { label: "D", text: "160" },
      { label: "E", text: "200" },
    ],
    correctLabel: "B",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is 17² - 13²?",
    options: [
      { label: "A", text: "100" },
      { label: "B", text: "110" },
      { label: "C", text: "120" },
      { label: "D", text: "130" },
      { label: "E", text: "140" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 25 × 4?",
    options: [
      { label: "A", text: "90" },
      { label: "B", text: "95" },
      { label: "C", text: "100" },
      { label: "D", text: "105" },
      { label: "E", text: "110" },
    ],
    correctLabel: "C",
    tags: ["arithmetic"],
  },

  // ============================================================
  // NUMBER SEQUENCES (~35 questions)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is the next number in the sequence: 2, 4, 6, 8, ___?",
    options: [
      { label: "A", text: "9" },
      { label: "B", text: "10" },
      { label: "C", text: "11" },
      { label: "D", text: "12" },
      { label: "E", text: "14" },
    ],
    correctLabel: "B",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is the next number in the sequence: 5, 10, 15, 20, ___?",
    options: [
      { label: "A", text: "22" },
      { label: "B", text: "24" },
      { label: "C", text: "25" },
      { label: "D", text: "30" },
      { label: "E", text: "35" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is the next number in the sequence: 3, 6, 9, 12, ___?",
    options: [
      { label: "A", text: "13" },
      { label: "B", text: "14" },
      { label: "C", text: "15" },
      { label: "D", text: "16" },
      { label: "E", text: "18" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is the next number in the sequence: 10, 20, 30, 40, ___?",
    options: [
      { label: "A", text: "45" },
      { label: "B", text: "50" },
      { label: "C", text: "55" },
      { label: "D", text: "60" },
      { label: "E", text: "70" },
    ],
    correctLabel: "B",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is the next number in the sequence: 100, 90, 80, 70, ___?",
    options: [
      { label: "A", text: "55" },
      { label: "B", text: "65" },
      { label: "C", text: "60" },
      { label: "D", text: "50" },
      { label: "E", text: "40" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is the next number in the sequence: 1, 3, 5, 7, ___?",
    options: [
      { label: "A", text: "8" },
      { label: "B", text: "9" },
      { label: "C", text: "10" },
      { label: "D", text: "11" },
      { label: "E", text: "12" },
    ],
    correctLabel: "B",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is the next number in the sequence: 7, 14, 21, 28, ___?",
    options: [
      { label: "A", text: "32" },
      { label: "B", text: "33" },
      { label: "C", text: "35" },
      { label: "D", text: "36" },
      { label: "E", text: "42" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 2, 6, 18, 54, ___?",
    options: [
      { label: "A", text: "108" },
      { label: "B", text: "162" },
      { label: "C", text: "128" },
      { label: "D", text: "216" },
      { label: "E", text: "148" },
    ],
    correctLabel: "B",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 1, 1, 2, 3, 5, 8, ___?",
    options: [
      { label: "A", text: "11" },
      { label: "B", text: "12" },
      { label: "C", text: "13" },
      { label: "D", text: "14" },
      { label: "E", text: "15" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 1, 4, 9, 16, 25, ___?",
    options: [
      { label: "A", text: "30" },
      { label: "B", text: "36" },
      { label: "C", text: "49" },
      { label: "D", text: "35" },
      { label: "E", text: "42" },
    ],
    correctLabel: "B",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 3, 9, 27, 81, ___?",
    options: [
      { label: "A", text: "162" },
      { label: "B", text: "216" },
      { label: "C", text: "243" },
      { label: "D", text: "324" },
      { label: "E", text: "189" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 2, 3, 5, 7, 11, 13, ___?",
    options: [
      { label: "A", text: "15" },
      { label: "B", text: "17" },
      { label: "C", text: "19" },
      { label: "D", text: "14" },
      { label: "E", text: "16" },
    ],
    correctLabel: "B",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 1, 2, 4, 8, 16, ___?",
    options: [
      { label: "A", text: "24" },
      { label: "B", text: "30" },
      { label: "C", text: "32" },
      { label: "D", text: "36" },
      { label: "E", text: "48" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 5, 11, 17, 23, 29, ___?",
    options: [
      { label: "A", text: "33" },
      { label: "B", text: "35" },
      { label: "C", text: "37" },
      { label: "D", text: "39" },
      { label: "E", text: "41" },
    ],
    correctLabel: "B",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 64, 32, 16, 8, ___?",
    options: [
      { label: "A", text: "2" },
      { label: "B", text: "6" },
      { label: "C", text: "4" },
      { label: "D", text: "3" },
      { label: "E", text: "0" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 1, 3, 7, 15, 31, ___?",
    options: [
      { label: "A", text: "47" },
      { label: "B", text: "55" },
      { label: "C", text: "61" },
      { label: "D", text: "63" },
      { label: "E", text: "59" },
    ],
    correctLabel: "D",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 0, 1, 4, 9, 16, 25, ___?",
    options: [
      { label: "A", text: "30" },
      { label: "B", text: "36" },
      { label: "C", text: "49" },
      { label: "D", text: "34" },
      { label: "E", text: "42" },
    ],
    correctLabel: "B",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 4, 7, 12, 19, 28, ___?",
    options: [
      { label: "A", text: "37" },
      { label: "B", text: "38" },
      { label: "C", text: "39" },
      { label: "D", text: "40" },
      { label: "E", text: "41" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 1, 8, 27, 64, ___?",
    options: [
      { label: "A", text: "100" },
      { label: "B", text: "125" },
      { label: "C", text: "128" },
      { label: "D", text: "216" },
      { label: "E", text: "81" },
    ],
    correctLabel: "B",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 2, 5, 10, 17, 26, ___?",
    options: [
      { label: "A", text: "33" },
      { label: "B", text: "35" },
      { label: "C", text: "37" },
      { label: "D", text: "39" },
      { label: "E", text: "41" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is the next number in the sequence: 1, 1, 2, 6, 24, 120, ___?",
    options: [
      { label: "A", text: "240" },
      { label: "B", text: "480" },
      { label: "C", text: "600" },
      { label: "D", text: "720" },
      { label: "E", text: "840" },
    ],
    correctLabel: "D",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is the next number in the sequence: 2, 3, 5, 9, 17, 33, ___?",
    options: [
      { label: "A", text: "57" },
      { label: "B", text: "63" },
      { label: "C", text: "65" },
      { label: "D", text: "66" },
      { label: "E", text: "49" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is the next number in the sequence: 1, 2, 6, 24, 120, ___?",
    options: [
      { label: "A", text: "240" },
      { label: "B", text: "360" },
      { label: "C", text: "480" },
      { label: "D", text: "600" },
      { label: "E", text: "720" },
    ],
    correctLabel: "E",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is the next number in the sequence: 0, 1, 1, 2, 3, 5, 8, 13, 21, ___?",
    options: [
      { label: "A", text: "28" },
      { label: "B", text: "30" },
      { label: "C", text: "32" },
      { label: "D", text: "34" },
      { label: "E", text: "36" },
    ],
    correctLabel: "D",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is the next number in the sequence: 1, 4, 10, 20, 35, ___?",
    options: [
      { label: "A", text: "50" },
      { label: "B", text: "56" },
      { label: "C", text: "52" },
      { label: "D", text: "60" },
      { label: "E", text: "48" },
    ],
    correctLabel: "B",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is the next number in the sequence: 4, 8, 12, 16, ___?",
    options: [
      { label: "A", text: "18" },
      { label: "B", text: "20" },
      { label: "C", text: "22" },
      { label: "D", text: "24" },
      { label: "E", text: "28" },
    ],
    correctLabel: "B",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is the next number in the sequence: 50, 45, 40, 35, ___?",
    options: [
      { label: "A", text: "25" },
      { label: "B", text: "28" },
      { label: "C", text: "30" },
      { label: "D", text: "32" },
      { label: "E", text: "33" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 3, 6, 12, 24, 48, ___?",
    options: [
      { label: "A", text: "72" },
      { label: "B", text: "84" },
      { label: "C", text: "96" },
      { label: "D", text: "60" },
      { label: "E", text: "108" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 1, 3, 6, 10, 15, ___?",
    options: [
      { label: "A", text: "18" },
      { label: "B", text: "20" },
      { label: "C", text: "21" },
      { label: "D", text: "24" },
      { label: "E", text: "25" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is the next number in the sequence: 2, 6, 14, 30, 62, ___?",
    options: [
      { label: "A", text: "94" },
      { label: "B", text: "124" },
      { label: "C", text: "126" },
      { label: "D", text: "130" },
      { label: "E", text: "118" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 10, 7, 4, 1, ___?",
    options: [
      { label: "A", text: "0" },
      { label: "B", text: "-1" },
      { label: "C", text: "-2" },
      { label: "D", text: "-3" },
      { label: "E", text: "2" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is the next number in the sequence: 11, 22, 33, 44, ___?",
    options: [
      { label: "A", text: "50" },
      { label: "B", text: "54" },
      { label: "C", text: "55" },
      { label: "D", text: "56" },
      { label: "E", text: "66" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What is the next number in the sequence: 1, 3, 7, 13, 21, 31, ___?",
    options: [
      { label: "A", text: "39" },
      { label: "B", text: "41" },
      { label: "C", text: "43" },
      { label: "D", text: "45" },
      { label: "E", text: "47" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What is the next number in the sequence: 256, 128, 64, 32, ___?",
    options: [
      { label: "A", text: "8" },
      { label: "B", text: "12" },
      { label: "C", text: "16" },
      { label: "D", text: "20" },
      { label: "E", text: "24" },
    ],
    correctLabel: "C",
    tags: ["number-sequence"],
  },

  // ============================================================
  // PERCENTAGES (~25 questions)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A shirt originally costs $40. If it is on sale for 25% off, what is the sale price?",
    options: [
      { label: "A", text: "$25" },
      { label: "B", text: "$30" },
      { label: "C", text: "$35" },
      { label: "D", text: "$20" },
      { label: "E", text: "$28" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 10% of 250?",
    options: [
      { label: "A", text: "20" },
      { label: "B", text: "25" },
      { label: "C", text: "30" },
      { label: "D", text: "15" },
      { label: "E", text: "35" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A store increases the price of a $60 item by 10%. What is the new price?",
    options: [
      { label: "A", text: "$64" },
      { label: "B", text: "$66" },
      { label: "C", text: "$70" },
      { label: "D", text: "$68" },
      { label: "E", text: "$72" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 50% of 84?",
    options: [
      { label: "A", text: "38" },
      { label: "B", text: "40" },
      { label: "C", text: "42" },
      { label: "D", text: "44" },
      { label: "E", text: "46" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A laptop costs $800. After a 15% discount and then an 8% sales tax on the discounted price, what is the total cost?",
    options: [
      { label: "A", text: "$724.80" },
      { label: "B", text: "$734.40" },
      { label: "C", text: "$744.00" },
      { label: "D", text: "$712.80" },
      { label: "E", text: "$748.80" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A restaurant bill is $85. If you leave a 20% tip, what is the total amount you pay?",
    options: [
      { label: "A", text: "$100" },
      { label: "B", text: "$102" },
      { label: "C", text: "$105" },
      { label: "D", text: "$104" },
      { label: "E", text: "$98" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A company's revenue grew from $2 million to $2.5 million. What is the percentage increase?",
    options: [
      { label: "A", text: "20%" },
      { label: "B", text: "25%" },
      { label: "C", text: "30%" },
      { label: "D", text: "15%" },
      { label: "E", text: "50%" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A jacket is marked down 30% from $120. What is the sale price?",
    options: [
      { label: "A", text: "$84" },
      { label: "B", text: "$90" },
      { label: "C", text: "$86" },
      { label: "D", text: "$88" },
      { label: "E", text: "$92" },
    ],
    correctLabel: "A",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "An employee earns $55,000 per year and receives a 4% raise. What is the new salary?",
    options: [
      { label: "A", text: "$56,200" },
      { label: "B", text: "$57,200" },
      { label: "C", text: "$57,000" },
      { label: "D", text: "$56,800" },
      { label: "E", text: "$58,000" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A population decreased from 8,000 to 6,800. What is the percentage decrease?",
    options: [
      { label: "A", text: "12%" },
      { label: "B", text: "18%" },
      { label: "C", text: "15%" },
      { label: "D", text: "20%" },
      { label: "E", text: "10%" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "You bought a stock at $40 and sold it at $52. What is your percentage profit?",
    options: [
      { label: "A", text: "25%" },
      { label: "B", text: "30%" },
      { label: "C", text: "35%" },
      { label: "D", text: "20%" },
      { label: "E", text: "12%" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A store offers a 20% discount, then takes an additional 10% off the discounted price. What is the total percentage discount from the original price?",
    options: [
      { label: "A", text: "28%" },
      { label: "B", text: "30%" },
      { label: "C", text: "32%" },
      { label: "D", text: "26%" },
      { label: "E", text: "25%" },
    ],
    correctLabel: "A",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A product's price is increased by 25% and then decreased by 20%. What is the net percentage change from the original price?",
    options: [
      { label: "A", text: "5% increase" },
      { label: "B", text: "No change" },
      { label: "C", text: "5% decrease" },
      { label: "D", text: "10% increase" },
      { label: "E", text: "2% decrease" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A meal costs $45 before tax. If the tax rate is 9%, how much is the tax?",
    options: [
      { label: "A", text: "$3.85" },
      { label: "B", text: "$4.05" },
      { label: "C", text: "$4.50" },
      { label: "D", text: "$3.60" },
      { label: "E", text: "$4.95" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 20% of 150?",
    options: [
      { label: "A", text: "25" },
      { label: "B", text: "30" },
      { label: "C", text: "35" },
      { label: "D", text: "40" },
      { label: "E", text: "45" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If a car depreciates 12% per year and was worth $25,000 new, what is it worth after one year?",
    options: [
      { label: "A", text: "$21,000" },
      { label: "B", text: "$22,000" },
      { label: "C", text: "$23,000" },
      { label: "D", text: "$22,500" },
      { label: "E", text: "$21,500" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "An investment earns 8% interest compounded annually. If you invest $1,000, how much will you have after 2 years (rounded to the nearest dollar)?",
    options: [
      { label: "A", text: "$1,160" },
      { label: "B", text: "$1,166" },
      { label: "C", text: "$1,170" },
      { label: "D", text: "$1,180" },
      { label: "E", text: "$1,152" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A book costs $16. If it is discounted by 25%, what do you pay?",
    options: [
      { label: "A", text: "$10" },
      { label: "B", text: "$11" },
      { label: "C", text: "$12" },
      { label: "D", text: "$13" },
      { label: "E", text: "$14" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A shop owner buys goods for $200 and sells them for $270. What is the profit percentage?",
    options: [
      { label: "A", text: "30%" },
      { label: "B", text: "35%" },
      { label: "C", text: "40%" },
      { label: "D", text: "25%" },
      { label: "E", text: "27%" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A test has 80 questions. If you answered 68 correctly, what percentage did you get right?",
    options: [
      { label: "A", text: "80%" },
      { label: "B", text: "82%" },
      { label: "C", text: "85%" },
      { label: "D", text: "88%" },
      { label: "E", text: "90%" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A house was bought for $250,000. It appreciated by 6% the first year and 4% the second year. What is its value after two years?",
    options: [
      { label: "A", text: "$272,500" },
      { label: "B", text: "$275,600" },
      { label: "C", text: "$276,000" },
      { label: "D", text: "$278,200" },
      { label: "E", text: "$280,000" },
    ],
    correctLabel: "B",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What is 75% of 200?",
    options: [
      { label: "A", text: "140" },
      { label: "B", text: "145" },
      { label: "C", text: "150" },
      { label: "D", text: "155" },
      { label: "E", text: "160" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A phone that costs $600 is on sale for $480. What is the discount percentage?",
    options: [
      { label: "A", text: "15%" },
      { label: "B", text: "18%" },
      { label: "C", text: "20%" },
      { label: "D", text: "22%" },
      { label: "E", text: "25%" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "In a class of 40 students, 60% are female. How many male students are there?",
    options: [
      { label: "A", text: "12" },
      { label: "B", text: "14" },
      { label: "C", text: "16" },
      { label: "D", text: "18" },
      { label: "E", text: "20" },
    ],
    correctLabel: "C",
    tags: ["percentage"],
  },

  // ============================================================
  // WORD PROBLEMS (~45 questions)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A train travels at 60 miles per hour. How far does it travel in 3 hours?",
    options: [
      { label: "A", text: "150 miles" },
      { label: "B", text: "180 miles" },
      { label: "C", text: "200 miles" },
      { label: "D", text: "160 miles" },
      { label: "E", text: "120 miles" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If 5 apples cost $3.75, how much does one apple cost?",
    options: [
      { label: "A", text: "$0.65" },
      { label: "B", text: "$0.70" },
      { label: "C", text: "$0.75" },
      { label: "D", text: "$0.80" },
      { label: "E", text: "$0.85" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A rectangle has a length of 12 cm and a width of 5 cm. What is its area?",
    options: [
      { label: "A", text: "50 cm²" },
      { label: "B", text: "55 cm²" },
      { label: "C", text: "60 cm²" },
      { label: "D", text: "65 cm²" },
      { label: "E", text: "70 cm²" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "Maria has 24 cookies and wants to divide them equally among 6 friends. How many cookies does each friend get?",
    options: [
      { label: "A", text: "3" },
      { label: "B", text: "4" },
      { label: "C", text: "5" },
      { label: "D", text: "6" },
      { label: "E", text: "8" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A movie starts at 2:15 PM and lasts 1 hour and 45 minutes. What time does it end?",
    options: [
      { label: "A", text: "3:45 PM" },
      { label: "B", text: "3:50 PM" },
      { label: "C", text: "4:00 PM" },
      { label: "D", text: "4:15 PM" },
      { label: "E", text: "3:30 PM" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A car travels 240 miles using 8 gallons of gas. How many miles per gallon does the car get?",
    options: [
      { label: "A", text: "25 mpg" },
      { label: "B", text: "28 mpg" },
      { label: "C", text: "30 mpg" },
      { label: "D", text: "32 mpg" },
      { label: "E", text: "35 mpg" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A painter can paint a room in 6 hours. Another painter can paint the same room in 4 hours. If they work together, approximately how long will it take?",
    options: [
      { label: "A", text: "2 hours" },
      { label: "B", text: "2 hours 24 minutes" },
      { label: "C", text: "2 hours 30 minutes" },
      { label: "D", text: "3 hours" },
      { label: "E", text: "3 hours 20 minutes" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "The average of five numbers is 42. If four of the numbers are 38, 40, 45, and 50, what is the fifth number?",
    options: [
      { label: "A", text: "35" },
      { label: "B", text: "37" },
      { label: "C", text: "39" },
      { label: "D", text: "41" },
      { label: "E", text: "43" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A store sells 3 pens for $5.25. How much would 8 pens cost?",
    options: [
      { label: "A", text: "$12.00" },
      { label: "B", text: "$13.00" },
      { label: "C", text: "$14.00" },
      { label: "D", text: "$15.00" },
      { label: "E", text: "$16.00" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A rectangular garden is 15 meters long and 10 meters wide. If fencing costs $12 per meter, how much will it cost to fence the entire garden?",
    options: [
      { label: "A", text: "$500" },
      { label: "B", text: "$540" },
      { label: "C", text: "$580" },
      { label: "D", text: "$600" },
      { label: "E", text: "$720" },
    ],
    correctLabel: "D",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "John earns $18 per hour. He worked 35 hours this week and 42 hours last week. What are his total earnings for the two weeks?",
    options: [
      { label: "A", text: "$1,286" },
      { label: "B", text: "$1,336" },
      { label: "C", text: "$1,386" },
      { label: "D", text: "$1,436" },
      { label: "E", text: "$1,260" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A tank holds 500 liters of water. If water drains at a rate of 15 liters per minute, how many minutes will it take to empty the tank?",
    options: [
      { label: "A", text: "30 minutes" },
      { label: "B", text: "33 minutes 20 seconds" },
      { label: "C", text: "35 minutes" },
      { label: "D", text: "25 minutes" },
      { label: "E", text: "40 minutes" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A recipe calls for 2.5 cups of flour to make 12 cookies. How many cups of flour are needed to make 30 cookies?",
    options: [
      { label: "A", text: "5.5 cups" },
      { label: "B", text: "6 cups" },
      { label: "C", text: "6.25 cups" },
      { label: "D", text: "6.5 cups" },
      { label: "E", text: "7 cups" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Two cars start from the same point traveling in opposite directions. One travels at 55 mph and the other at 65 mph. How far apart are they after 3 hours?",
    options: [
      { label: "A", text: "330 miles" },
      { label: "B", text: "345 miles" },
      { label: "C", text: "360 miles" },
      { label: "D", text: "375 miles" },
      { label: "E", text: "390 miles" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A school has 480 students. If the student-to-teacher ratio is 20:1, how many teachers does the school have?",
    options: [
      { label: "A", text: "20" },
      { label: "B", text: "22" },
      { label: "C", text: "24" },
      { label: "D", text: "26" },
      { label: "E", text: "28" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Pipe A fills a pool in 8 hours and Pipe B fills it in 12 hours. If both pipes are opened simultaneously, but Pipe A is turned off after 3 hours, how long does it take in total to fill the pool?",
    options: [
      { label: "A", text: "6 hours 15 minutes" },
      { label: "B", text: "6 hours 30 minutes" },
      { label: "C", text: "7 hours" },
      { label: "D", text: "7 hours 30 minutes" },
      { label: "E", text: "8 hours" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A cyclist travels from Town A to Town B at 20 km/h and returns at 30 km/h. If the towns are 60 km apart, what is the average speed for the entire trip?",
    options: [
      { label: "A", text: "22 km/h" },
      { label: "B", text: "24 km/h" },
      { label: "C", text: "25 km/h" },
      { label: "D", text: "26 km/h" },
      { label: "E", text: "28 km/h" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A baker makes 48 muffins. If each box holds 6 muffins, how many boxes does the baker need?",
    options: [
      { label: "A", text: "6" },
      { label: "B", text: "7" },
      { label: "C", text: "8" },
      { label: "D", text: "9" },
      { label: "E", text: "10" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "Tom has $50. He buys a book for $12 and a notebook for $8. How much money does he have left?",
    options: [
      { label: "A", text: "$28" },
      { label: "B", text: "$30" },
      { label: "C", text: "$32" },
      { label: "D", text: "$34" },
      { label: "E", text: "$26" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A contractor needs to tile a floor that is 18 feet by 24 feet. If each tile covers 4 square feet, how many tiles are needed?",
    options: [
      { label: "A", text: "96" },
      { label: "B", text: "104" },
      { label: "C", text: "108" },
      { label: "D", text: "112" },
      { label: "E", text: "120" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A bus leaves at 8:30 AM and arrives at 11:15 AM. If the total distance is 198 miles, what is the average speed?",
    options: [
      { label: "A", text: "66 mph" },
      { label: "B", text: "70 mph" },
      { label: "C", text: "72 mph" },
      { label: "D", text: "74 mph" },
      { label: "E", text: "68 mph" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A store sells notebooks in packs of 3 for $7.50 or individually for $3.00 each. How much do you save by buying a pack of 3 instead of 3 individual notebooks?",
    options: [
      { label: "A", text: "$0.50" },
      { label: "B", text: "$1.00" },
      { label: "C", text: "$1.50" },
      { label: "D", text: "$2.00" },
      { label: "E", text: "$2.50" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Worker A can complete a project in 10 days. Worker B can complete it in 15 days. Worker C can complete it in 30 days. If all three work together, how many days will it take to complete the project?",
    options: [
      { label: "A", text: "4 days" },
      { label: "B", text: "5 days" },
      { label: "C", text: "6 days" },
      { label: "D", text: "7 days" },
      { label: "E", text: "8 days" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A parking lot has 4 rows with 15 cars in each row. How many cars are in the parking lot?",
    options: [
      { label: "A", text: "50" },
      { label: "B", text: "55" },
      { label: "C", text: "60" },
      { label: "D", text: "65" },
      { label: "E", text: "70" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A plane flies from City A to City B in 2.5 hours at 480 mph. On the return trip, headwinds reduce its speed to 400 mph. How long does the return trip take?",
    options: [
      { label: "A", text: "2 hours 30 minutes" },
      { label: "B", text: "2 hours 45 minutes" },
      { label: "C", text: "3 hours" },
      { label: "D", text: "3 hours 15 minutes" },
      { label: "E", text: "3 hours 30 minutes" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A company ships boxes that weigh 35 pounds each. If a truck can carry 2,100 pounds, how many boxes can the truck carry?",
    options: [
      { label: "A", text: "55" },
      { label: "B", text: "58" },
      { label: "C", text: "60" },
      { label: "D", text: "62" },
      { label: "E", text: "65" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Sarah buys 3 shirts at $22 each and 2 pairs of pants at $35 each. What is her total bill?",
    options: [
      { label: "A", text: "$126" },
      { label: "B", text: "$130" },
      { label: "C", text: "$134" },
      { label: "D", text: "$136" },
      { label: "E", text: "$140" },
    ],
    correctLabel: "D",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A boat travels 36 km upstream in 4 hours and returns downstream in 3 hours. What is the speed of the current?",
    options: [
      { label: "A", text: "1 km/h" },
      { label: "B", text: "1.5 km/h" },
      { label: "C", text: "2 km/h" },
      { label: "D", text: "2.5 km/h" },
      { label: "E", text: "3 km/h" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A classroom has 28 desks arranged in 4 equal rows. How many desks are in each row?",
    options: [
      { label: "A", text: "5" },
      { label: "B", text: "6" },
      { label: "C", text: "7" },
      { label: "D", text: "8" },
      { label: "E", text: "9" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A warehouse has 1,250 items. If 35% are electronics, 40% are clothing, and the rest are furniture, how many furniture items are there?",
    options: [
      { label: "A", text: "275" },
      { label: "B", text: "300" },
      { label: "C", text: "312.5" },
      { label: "D", text: "325" },
      { label: "E", text: "350" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A circular pool has a diameter of 14 feet. What is the approximate area of the pool? (Use π ≈ 3.14)",
    options: [
      { label: "A", text: "143.86 sq ft" },
      { label: "B", text: "149.50 sq ft" },
      { label: "C", text: "153.86 sq ft" },
      { label: "D", text: "157.00 sq ft" },
      { label: "E", text: "161.14 sq ft" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Two trains leave stations 400 miles apart and travel toward each other. Train A travels at 70 mph and Train B at 80 mph. After how many hours will they meet? (Round to nearest tenth)",
    options: [
      { label: "A", text: "2.3 hours" },
      { label: "B", text: "2.5 hours" },
      { label: "C", text: "2.7 hours" },
      { label: "D", text: "3.0 hours" },
      { label: "E", text: "3.3 hours" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "Emma reads 15 pages per hour. How many pages can she read in 4 hours?",
    options: [
      { label: "A", text: "45" },
      { label: "B", text: "50" },
      { label: "C", text: "55" },
      { label: "D", text: "60" },
      { label: "E", text: "65" },
    ],
    correctLabel: "D",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A water tank is 3/4 full. If it contains 450 liters, what is the total capacity of the tank?",
    options: [
      { label: "A", text: "525 liters" },
      { label: "B", text: "550 liters" },
      { label: "C", text: "575 liters" },
      { label: "D", text: "600 liters" },
      { label: "E", text: "625 liters" },
    ],
    correctLabel: "D",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "An office orders coffee beans at $12 per pound. If the office uses 3.5 pounds per week, what is the monthly cost (assuming 4 weeks per month)?",
    options: [
      { label: "A", text: "$156" },
      { label: "B", text: "$162" },
      { label: "C", text: "$168" },
      { label: "D", text: "$174" },
      { label: "E", text: "$180" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A mixture contains milk and water in the ratio 5:3. If 16 liters of the mixture are removed and replaced with water, the ratio becomes 3:5. What was the original volume of the mixture?",
    options: [
      { label: "A", text: "28 liters" },
      { label: "B", text: "32 liters" },
      { label: "C", text: "36 liters" },
      { label: "D", text: "40 liters" },
      { label: "E", text: "48 liters" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A rope is 36 feet long. If it is cut into 4 equal pieces, how long is each piece?",
    options: [
      { label: "A", text: "7 feet" },
      { label: "B", text: "8 feet" },
      { label: "C", text: "9 feet" },
      { label: "D", text: "10 feet" },
      { label: "E", text: "12 feet" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A conference room is booked from 9:00 AM to 4:30 PM with a 45-minute lunch break. How many hours of meeting time are available?",
    options: [
      { label: "A", text: "6 hours" },
      { label: "B", text: "6 hours 15 minutes" },
      { label: "C", text: "6 hours 30 minutes" },
      { label: "D", text: "6 hours 45 minutes" },
      { label: "E", text: "7 hours" },
    ],
    correctLabel: "D",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A factory produces 840 units in 7 hours. If the factory operates at the same rate, how many units will it produce in 10 hours?",
    options: [
      { label: "A", text: "1,100" },
      { label: "B", text: "1,150" },
      { label: "C", text: "1,200" },
      { label: "D", text: "1,250" },
      { label: "E", text: "1,300" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A ladder is leaning against a wall. The base of the ladder is 6 feet from the wall, and the ladder is 10 feet long. How high up the wall does the ladder reach?",
    options: [
      { label: "A", text: "7 feet" },
      { label: "B", text: "8 feet" },
      { label: "C", text: "9 feet" },
      { label: "D", text: "7.5 feet" },
      { label: "E", text: "8.5 feet" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A dozen eggs costs $3.60. How much does one egg cost?",
    options: [
      { label: "A", text: "$0.25" },
      { label: "B", text: "$0.30" },
      { label: "C", text: "$0.35" },
      { label: "D", text: "$0.40" },
      { label: "E", text: "$0.45" },
    ],
    correctLabel: "B",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A salesperson earns a base salary of $400 per week plus a 5% commission on sales. If they sell $6,000 worth of goods in one week, what is their total pay?",
    options: [
      { label: "A", text: "$650" },
      { label: "B", text: "$680" },
      { label: "C", text: "$700" },
      { label: "D", text: "$720" },
      { label: "E", text: "$750" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A project takes 12 workers 8 days to complete. Due to budget cuts, only 6 workers are available. How many days will it take the smaller team to complete the project?",
    options: [
      { label: "A", text: "12 days" },
      { label: "B", text: "14 days" },
      { label: "C", text: "16 days" },
      { label: "D", text: "18 days" },
      { label: "E", text: "20 days" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If a car uses 5 liters of fuel per 100 km, how many liters are needed for a 300 km trip?",
    options: [
      { label: "A", text: "10 liters" },
      { label: "B", text: "12 liters" },
      { label: "C", text: "15 liters" },
      { label: "D", text: "18 liters" },
      { label: "E", text: "20 liters" },
    ],
    correctLabel: "C",
    tags: ["word-problem"],
  },

  // ============================================================
  // RATIOS (~20 questions)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If the ratio of boys to girls in a class is 3:2, and there are 30 students total, how many boys are there?",
    options: [
      { label: "A", text: "12" },
      { label: "B", text: "15" },
      { label: "C", text: "18" },
      { label: "D", text: "20" },
      { label: "E", text: "10" },
    ],
    correctLabel: "C",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A map has a scale of 1 cm = 5 km. If two cities are 8 cm apart on the map, what is the actual distance?",
    options: [
      { label: "A", text: "35 km" },
      { label: "B", text: "40 km" },
      { label: "C", text: "45 km" },
      { label: "D", text: "50 km" },
      { label: "E", text: "30 km" },
    ],
    correctLabel: "B",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A recipe for 4 servings requires 2 cups of rice. How many cups of rice are needed for 10 servings?",
    options: [
      { label: "A", text: "4 cups" },
      { label: "B", text: "4.5 cups" },
      { label: "C", text: "5 cups" },
      { label: "D", text: "5.5 cups" },
      { label: "E", text: "6 cups" },
    ],
    correctLabel: "C",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A bag contains red and blue marbles in the ratio 4:7. If there are 44 marbles in total, how many are blue?",
    options: [
      { label: "A", text: "24" },
      { label: "B", text: "26" },
      { label: "C", text: "28" },
      { label: "D", text: "30" },
      { label: "E", text: "32" },
    ],
    correctLabel: "C",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A standard deck of 52 cards has 4 aces. What is the probability of drawing an ace at random?",
    options: [
      { label: "A", text: "1/10" },
      { label: "B", text: "1/13" },
      { label: "C", text: "1/15" },
      { label: "D", text: "1/12" },
      { label: "E", text: "1/52" },
    ],
    correctLabel: "B",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If 3 machines produce 120 units in 4 hours, how many units can 5 machines produce in 6 hours?",
    options: [
      { label: "A", text: "250" },
      { label: "B", text: "280" },
      { label: "C", text: "300" },
      { label: "D", text: "320" },
      { label: "E", text: "360" },
    ],
    correctLabel: "C",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A concrete mix requires cement, sand, and gravel in the ratio 1:2:4. If you need 21 kg of mix total, how much sand is needed?",
    options: [
      { label: "A", text: "3 kg" },
      { label: "B", text: "4 kg" },
      { label: "C", text: "5 kg" },
      { label: "D", text: "6 kg" },
      { label: "E", text: "7 kg" },
    ],
    correctLabel: "D",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "In a survey, the ratio of people who prefer coffee to tea to juice is 5:3:2. If 200 people were surveyed, how many prefer tea?",
    options: [
      { label: "A", text: "40" },
      { label: "B", text: "50" },
      { label: "C", text: "60" },
      { label: "D", text: "70" },
      { label: "E", text: "80" },
    ],
    correctLabel: "C",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A model building is built at a scale of 1:50. If the model is 30 cm tall, how tall is the actual building?",
    options: [
      { label: "A", text: "12 m" },
      { label: "B", text: "15 m" },
      { label: "C", text: "18 m" },
      { label: "D", text: "20 m" },
      { label: "E", text: "25 m" },
    ],
    correctLabel: "B",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A jar contains 5 red, 3 blue, and 2 green marbles. If two marbles are drawn without replacement, what is the probability that both are red?",
    options: [
      { label: "A", text: "1/4" },
      { label: "B", text: "2/9" },
      { label: "C", text: "1/5" },
      { label: "D", text: "5/18" },
      { label: "E", text: "1/3" },
    ],
    correctLabel: "B",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Two dice are rolled. What is the probability that the sum is 7?",
    options: [
      { label: "A", text: "1/9" },
      { label: "B", text: "1/8" },
      { label: "C", text: "1/6" },
      { label: "D", text: "5/36" },
      { label: "E", text: "7/36" },
    ],
    correctLabel: "C",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If a car travels 3 miles for every 1 gallon of gas, how many gallons are needed for a 24-mile trip?",
    options: [
      { label: "A", text: "6" },
      { label: "B", text: "7" },
      { label: "C", text: "8" },
      { label: "D", text: "9" },
      { label: "E", text: "10" },
    ],
    correctLabel: "C",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "An investment of $4,000 yields a profit of $600 in one year. At the same rate, what profit would a $10,000 investment yield?",
    options: [
      { label: "A", text: "$1,200" },
      { label: "B", text: "$1,350" },
      { label: "C", text: "$1,500" },
      { label: "D", text: "$1,650" },
      { label: "E", text: "$1,800" },
    ],
    correctLabel: "C",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A fruit punch recipe mixes apple juice and cranberry juice in a ratio of 3:1. If you want to make 2 liters of punch, how much cranberry juice do you need?",
    options: [
      { label: "A", text: "250 ml" },
      { label: "B", text: "400 ml" },
      { label: "C", text: "500 ml" },
      { label: "D", text: "600 ml" },
      { label: "E", text: "750 ml" },
    ],
    correctLabel: "C",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A bag has 6 red and 4 blue balls. If 3 balls are drawn at random without replacement, what is the probability that all 3 are red?",
    options: [
      { label: "A", text: "1/6" },
      { label: "B", text: "1/5" },
      { label: "C", text: "1/4" },
      { label: "D", text: "2/15" },
      { label: "E", text: "3/10" },
    ],
    correctLabel: "A",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If 2 workers can build a wall in 6 days, how many days would it take 6 workers to build the same wall?",
    options: [
      { label: "A", text: "1 day" },
      { label: "B", text: "2 days" },
      { label: "C", text: "3 days" },
      { label: "D", text: "4 days" },
      { label: "E", text: "5 days" },
    ],
    correctLabel: "B",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Gold and silver are mixed in the ratio 3:5. If the mixture weighs 480 grams, how much gold is in the mixture?",
    options: [
      { label: "A", text: "150 g" },
      { label: "B", text: "160 g" },
      { label: "C", text: "170 g" },
      { label: "D", text: "180 g" },
      { label: "E", text: "200 g" },
    ],
    correctLabel: "D",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A coin is flipped 3 times. What is the probability of getting exactly 2 heads?",
    options: [
      { label: "A", text: "1/4" },
      { label: "B", text: "3/8" },
      { label: "C", text: "1/2" },
      { label: "D", text: "1/3" },
      { label: "E", text: "2/8" },
    ],
    correctLabel: "B",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A blueprint has a scale of 1 inch = 4 feet. If a room is 5 inches long on the blueprint, how long is the actual room?",
    options: [
      { label: "A", text: "16 feet" },
      { label: "B", text: "18 feet" },
      { label: "C", text: "20 feet" },
      { label: "D", text: "22 feet" },
      { label: "E", text: "24 feet" },
    ],
    correctLabel: "C",
    tags: ["ratio"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "In a bag of 50 candies, the ratio of chocolate to caramel to mint is 4:3:3. How many chocolate candies are there?",
    options: [
      { label: "A", text: "15" },
      { label: "B", text: "18" },
      { label: "C", text: "20" },
      { label: "D", text: "22" },
      { label: "E", text: "25" },
    ],
    correctLabel: "C",
    tags: ["ratio"],
  },

  // ============================================================
  // LOGICAL DEDUCTION (~35 questions)
  // ============================================================
  {
    category: "math_logic",
    difficulty: 1,
    stem: "All roses are flowers. All flowers need water. Therefore:",
    options: [
      { label: "A", text: "All things that need water are roses" },
      { label: "B", text: "All roses need water" },
      { label: "C", text: "Some flowers are not roses" },
      { label: "D", text: "Water is needed only by roses" },
      { label: "E", text: "Not all flowers need water" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If all cats are animals, and Whiskers is a cat, what can we conclude?",
    options: [
      { label: "A", text: "All animals are cats" },
      { label: "B", text: "Whiskers is not an animal" },
      { label: "C", text: "Whiskers is an animal" },
      { label: "D", text: "Some animals are not cats" },
      { label: "E", text: "Whiskers is the only cat" },
    ],
    correctLabel: "C",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If it rains, the ground gets wet. The ground is wet. What can we conclude?",
    options: [
      { label: "A", text: "It definitely rained" },
      { label: "B", text: "It did not rain" },
      { label: "C", text: "The ground is always wet" },
      { label: "D", text: "It may or may not have rained" },
      { label: "E", text: "Rain is the only cause of wet ground" },
    ],
    correctLabel: "D",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "Tom is taller than Jerry. Jerry is taller than Spike. Who is the shortest?",
    options: [
      { label: "A", text: "Tom" },
      { label: "B", text: "Jerry" },
      { label: "C", text: "Spike" },
      { label: "D", text: "Tom and Jerry are the same height" },
      { label: "E", text: "Cannot be determined" },
    ],
    correctLabel: "C",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "No birds are reptiles. A parrot is a bird. Therefore:",
    options: [
      { label: "A", text: "A parrot might be a reptile" },
      { label: "B", text: "A parrot is not a reptile" },
      { label: "C", text: "All non-reptiles are birds" },
      { label: "D", text: "Some reptiles are birds" },
      { label: "E", text: "Parrots are the only birds" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Five friends — Alice, Bob, Carol, Dave, and Eve — are sitting in a row. Alice is next to Bob. Carol is not next to Dave. Eve is at one end. Bob is in the middle. Who is at the other end?",
    options: [
      { label: "A", text: "Alice" },
      { label: "B", text: "Carol" },
      { label: "C", text: "Dave" },
      { label: "D", text: "Either Carol or Dave" },
      { label: "E", text: "Cannot be determined" },
    ],
    correctLabel: "D",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "All managers attend meetings. Some employees are managers. Therefore:",
    options: [
      { label: "A", text: "All employees attend meetings" },
      { label: "B", text: "Some employees attend meetings" },
      { label: "C", text: "No employees attend meetings" },
      { label: "D", text: "All meeting attendees are managers" },
      { label: "E", text: "Managers are not employees" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If P is true, then Q is true. Q is false. What can we conclude?",
    options: [
      { label: "A", text: "P is true" },
      { label: "B", text: "P is false" },
      { label: "C", text: "P might be true or false" },
      { label: "D", text: "Q is true" },
      { label: "E", text: "Nothing can be concluded" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "In a race, Alex finished before Brian but after Charlie. Dave finished after Brian. Who finished second?",
    options: [
      { label: "A", text: "Charlie" },
      { label: "B", text: "Alex" },
      { label: "C", text: "Brian" },
      { label: "D", text: "Dave" },
      { label: "E", text: "Cannot be determined" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If a shape is a square, then it has four equal sides. Shape X has four equal sides. What can we conclude?",
    options: [
      { label: "A", text: "Shape X is definitely a square" },
      { label: "B", text: "Shape X is not a square" },
      { label: "C", text: "Shape X might or might not be a square" },
      { label: "D", text: "All shapes with four sides are squares" },
      { label: "E", text: "Shape X has four right angles" },
    ],
    correctLabel: "C",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "All doctors have medical degrees. No plumbers have medical degrees. Therefore:",
    options: [
      { label: "A", text: "Some plumbers are doctors" },
      { label: "B", text: "No doctors are plumbers" },
      { label: "C", text: "All people with medical degrees are doctors" },
      { label: "D", text: "Some doctors are plumbers" },
      { label: "E", text: "Plumbers do not exist" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Three boxes are labeled 'Apples', 'Oranges', and 'Mixed'. All labels are wrong. The box labeled 'Mixed' contains only apples. What does the box labeled 'Oranges' contain?",
    options: [
      { label: "A", text: "Oranges" },
      { label: "B", text: "Apples" },
      { label: "C", text: "Mixed" },
      { label: "D", text: "Empty" },
      { label: "E", text: "Cannot be determined" },
    ],
    correctLabel: "C",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If today is Wednesday, what day will it be 100 days from now?",
    options: [
      { label: "A", text: "Monday" },
      { label: "B", text: "Tuesday" },
      { label: "C", text: "Thursday" },
      { label: "D", text: "Friday" },
      { label: "E", text: "Saturday" },
    ],
    correctLabel: "D",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "In a group of 30 people, 18 like chocolate, 15 like vanilla, and 8 like both. How many like neither?",
    options: [
      { label: "A", text: "3" },
      { label: "B", text: "5" },
      { label: "C", text: "7" },
      { label: "D", text: "8" },
      { label: "E", text: "10" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Four people — Ana, Ben, Cleo, and Dan — each have a different profession: doctor, lawyer, teacher, engineer. Ana is not the doctor or lawyer. Ben is not the teacher. Cleo is the doctor. What is Dan's profession?",
    options: [
      { label: "A", text: "Doctor" },
      { label: "B", text: "Lawyer" },
      { label: "C", text: "Teacher" },
      { label: "D", text: "Engineer" },
      { label: "E", text: "Cannot be determined" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A lie-detector scenario: One of three suspects always tells the truth, one always lies, and one alternates. Suspect A says 'I am not the liar.' Suspect B says 'A is the liar.' Suspect C says 'B is not the truth-teller.' If B is the alternator, who is the truth-teller?",
    options: [
      { label: "A", text: "A" },
      { label: "B", text: "B" },
      { label: "C", text: "C" },
      { label: "D", text: "Either A or C" },
      { label: "E", text: "Cannot be determined" },
    ],
    correctLabel: "A",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Some teachers are musicians. All musicians can read music. Therefore:",
    options: [
      { label: "A", text: "All teachers can read music" },
      { label: "B", text: "Some teachers can read music" },
      { label: "C", text: "No teachers can read music" },
      { label: "D", text: "All people who read music are teachers" },
      { label: "E", text: "Musicians are always teachers" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Six books are stacked from bottom to top: A, B, C, D, E, F. Book C is removed and placed on top. What is now the third book from the bottom?",
    options: [
      { label: "A", text: "B" },
      { label: "B", text: "D" },
      { label: "C", text: "E" },
      { label: "D", text: "A" },
      { label: "E", text: "F" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "In a tournament, 8 teams play single-elimination (no ties). How many total games must be played to determine a winner?",
    options: [
      { label: "A", text: "5" },
      { label: "B", text: "6" },
      { label: "C", text: "7" },
      { label: "D", text: "8" },
      { label: "E", text: "10" },
    ],
    correctLabel: "C",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If all apples are fruits, and all fruits grow on plants, then:",
    options: [
      { label: "A", text: "Some apples do not grow on plants" },
      { label: "B", text: "All apples grow on plants" },
      { label: "C", text: "Some plants are apples" },
      { label: "D", text: "All plants have apples" },
      { label: "E", text: "Fruits are the only things that grow on plants" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "There are 5 houses in a row, each painted a different color. The red house is to the left of the blue house. The green house is at one end. The yellow house is next to the green house. Which house cannot be in the middle?",
    options: [
      { label: "A", text: "Red" },
      { label: "B", text: "Blue" },
      { label: "C", text: "Green" },
      { label: "D", text: "Yellow" },
      { label: "E", text: "White" },
    ],
    correctLabel: "C",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A clock loses 3 minutes every hour. If it is set correctly at noon, what time will it show when the actual time is 4:00 PM?",
    options: [
      { label: "A", text: "3:45 PM" },
      { label: "B", text: "3:48 PM" },
      { label: "C", text: "3:50 PM" },
      { label: "D", text: "3:52 PM" },
      { label: "E", text: "3:54 PM" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A man says, 'If my sister's daughter is my niece, then my niece's mother's brother is my ___.'",
    options: [
      { label: "A", text: "Father" },
      { label: "B", text: "Brother" },
      { label: "C", text: "Self" },
      { label: "D", text: "Uncle" },
      { label: "E", text: "Brother-in-law" },
    ],
    correctLabel: "C",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "Amy is older than Beth. Beth is older than Carol. Carol is older than Diane. Who is the oldest?",
    options: [
      { label: "A", text: "Amy" },
      { label: "B", text: "Beth" },
      { label: "C", text: "Carol" },
      { label: "D", text: "Diane" },
      { label: "E", text: "Cannot be determined" },
    ],
    correctLabel: "A",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "In a row of people, Mike is 8th from the left and 12th from the right. How many people are in the row?",
    options: [
      { label: "A", text: "18" },
      { label: "B", text: "19" },
      { label: "C", text: "20" },
      { label: "D", text: "21" },
      { label: "E", text: "22" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "You have 12 identical-looking coins, one of which is counterfeit (lighter). Using a balance scale, what is the minimum number of weighings needed to guarantee finding the counterfeit coin?",
    options: [
      { label: "A", text: "2" },
      { label: "B", text: "3" },
      { label: "C", text: "4" },
      { label: "D", text: "5" },
      { label: "E", text: "6" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If no athletes are lazy, and some students are athletes, then:",
    options: [
      { label: "A", text: "All students are lazy" },
      { label: "B", text: "No students are lazy" },
      { label: "C", text: "Some students are not lazy" },
      { label: "D", text: "All athletes are students" },
      { label: "E", text: "Lazy people cannot be students" },
    ],
    correctLabel: "C",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Five people finished a race: Pat, Quinn, Rita, Sam, and Tina. Pat finished before Quinn but after Rita. Sam did not finish last. Tina finished immediately after Quinn. Who finished fourth?",
    options: [
      { label: "A", text: "Pat" },
      { label: "B", text: "Quinn" },
      { label: "C", text: "Rita" },
      { label: "D", text: "Sam" },
      { label: "E", text: "Tina" },
    ],
    correctLabel: "E",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If you need to be at work by 9:00 AM and the commute takes 45 minutes, what is the latest you should leave home?",
    options: [
      { label: "A", text: "8:00 AM" },
      { label: "B", text: "8:10 AM" },
      { label: "C", text: "8:15 AM" },
      { label: "D", text: "8:20 AM" },
      { label: "E", text: "8:30 AM" },
    ],
    correctLabel: "C",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A is the father of B. B is the sister of C. D is the mother of C. What is A's relationship to D?",
    options: [
      { label: "A", text: "Brother" },
      { label: "B", text: "Father" },
      { label: "C", text: "Husband" },
      { label: "D", text: "Son" },
      { label: "E", text: "Uncle" },
    ],
    correctLabel: "C",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "In a group of 100 people, 70 like pizza, 65 like burgers, and 50 like both. How many like exactly one of the two?",
    options: [
      { label: "A", text: "25" },
      { label: "B", text: "30" },
      { label: "C", text: "35" },
      { label: "D", text: "40" },
      { label: "E", text: "45" },
    ],
    correctLabel: "C",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "If Monday comes after Sunday, and Wednesday comes after Tuesday, what day comes after Thursday?",
    options: [
      { label: "A", text: "Wednesday" },
      { label: "B", text: "Friday" },
      { label: "C", text: "Saturday" },
      { label: "D", text: "Sunday" },
      { label: "E", text: "Tuesday" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Four cards are placed on a table showing A, B, 3, and 4. The rule is: 'If a card has a vowel on one side, it has an even number on the other.' Which cards must you flip to test this rule?",
    options: [
      { label: "A", text: "A only" },
      { label: "B", text: "A and 4" },
      { label: "C", text: "A and 3" },
      { label: "D", text: "A, B, and 3" },
      { label: "E", text: "All four cards" },
    ],
    correctLabel: "C",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "How many handshakes occur if each person in a group of 10 shakes hands with every other person exactly once?",
    options: [
      { label: "A", text: "35" },
      { label: "B", text: "40" },
      { label: "C", text: "45" },
      { label: "D", text: "50" },
      { label: "E", text: "55" },
    ],
    correctLabel: "C",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "If every member of Team A is also on Team B, but not every member of Team B is on Team A, which statement must be true?",
    options: [
      { label: "A", text: "Team A has more members than Team B" },
      { label: "B", text: "Team B has more members than Team A" },
      { label: "C", text: "The teams have the same number of members" },
      { label: "D", text: "Team A and Team B have no members in common" },
      { label: "E", text: "Team B is a subset of Team A" },
    ],
    correctLabel: "B",
    tags: ["logical-deduction"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "There are 3 red balls and 2 blue balls in a bag. If you pick one ball without looking, which color are you more likely to pick?",
    options: [
      { label: "A", text: "Red" },
      { label: "B", text: "Blue" },
      { label: "C", text: "Equal chance" },
      { label: "D", text: "Cannot be determined" },
      { label: "E", text: "Neither — you cannot pick from a bag" },
    ],
    correctLabel: "A",
    tags: ["logical-deduction"],
  },
];
