type QuestionData = {
  category: "verbal" | "math_logic" | "spatial";
  difficulty: number;
  stem: string;
  options: { label: string; text: string }[];
  correctLabel: string;
  tags: string[];
};

export const verbalQuestions: QuestionData[] = [
  // ─── ANTONYMS (45 questions) ───────────────────────────────────────────────

  // Antonyms — Easy (difficulty 1)
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to HAPPY.",
    options: [
      { label: "A", text: "Joyful" },
      { label: "B", text: "Sad" },
      { label: "C", text: "Excited" },
      { label: "D", text: "Calm" },
      { label: "E", text: "Cheerful" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to BRAVE.",
    options: [
      { label: "A", text: "Bold" },
      { label: "B", text: "Strong" },
      { label: "C", text: "Cowardly" },
      { label: "D", text: "Fierce" },
      { label: "E", text: "Daring" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to SIMPLE.",
    options: [
      { label: "A", text: "Easy" },
      { label: "B", text: "Plain" },
      { label: "C", text: "Clear" },
      { label: "D", text: "Complex" },
      { label: "E", text: "Basic" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to COLD.",
    options: [
      { label: "A", text: "Frozen" },
      { label: "B", text: "Chilly" },
      { label: "C", text: "Hot" },
      { label: "D", text: "Cool" },
      { label: "E", text: "Icy" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to ANCIENT.",
    options: [
      { label: "A", text: "Old" },
      { label: "B", text: "Historic" },
      { label: "C", text: "Aged" },
      { label: "D", text: "Modern" },
      { label: "E", text: "Classic" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to GENEROUS.",
    options: [
      { label: "A", text: "Kind" },
      { label: "B", text: "Giving" },
      { label: "C", text: "Stingy" },
      { label: "D", text: "Wealthy" },
      { label: "E", text: "Caring" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to LOUD.",
    options: [
      { label: "A", text: "Noisy" },
      { label: "B", text: "Booming" },
      { label: "C", text: "Shrill" },
      { label: "D", text: "Quiet" },
      { label: "E", text: "Blaring" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to TALL.",
    options: [
      { label: "A", text: "High" },
      { label: "B", text: "Short" },
      { label: "C", text: "Large" },
      { label: "D", text: "Towering" },
      { label: "E", text: "Elevated" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to LIGHT.",
    options: [
      { label: "A", text: "Bright" },
      { label: "B", text: "Pale" },
      { label: "C", text: "Heavy" },
      { label: "D", text: "Thin" },
      { label: "E", text: "Airy" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to FRIEND.",
    options: [
      { label: "A", text: "Companion" },
      { label: "B", text: "Ally" },
      { label: "C", text: "Partner" },
      { label: "D", text: "Neighbor" },
      { label: "E", text: "Enemy" },
    ],
    correctLabel: "E",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to EMPTY.",
    options: [
      { label: "A", text: "Vacant" },
      { label: "B", text: "Full" },
      { label: "C", text: "Hollow" },
      { label: "D", text: "Bare" },
      { label: "E", text: "Blank" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to DARK.",
    options: [
      { label: "A", text: "Dim" },
      { label: "B", text: "Shadowy" },
      { label: "C", text: "Murky" },
      { label: "D", text: "Bright" },
      { label: "E", text: "Gloomy" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },

  // Antonyms — Medium (difficulty 2)
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to EPHEMERAL.",
    options: [
      { label: "A", text: "Transient" },
      { label: "B", text: "Permanent" },
      { label: "C", text: "Brief" },
      { label: "D", text: "Fleeting" },
      { label: "E", text: "Temporary" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to LETHARGIC.",
    options: [
      { label: "A", text: "Sluggish" },
      { label: "B", text: "Drowsy" },
      { label: "C", text: "Energetic" },
      { label: "D", text: "Idle" },
      { label: "E", text: "Listless" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to BENEVOLENT.",
    options: [
      { label: "A", text: "Charitable" },
      { label: "B", text: "Malevolent" },
      { label: "C", text: "Generous" },
      { label: "D", text: "Humane" },
      { label: "E", text: "Compassionate" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to VERBOSE.",
    options: [
      { label: "A", text: "Wordy" },
      { label: "B", text: "Lengthy" },
      { label: "C", text: "Concise" },
      { label: "D", text: "Rambling" },
      { label: "E", text: "Elaborate" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to ARDUOUS.",
    options: [
      { label: "A", text: "Difficult" },
      { label: "B", text: "Demanding" },
      { label: "C", text: "Strenuous" },
      { label: "D", text: "Effortless" },
      { label: "E", text: "Grueling" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to CANDID.",
    options: [
      { label: "A", text: "Honest" },
      { label: "B", text: "Deceptive" },
      { label: "C", text: "Frank" },
      { label: "D", text: "Blunt" },
      { label: "E", text: "Forthright" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to TRANQUIL.",
    options: [
      { label: "A", text: "Serene" },
      { label: "B", text: "Peaceful" },
      { label: "C", text: "Placid" },
      { label: "D", text: "Turbulent" },
      { label: "E", text: "Still" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to PROLIFIC.",
    options: [
      { label: "A", text: "Productive" },
      { label: "B", text: "Fertile" },
      { label: "C", text: "Barren" },
      { label: "D", text: "Abundant" },
      { label: "E", text: "Fruitful" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to METICULOUS.",
    options: [
      { label: "A", text: "Precise" },
      { label: "B", text: "Thorough" },
      { label: "C", text: "Careful" },
      { label: "D", text: "Detailed" },
      { label: "E", text: "Careless" },
    ],
    correctLabel: "E",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to AUSTERE.",
    options: [
      { label: "A", text: "Lavish" },
      { label: "B", text: "Strict" },
      { label: "C", text: "Spartan" },
      { label: "D", text: "Severe" },
      { label: "E", text: "Harsh" },
    ],
    correctLabel: "A",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to ELATED.",
    options: [
      { label: "A", text: "Thrilled" },
      { label: "B", text: "Jubilant" },
      { label: "C", text: "Despondent" },
      { label: "D", text: "Ecstatic" },
      { label: "E", text: "Overjoyed" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to PRAGMATIC.",
    options: [
      { label: "A", text: "Practical" },
      { label: "B", text: "Realistic" },
      { label: "C", text: "Sensible" },
      { label: "D", text: "Idealistic" },
      { label: "E", text: "Rational" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to DIMINISH.",
    options: [
      { label: "A", text: "Reduce" },
      { label: "B", text: "Decrease" },
      { label: "C", text: "Amplify" },
      { label: "D", text: "Shrink" },
      { label: "E", text: "Lessen" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to AFFLUENT.",
    options: [
      { label: "A", text: "Wealthy" },
      { label: "B", text: "Prosperous" },
      { label: "C", text: "Rich" },
      { label: "D", text: "Destitute" },
      { label: "E", text: "Opulent" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },

  // Antonyms — Hard (difficulty 3)
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to PERSPICACIOUS.",
    options: [
      { label: "A", text: "Astute" },
      { label: "B", text: "Obtuse" },
      { label: "C", text: "Shrewd" },
      { label: "D", text: "Perceptive" },
      { label: "E", text: "Discerning" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to OBSEQUIOUS.",
    options: [
      { label: "A", text: "Servile" },
      { label: "B", text: "Fawning" },
      { label: "C", text: "Domineering" },
      { label: "D", text: "Sycophantic" },
      { label: "E", text: "Submissive" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to PARSIMONIOUS.",
    options: [
      { label: "A", text: "Miserly" },
      { label: "B", text: "Frugal" },
      { label: "C", text: "Thrifty" },
      { label: "D", text: "Profligate" },
      { label: "E", text: "Stingy" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to GARRULOUS.",
    options: [
      { label: "A", text: "Talkative" },
      { label: "B", text: "Loquacious" },
      { label: "C", text: "Chatty" },
      { label: "D", text: "Verbose" },
      { label: "E", text: "Taciturn" },
    ],
    correctLabel: "E",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to PELLUCID.",
    options: [
      { label: "A", text: "Transparent" },
      { label: "B", text: "Opaque" },
      { label: "C", text: "Clear" },
      { label: "D", text: "Lucid" },
      { label: "E", text: "Crystalline" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to TRUCULENT.",
    options: [
      { label: "A", text: "Aggressive" },
      { label: "B", text: "Belligerent" },
      { label: "C", text: "Hostile" },
      { label: "D", text: "Amenable" },
      { label: "E", text: "Pugnacious" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to RECONDITE.",
    options: [
      { label: "A", text: "Abstruse" },
      { label: "B", text: "Arcane" },
      { label: "C", text: "Accessible" },
      { label: "D", text: "Esoteric" },
      { label: "E", text: "Obscure" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to LACONIC.",
    options: [
      { label: "A", text: "Terse" },
      { label: "B", text: "Pithy" },
      { label: "C", text: "Curt" },
      { label: "D", text: "Succinct" },
      { label: "E", text: "Prolix" },
    ],
    correctLabel: "E",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to QUIESCENT.",
    options: [
      { label: "A", text: "Dormant" },
      { label: "B", text: "Turbulent" },
      { label: "C", text: "Inactive" },
      { label: "D", text: "Latent" },
      { label: "E", text: "Still" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to MENDACIOUS.",
    options: [
      { label: "A", text: "Deceitful" },
      { label: "B", text: "Dishonest" },
      { label: "C", text: "Veracious" },
      { label: "D", text: "Fraudulent" },
      { label: "E", text: "Duplicitous" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },

  // ─── ANALOGIES (45 questions) ──────────────────────────────────────────────

  // Analogies — Easy (difficulty 1)
  {
    category: "verbal",
    difficulty: 1,
    stem: "HAMMER is to CARPENTER as BRUSH is to:",
    options: [
      { label: "A", text: "Canvas" },
      { label: "B", text: "Painter" },
      { label: "C", text: "Color" },
      { label: "D", text: "Gallery" },
      { label: "E", text: "Easel" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "PUPPY is to DOG as KITTEN is to:",
    options: [
      { label: "A", text: "Cat" },
      { label: "B", text: "Pet" },
      { label: "C", text: "Mouse" },
      { label: "D", text: "Fur" },
      { label: "E", text: "Paw" },
    ],
    correctLabel: "A",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "BOOK is to LIBRARY as PAINTING is to:",
    options: [
      { label: "A", text: "Artist" },
      { label: "B", text: "Canvas" },
      { label: "C", text: "Museum" },
      { label: "D", text: "Frame" },
      { label: "E", text: "Color" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "FISH is to WATER as BIRD is to:",
    options: [
      { label: "A", text: "Nest" },
      { label: "B", text: "Wing" },
      { label: "C", text: "Sky" },
      { label: "D", text: "Feather" },
      { label: "E", text: "Tree" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "HAND is to GLOVE as FOOT is to:",
    options: [
      { label: "A", text: "Leg" },
      { label: "B", text: "Shoe" },
      { label: "C", text: "Toe" },
      { label: "D", text: "Walk" },
      { label: "E", text: "Ankle" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "EAR is to HEAR as EYE is to:",
    options: [
      { label: "A", text: "Blink" },
      { label: "B", text: "Face" },
      { label: "C", text: "See" },
      { label: "D", text: "Glasses" },
      { label: "E", text: "Color" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "AUTHOR is to BOOK as COMPOSER is to:",
    options: [
      { label: "A", text: "Piano" },
      { label: "B", text: "Symphony" },
      { label: "C", text: "Singer" },
      { label: "D", text: "Concert" },
      { label: "E", text: "Stage" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "PETAL is to FLOWER as LEAF is to:",
    options: [
      { label: "A", text: "Green" },
      { label: "B", text: "Garden" },
      { label: "C", text: "Tree" },
      { label: "D", text: "Root" },
      { label: "E", text: "Soil" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "KEY is to LOCK as PASSWORD is to:",
    options: [
      { label: "A", text: "Computer" },
      { label: "B", text: "Account" },
      { label: "C", text: "Hacker" },
      { label: "D", text: "Keyboard" },
      { label: "E", text: "Screen" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "NEEDLE is to THREAD as PEN is to:",
    options: [
      { label: "A", text: "Paper" },
      { label: "B", text: "Ink" },
      { label: "C", text: "Writer" },
      { label: "D", text: "Desk" },
      { label: "E", text: "Cap" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "TEACHER is to CLASSROOM as DOCTOR is to:",
    options: [
      { label: "A", text: "Medicine" },
      { label: "B", text: "Patient" },
      { label: "C", text: "Hospital" },
      { label: "D", text: "Nurse" },
      { label: "E", text: "Stethoscope" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },

  // Analogies — Medium (difficulty 2)
  {
    category: "verbal",
    difficulty: 2,
    stem: "SURGEON is to SCALPEL as SCULPTOR is to:",
    options: [
      { label: "A", text: "Museum" },
      { label: "B", text: "Marble" },
      { label: "C", text: "Chisel" },
      { label: "D", text: "Studio" },
      { label: "E", text: "Statue" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "DROUGHT is to FAMINE as SPARK is to:",
    options: [
      { label: "A", text: "Water" },
      { label: "B", text: "Inferno" },
      { label: "C", text: "Match" },
      { label: "D", text: "Light" },
      { label: "E", text: "Smoke" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "CONSTELLATION is to STAR as ARCHIPELAGO is to:",
    options: [
      { label: "A", text: "Ocean" },
      { label: "B", text: "Continent" },
      { label: "C", text: "Island" },
      { label: "D", text: "Beach" },
      { label: "E", text: "Harbor" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "PROLOGUE is to PLAY as PREFACE is to:",
    options: [
      { label: "A", text: "Author" },
      { label: "B", text: "Chapter" },
      { label: "C", text: "Index" },
      { label: "D", text: "Book" },
      { label: "E", text: "Page" },
    ],
    correctLabel: "D",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "COUPLET is to POEM as VERSE is to:",
    options: [
      { label: "A", text: "Hymn" },
      { label: "B", text: "Choir" },
      { label: "C", text: "Singer" },
      { label: "D", text: "Music" },
      { label: "E", text: "Melody" },
    ],
    correctLabel: "A",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "IMMUNE is to DISEASE as FIREPROOF is to:",
    options: [
      { label: "A", text: "Smoke" },
      { label: "B", text: "Heat" },
      { label: "C", text: "Combustion" },
      { label: "D", text: "Water" },
      { label: "E", text: "Ash" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "AMPLIFY is to SOUND as MAGNIFY is to:",
    options: [
      { label: "A", text: "Lens" },
      { label: "B", text: "Image" },
      { label: "C", text: "Light" },
      { label: "D", text: "Microscope" },
      { label: "E", text: "Focus" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "HYPOTHESIS is to THEORY as SKETCH is to:",
    options: [
      { label: "A", text: "Pencil" },
      { label: "B", text: "Eraser" },
      { label: "C", text: "Blueprint" },
      { label: "D", text: "Artist" },
      { label: "E", text: "Paper" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "ANARCHY is to ORDER as CACOPHONY is to:",
    options: [
      { label: "A", text: "Noise" },
      { label: "B", text: "Sound" },
      { label: "C", text: "Volume" },
      { label: "D", text: "Harmony" },
      { label: "E", text: "Music" },
    ],
    correctLabel: "D",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "JUDGE is to COURTROOM as REFEREE is to:",
    options: [
      { label: "A", text: "Whistle" },
      { label: "B", text: "Arena" },
      { label: "C", text: "Team" },
      { label: "D", text: "Penalty" },
      { label: "E", text: "Score" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "ANTIDOTE is to POISON as CURE is to:",
    options: [
      { label: "A", text: "Doctor" },
      { label: "B", text: "Hospital" },
      { label: "C", text: "Medicine" },
      { label: "D", text: "Disease" },
      { label: "E", text: "Health" },
    ],
    correctLabel: "D",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "DEFORESTATION is to EROSION as OVEREATING is to:",
    options: [
      { label: "A", text: "Hunger" },
      { label: "B", text: "Obesity" },
      { label: "C", text: "Food" },
      { label: "D", text: "Appetite" },
      { label: "E", text: "Diet" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "THERMOMETER is to TEMPERATURE as BAROMETER is to:",
    options: [
      { label: "A", text: "Wind" },
      { label: "B", text: "Humidity" },
      { label: "C", text: "Pressure" },
      { label: "D", text: "Rain" },
      { label: "E", text: "Climate" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "EVAPORATION is to GAS as FREEZING is to:",
    options: [
      { label: "A", text: "Water" },
      { label: "B", text: "Solid" },
      { label: "C", text: "Ice" },
      { label: "D", text: "Cold" },
      { label: "E", text: "Liquid" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "TELESCOPE is to ASTRONOMER as STETHOSCOPE is to:",
    options: [
      { label: "A", text: "Heart" },
      { label: "B", text: "Nurse" },
      { label: "C", text: "Physician" },
      { label: "D", text: "Pulse" },
      { label: "E", text: "Diagnosis" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },

  // Analogies — Hard (difficulty 3)
  {
    category: "verbal",
    difficulty: 3,
    stem: "SYCOPHANT is to FLATTERY as DEMAGOGUE is to:",
    options: [
      { label: "A", text: "Democracy" },
      { label: "B", text: "Rhetoric" },
      { label: "C", text: "Violence" },
      { label: "D", text: "Legislation" },
      { label: "E", text: "Diplomacy" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "ICONOCLAST is to TRADITION as HERETIC is to:",
    options: [
      { label: "A", text: "Religion" },
      { label: "B", text: "Orthodoxy" },
      { label: "C", text: "Church" },
      { label: "D", text: "Faith" },
      { label: "E", text: "Worship" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "LABYRINTHINE is to NAVIGATE as ABSTRUSE is to:",
    options: [
      { label: "A", text: "Ignore" },
      { label: "B", text: "Explain" },
      { label: "C", text: "Comprehend" },
      { label: "D", text: "Observe" },
      { label: "E", text: "Memorize" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "SOPORIFIC is to SLEEP as EMETIC is to:",
    options: [
      { label: "A", text: "Vomiting" },
      { label: "B", text: "Digestion" },
      { label: "C", text: "Appetite" },
      { label: "D", text: "Illness" },
      { label: "E", text: "Nausea" },
    ],
    correctLabel: "A",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "CHICANERY is to HONESTY as PROFLIGACY is to:",
    options: [
      { label: "A", text: "Wealth" },
      { label: "B", text: "Poverty" },
      { label: "C", text: "Frugality" },
      { label: "D", text: "Generosity" },
      { label: "E", text: "Spending" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "PHILATELIST is to STAMPS as NUMISMATIST is to:",
    options: [
      { label: "A", text: "Numbers" },
      { label: "B", text: "Coins" },
      { label: "C", text: "Artifacts" },
      { label: "D", text: "Medals" },
      { label: "E", text: "Antiques" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "MARTINET is to DISCIPLINE as EPICURE is to:",
    options: [
      { label: "A", text: "Philosophy" },
      { label: "B", text: "Cooking" },
      { label: "C", text: "Fine dining" },
      { label: "D", text: "Temperance" },
      { label: "E", text: "Asceticism" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "PANACEA is to AILMENT as OMNISCIENCE is to:",
    options: [
      { label: "A", text: "Wisdom" },
      { label: "B", text: "Ignorance" },
      { label: "C", text: "Knowledge" },
      { label: "D", text: "Education" },
      { label: "E", text: "Intelligence" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },

  // ─── SENTENCE COMPLETION (50 questions) ────────────────────────────────────

  // Sentence Completion — Easy (difficulty 1)
  {
    category: "verbal",
    difficulty: 1,
    stem: "The children were so ___ after playing outside all day that they fell asleep immediately.",
    options: [
      { label: "A", text: "Energetic" },
      { label: "B", text: "Tired" },
      { label: "C", text: "Hungry" },
      { label: "D", text: "Excited" },
      { label: "E", text: "Restless" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Because the road was covered in ice, the driver proceeded with extreme ___.",
    options: [
      { label: "A", text: "Speed" },
      { label: "B", text: "Confidence" },
      { label: "C", text: "Caution" },
      { label: "D", text: "Excitement" },
      { label: "E", text: "Anger" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "The sunset was so ___ that everyone stopped to take photographs.",
    options: [
      { label: "A", text: "Dull" },
      { label: "B", text: "Ordinary" },
      { label: "C", text: "Beautiful" },
      { label: "D", text: "Brief" },
      { label: "E", text: "Common" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "After the long drought, the farmers were ___ when the rain finally arrived.",
    options: [
      { label: "A", text: "Disappointed" },
      { label: "B", text: "Relieved" },
      { label: "C", text: "Angry" },
      { label: "D", text: "Confused" },
      { label: "E", text: "Indifferent" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "The instructions were so ___ that even a child could follow them.",
    options: [
      { label: "A", text: "Complicated" },
      { label: "B", text: "Vague" },
      { label: "C", text: "Clear" },
      { label: "D", text: "Lengthy" },
      { label: "E", text: "Technical" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "The old bridge was declared ___ and closed to all traffic.",
    options: [
      { label: "A", text: "Sturdy" },
      { label: "B", text: "Unsafe" },
      { label: "C", text: "Historic" },
      { label: "D", text: "Beautiful" },
      { label: "E", text: "Expensive" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "She spoke so ___ that no one in the back row could hear her presentation.",
    options: [
      { label: "A", text: "Loudly" },
      { label: "B", text: "Quickly" },
      { label: "C", text: "Clearly" },
      { label: "D", text: "Softly" },
      { label: "E", text: "Confidently" },
    ],
    correctLabel: "D",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "The detective searched for ___ that would help solve the mystery.",
    options: [
      { label: "A", text: "Trouble" },
      { label: "B", text: "Clues" },
      { label: "C", text: "Weapons" },
      { label: "D", text: "Suspects" },
      { label: "E", text: "Rewards" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "The new employee was eager to ___ a good impression on her first day.",
    options: [
      { label: "A", text: "Avoid" },
      { label: "B", text: "Make" },
      { label: "C", text: "Lose" },
      { label: "D", text: "Forget" },
      { label: "E", text: "Skip" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "The storm caused widespread ___ throughout the coastal region.",
    options: [
      { label: "A", text: "Calm" },
      { label: "B", text: "Joy" },
      { label: "C", text: "Damage" },
      { label: "D", text: "Growth" },
      { label: "E", text: "Silence" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },

  // Sentence Completion — Medium (difficulty 2)
  {
    category: "verbal",
    difficulty: 2,
    stem: "The politician's speech was deliberately ___, designed to appeal to voters without committing to any specific policy.",
    options: [
      { label: "A", text: "Forthright" },
      { label: "B", text: "Ambiguous" },
      { label: "C", text: "Inspiring" },
      { label: "D", text: "Provocative" },
      { label: "E", text: "Detailed" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Although the critic praised the novel's plot, she found the characters to be ___ and one-dimensional.",
    options: [
      { label: "A", text: "Compelling" },
      { label: "B", text: "Memorable" },
      { label: "C", text: "Superficial" },
      { label: "D", text: "Complex" },
      { label: "E", text: "Vivid" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The scientist's findings were initially met with ___, but subsequent experiments confirmed her results.",
    options: [
      { label: "A", text: "Enthusiasm" },
      { label: "B", text: "Skepticism" },
      { label: "C", text: "Applause" },
      { label: "D", text: "Funding" },
      { label: "E", text: "Agreement" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The company's attempt to ___ its environmental record was undermined by leaked internal documents.",
    options: [
      { label: "A", text: "Ignore" },
      { label: "B", text: "Document" },
      { label: "C", text: "Embellish" },
      { label: "D", text: "Investigate" },
      { label: "E", text: "Publish" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Her ___ nature made her the ideal candidate for diplomatic negotiations, as she could remain calm under pressure.",
    options: [
      { label: "A", text: "Volatile" },
      { label: "B", text: "Impatient" },
      { label: "C", text: "Temperamental" },
      { label: "D", text: "Composed" },
      { label: "E", text: "Aggressive" },
    ],
    correctLabel: "D",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The ancient manuscript was so ___ that only a handful of scholars worldwide could decipher its contents.",
    options: [
      { label: "A", text: "Common" },
      { label: "B", text: "Cryptic" },
      { label: "C", text: "Popular" },
      { label: "D", text: "Accessible" },
      { label: "E", text: "Legible" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Rather than ___ the problem, the manager chose to address it directly during the team meeting.",
    options: [
      { label: "A", text: "Solve" },
      { label: "B", text: "Confront" },
      { label: "C", text: "Circumvent" },
      { label: "D", text: "Discuss" },
      { label: "E", text: "Analyze" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The documentary provided a ___ account of the historical events, presenting multiple perspectives without taking sides.",
    options: [
      { label: "A", text: "Biased" },
      { label: "B", text: "Partial" },
      { label: "C", text: "Balanced" },
      { label: "D", text: "Sensational" },
      { label: "E", text: "Distorted" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The professor's lectures were so ___ that students often struggled to stay awake.",
    options: [
      { label: "A", text: "Riveting" },
      { label: "B", text: "Monotonous" },
      { label: "C", text: "Engaging" },
      { label: "D", text: "Dynamic" },
      { label: "E", text: "Stimulating" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The witness gave a ___ testimony, providing exact times, dates, and descriptions with remarkable precision.",
    options: [
      { label: "A", text: "Vague" },
      { label: "B", text: "Contradictory" },
      { label: "C", text: "Meticulous" },
      { label: "D", text: "Rambling" },
      { label: "E", text: "Evasive" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The CEO's ___ decision to expand into new markets proved to be visionary when profits tripled the following year.",
    options: [
      { label: "A", text: "Reckless" },
      { label: "B", text: "Audacious" },
      { label: "C", text: "Timid" },
      { label: "D", text: "Conservative" },
      { label: "E", text: "Reluctant" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The negotiator was known for his ability to find ___ solutions that satisfied all parties involved.",
    options: [
      { label: "A", text: "Divisive" },
      { label: "B", text: "Contentious" },
      { label: "C", text: "Equitable" },
      { label: "D", text: "Partisan" },
      { label: "E", text: "Hostile" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The architect's innovative design was praised for its ___ blend of modern aesthetics and traditional elements.",
    options: [
      { label: "A", text: "Discordant" },
      { label: "B", text: "Clashing" },
      { label: "C", text: "Jarring" },
      { label: "D", text: "Harmonious" },
      { label: "E", text: "Chaotic" },
    ],
    correctLabel: "D",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Despite the team's initial ___, they eventually embraced the new workflow after seeing improved results.",
    options: [
      { label: "A", text: "Enthusiasm" },
      { label: "B", text: "Resistance" },
      { label: "C", text: "Eagerness" },
      { label: "D", text: "Support" },
      { label: "E", text: "Approval" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The report was criticized for its ___ conclusions, which were drawn from an insufficient sample size.",
    options: [
      { label: "A", text: "Robust" },
      { label: "B", text: "Rigorous" },
      { label: "C", text: "Premature" },
      { label: "D", text: "Thorough" },
      { label: "E", text: "Sound" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },

  // Sentence Completion — Hard (difficulty 3)
  {
    category: "verbal",
    difficulty: 3,
    stem: "The author's prose was marked by a ___ quality, with sentences that meandered through subordinate clauses before arriving at their point.",
    options: [
      { label: "A", text: "Laconic" },
      { label: "B", text: "Terse" },
      { label: "C", text: "Discursive" },
      { label: "D", text: "Pithy" },
      { label: "E", text: "Succinct" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "The dictator maintained power through a combination of ___ propaganda and ruthless suppression of dissent.",
    options: [
      { label: "A", text: "Transparent" },
      { label: "B", text: "Insidious" },
      { label: "C", text: "Forthright" },
      { label: "D", text: "Candid" },
      { label: "E", text: "Benign" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "The philosopher's argument, though internally ___, failed to account for several well-documented counterexamples.",
    options: [
      { label: "A", text: "Contradictory" },
      { label: "B", text: "Incoherent" },
      { label: "C", text: "Fallacious" },
      { label: "D", text: "Coherent" },
      { label: "E", text: "Specious" },
    ],
    correctLabel: "D",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Her ___ remarks at the dinner party offended several guests who found her bluntness inappropriate for the occasion.",
    options: [
      { label: "A", text: "Diplomatic" },
      { label: "B", text: "Tactful" },
      { label: "C", text: "Trenchant" },
      { label: "D", text: "Gracious" },
      { label: "E", text: "Courteous" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "The researcher's ___ approach to data collection, involving years of painstaking fieldwork, ultimately yielded groundbreaking results.",
    options: [
      { label: "A", text: "Haphazard" },
      { label: "B", text: "Cursory" },
      { label: "C", text: "Negligent" },
      { label: "D", text: "Assiduous" },
      { label: "E", text: "Perfunctory" },
    ],
    correctLabel: "D",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "The artist's later works revealed a ___ shift from exuberant optimism to somber introspection.",
    options: [
      { label: "A", text: "Subtle" },
      { label: "B", text: "Imperceptible" },
      { label: "C", text: "Palpable" },
      { label: "D", text: "Negligible" },
      { label: "E", text: "Trivial" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "The diplomat was lauded for her ___ handling of the crisis, deftly avoiding escalation while protecting her nation's interests.",
    options: [
      { label: "A", text: "Inept" },
      { label: "B", text: "Maladroit" },
      { label: "C", text: "Adroit" },
      { label: "D", text: "Clumsy" },
      { label: "E", text: "Fumbling" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "The once-___ neighborhood has undergone a dramatic transformation, now boasting upscale restaurants and boutique shops.",
    options: [
      { label: "A", text: "Affluent" },
      { label: "B", text: "Prosperous" },
      { label: "C", text: "Dilapidated" },
      { label: "D", text: "Opulent" },
      { label: "E", text: "Thriving" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The journalist's ___ investigation uncovered a network of corruption that had gone undetected for decades.",
    options: [
      { label: "A", text: "Superficial" },
      { label: "B", text: "Cursory" },
      { label: "C", text: "Exhaustive" },
      { label: "D", text: "Brief" },
      { label: "E", text: "Casual" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The medication's side effects were ___, ranging from mild headaches to severe allergic reactions.",
    options: [
      { label: "A", text: "Uniform" },
      { label: "B", text: "Predictable" },
      { label: "C", text: "Consistent" },
      { label: "D", text: "Variable" },
      { label: "E", text: "Identical" },
    ],
    correctLabel: "D",
    tags: ["sentence-completion"],
  },

  // ─── VOCABULARY (45 questions) ─────────────────────────────────────────────

  // Vocabulary — Easy (difficulty 1)
  {
    category: "verbal",
    difficulty: 1,
    stem: "FREQUENT most nearly means:",
    options: [
      { label: "A", text: "Rare" },
      { label: "B", text: "Often" },
      { label: "C", text: "Never" },
      { label: "D", text: "Slow" },
      { label: "E", text: "Distant" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "SCARCE most nearly means:",
    options: [
      { label: "A", text: "Abundant" },
      { label: "B", text: "Cheap" },
      { label: "C", text: "Limited" },
      { label: "D", text: "Large" },
      { label: "E", text: "Heavy" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "RIGID most nearly means:",
    options: [
      { label: "A", text: "Flexible" },
      { label: "B", text: "Soft" },
      { label: "C", text: "Stiff" },
      { label: "D", text: "Warm" },
      { label: "E", text: "Smooth" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "CONCEAL most nearly means:",
    options: [
      { label: "A", text: "Reveal" },
      { label: "B", text: "Hide" },
      { label: "C", text: "Search" },
      { label: "D", text: "Collect" },
      { label: "E", text: "Create" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "DECLINE most nearly means:",
    options: [
      { label: "A", text: "Accept" },
      { label: "B", text: "Increase" },
      { label: "C", text: "Refuse" },
      { label: "D", text: "Celebrate" },
      { label: "E", text: "Discuss" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "TIMID most nearly means:",
    options: [
      { label: "A", text: "Bold" },
      { label: "B", text: "Shy" },
      { label: "C", text: "Loud" },
      { label: "D", text: "Strong" },
      { label: "E", text: "Quick" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "OBTAIN most nearly means:",
    options: [
      { label: "A", text: "Lose" },
      { label: "B", text: "Give" },
      { label: "C", text: "Get" },
      { label: "D", text: "Break" },
      { label: "E", text: "Throw" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "FRAGILE most nearly means:",
    options: [
      { label: "A", text: "Strong" },
      { label: "B", text: "Delicate" },
      { label: "C", text: "Heavy" },
      { label: "D", text: "Large" },
      { label: "E", text: "Round" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "VAST most nearly means:",
    options: [
      { label: "A", text: "Tiny" },
      { label: "B", text: "Narrow" },
      { label: "C", text: "Enormous" },
      { label: "D", text: "Fast" },
      { label: "E", text: "Flat" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "OBVIOUS most nearly means:",
    options: [
      { label: "A", text: "Hidden" },
      { label: "B", text: "Apparent" },
      { label: "C", text: "Strange" },
      { label: "D", text: "Difficult" },
      { label: "E", text: "Quiet" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "HAZARD most nearly means:",
    options: [
      { label: "A", text: "Safety" },
      { label: "B", text: "Luck" },
      { label: "C", text: "Danger" },
      { label: "D", text: "Speed" },
      { label: "E", text: "Distance" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },

  // Vocabulary — Medium (difficulty 2)
  {
    category: "verbal",
    difficulty: 2,
    stem: "UBIQUITOUS most nearly means:",
    options: [
      { label: "A", text: "Rare" },
      { label: "B", text: "Dangerous" },
      { label: "C", text: "Everywhere" },
      { label: "D", text: "Unusual" },
      { label: "E", text: "Ancient" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "TENACIOUS most nearly means:",
    options: [
      { label: "A", text: "Weak" },
      { label: "B", text: "Persistent" },
      { label: "C", text: "Gentle" },
      { label: "D", text: "Nervous" },
      { label: "E", text: "Wealthy" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "ELOQUENT most nearly means:",
    options: [
      { label: "A", text: "Silent" },
      { label: "B", text: "Confused" },
      { label: "C", text: "Articulate" },
      { label: "D", text: "Loud" },
      { label: "E", text: "Rude" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "MITIGATE most nearly means:",
    options: [
      { label: "A", text: "Worsen" },
      { label: "B", text: "Lessen" },
      { label: "C", text: "Ignore" },
      { label: "D", text: "Cause" },
      { label: "E", text: "Prevent" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "COGENT most nearly means:",
    options: [
      { label: "A", text: "Weak" },
      { label: "B", text: "Complicated" },
      { label: "C", text: "Convincing" },
      { label: "D", text: "Lengthy" },
      { label: "E", text: "Boring" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "ACQUIESCE most nearly means:",
    options: [
      { label: "A", text: "Resist" },
      { label: "B", text: "Comply" },
      { label: "C", text: "Demand" },
      { label: "D", text: "Question" },
      { label: "E", text: "Argue" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "ASTUTE most nearly means:",
    options: [
      { label: "A", text: "Foolish" },
      { label: "B", text: "Lazy" },
      { label: "C", text: "Shrewd" },
      { label: "D", text: "Timid" },
      { label: "E", text: "Generous" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "VOLATILE most nearly means:",
    options: [
      { label: "A", text: "Stable" },
      { label: "B", text: "Unpredictable" },
      { label: "C", text: "Quiet" },
      { label: "D", text: "Heavy" },
      { label: "E", text: "Slow" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "DISPARATE most nearly means:",
    options: [
      { label: "A", text: "Similar" },
      { label: "B", text: "Equal" },
      { label: "C", text: "Different" },
      { label: "D", text: "Parallel" },
      { label: "E", text: "Adjacent" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "PRECLUDE most nearly means:",
    options: [
      { label: "A", text: "Allow" },
      { label: "B", text: "Prevent" },
      { label: "C", text: "Encourage" },
      { label: "D", text: "Include" },
      { label: "E", text: "Delay" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "CORROBORATE most nearly means:",
    options: [
      { label: "A", text: "Deny" },
      { label: "B", text: "Question" },
      { label: "C", text: "Confirm" },
      { label: "D", text: "Ignore" },
      { label: "E", text: "Fabricate" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "PRUDENT most nearly means:",
    options: [
      { label: "A", text: "Reckless" },
      { label: "B", text: "Cautious" },
      { label: "C", text: "Arrogant" },
      { label: "D", text: "Generous" },
      { label: "E", text: "Impatient" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "EXACERBATE most nearly means:",
    options: [
      { label: "A", text: "Improve" },
      { label: "B", text: "Soothe" },
      { label: "C", text: "Aggravate" },
      { label: "D", text: "Resolve" },
      { label: "E", text: "Examine" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },

  // Vocabulary — Hard (difficulty 3)
  {
    category: "verbal",
    difficulty: 3,
    stem: "ENERVATE most nearly means:",
    options: [
      { label: "A", text: "Energize" },
      { label: "B", text: "Weaken" },
      { label: "C", text: "Irritate" },
      { label: "D", text: "Enlighten" },
      { label: "E", text: "Excite" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "PUSILLANIMOUS most nearly means:",
    options: [
      { label: "A", text: "Courageous" },
      { label: "B", text: "Generous" },
      { label: "C", text: "Cowardly" },
      { label: "D", text: "Ambitious" },
      { label: "E", text: "Scholarly" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "IMPECUNIOUS most nearly means:",
    options: [
      { label: "A", text: "Wealthy" },
      { label: "B", text: "Careless" },
      { label: "C", text: "Penniless" },
      { label: "D", text: "Meticulous" },
      { label: "E", text: "Powerful" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "MERETRICIOUS most nearly means:",
    options: [
      { label: "A", text: "Meritorious" },
      { label: "B", text: "Superficially attractive" },
      { label: "C", text: "Generous" },
      { label: "D", text: "Authentic" },
      { label: "E", text: "Modest" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "DILATORY most nearly means:",
    options: [
      { label: "A", text: "Prompt" },
      { label: "B", text: "Expanding" },
      { label: "C", text: "Delaying" },
      { label: "D", text: "Destructive" },
      { label: "E", text: "Diplomatic" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "VERISIMILITUDE most nearly means:",
    options: [
      { label: "A", text: "Falsehood" },
      { label: "B", text: "Appearance of truth" },
      { label: "C", text: "Exact copy" },
      { label: "D", text: "Contradiction" },
      { label: "E", text: "Exaggeration" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "TENDENTIOUS most nearly means:",
    options: [
      { label: "A", text: "Impartial" },
      { label: "B", text: "Sensitive" },
      { label: "C", text: "Biased" },
      { label: "D", text: "Tentative" },
      { label: "E", text: "Compassionate" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "VITUPERATE most nearly means:",
    options: [
      { label: "A", text: "Praise" },
      { label: "B", text: "Berate" },
      { label: "C", text: "Invigorate" },
      { label: "D", text: "Negotiate" },
      { label: "E", text: "Meditate" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "ANODYNE most nearly means:",
    options: [
      { label: "A", text: "Painful" },
      { label: "B", text: "Anonymous" },
      { label: "C", text: "Soothing" },
      { label: "D", text: "Acidic" },
      { label: "E", text: "Novel" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "PULCHRITUDINOUS most nearly means:",
    options: [
      { label: "A", text: "Ugly" },
      { label: "B", text: "Powerful" },
      { label: "C", text: "Beautiful" },
      { label: "D", text: "Disgusting" },
      { label: "E", text: "Enormous" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "PERFUNCTORY most nearly means:",
    options: [
      { label: "A", text: "Thorough" },
      { label: "B", text: "Hasty" },
      { label: "C", text: "Functional" },
      { label: "D", text: "Careless and superficial" },
      { label: "E", text: "Perfect" },
    ],
    correctLabel: "D",
    tags: ["vocabulary"],
  },

  // ─── ADDITIONAL QUESTIONS TO REACH 185+ ────────────────────────────────────

  // Extra Antonyms — Medium
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to FERVENT.",
    options: [
      { label: "A", text: "Passionate" },
      { label: "B", text: "Zealous" },
      { label: "C", text: "Apathetic" },
      { label: "D", text: "Intense" },
      { label: "E", text: "Ardent" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to COPIOUS.",
    options: [
      { label: "A", text: "Plentiful" },
      { label: "B", text: "Abundant" },
      { label: "C", text: "Ample" },
      { label: "D", text: "Scanty" },
      { label: "E", text: "Generous" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },

  // Extra Analogies — Medium
  {
    category: "verbal",
    difficulty: 2,
    stem: "HIBERNATION is to WINTER as MIGRATION is to:",
    options: [
      { label: "A", text: "Birds" },
      { label: "B", text: "Season" },
      { label: "C", text: "Autumn" },
      { label: "D", text: "Travel" },
      { label: "E", text: "Navigation" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "CALLIGRAPHY is to WRITING as CHOREOGRAPHY is to:",
    options: [
      { label: "A", text: "Music" },
      { label: "B", text: "Dance" },
      { label: "C", text: "Theater" },
      { label: "D", text: "Singing" },
      { label: "E", text: "Painting" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },

  // Extra Sentence Completion — Medium
  {
    category: "verbal",
    difficulty: 2,
    stem: "The museum's collection was remarkably ___, spanning artifacts from every major civilization in recorded history.",
    options: [
      { label: "A", text: "Limited" },
      { label: "B", text: "Comprehensive" },
      { label: "C", text: "Modest" },
      { label: "D", text: "Narrow" },
      { label: "E", text: "Sparse" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The author's ___ style, using ten words where one would suffice, made his novels exhausting to read.",
    options: [
      { label: "A", text: "Concise" },
      { label: "B", text: "Economical" },
      { label: "C", text: "Prolix" },
      { label: "D", text: "Elegant" },
      { label: "E", text: "Precise" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "The teacher asked the students to ___ their homework before the end of the day.",
    options: [
      { label: "A", text: "Destroy" },
      { label: "B", text: "Submit" },
      { label: "C", text: "Forget" },
      { label: "D", text: "Hide" },
      { label: "E", text: "Ignore" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "The athlete trained every day to ___ her performance before the competition.",
    options: [
      { label: "A", text: "Worsen" },
      { label: "B", text: "Improve" },
      { label: "C", text: "Forget" },
      { label: "D", text: "Avoid" },
      { label: "E", text: "Ignore" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },

  // Extra Vocabulary — Medium
  {
    category: "verbal",
    difficulty: 2,
    stem: "ARBITRARY most nearly means:",
    options: [
      { label: "A", text: "Logical" },
      { label: "B", text: "Random" },
      { label: "C", text: "Careful" },
      { label: "D", text: "Permanent" },
      { label: "E", text: "Systematic" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "COMPLACENT most nearly means:",
    options: [
      { label: "A", text: "Anxious" },
      { label: "B", text: "Self-satisfied" },
      { label: "C", text: "Aggressive" },
      { label: "D", text: "Curious" },
      { label: "E", text: "Diligent" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },

  // Extra Antonyms — Easy
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to SMOOTH.",
    options: [
      { label: "A", text: "Sleek" },
      { label: "B", text: "Polished" },
      { label: "C", text: "Rough" },
      { label: "D", text: "Flat" },
      { label: "E", text: "Silky" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to RICH.",
    options: [
      { label: "A", text: "Wealthy" },
      { label: "B", text: "Poor" },
      { label: "C", text: "Abundant" },
      { label: "D", text: "Lavish" },
      { label: "E", text: "Prosperous" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },

  // Extra Analogies — Easy
  {
    category: "verbal",
    difficulty: 1,
    stem: "CUP is to DRINK as PLATE is to:",
    options: [
      { label: "A", text: "Eat" },
      { label: "B", text: "Kitchen" },
      { label: "C", text: "Table" },
      { label: "D", text: "Fork" },
      { label: "E", text: "Wash" },
    ],
    correctLabel: "A",
    tags: ["analogy"],
  },

  // Extra Vocabulary — Easy
  {
    category: "verbal",
    difficulty: 1,
    stem: "BOLD most nearly means:",
    options: [
      { label: "A", text: "Shy" },
      { label: "B", text: "Quiet" },
      { label: "C", text: "Daring" },
      { label: "D", text: "Slow" },
      { label: "E", text: "Weak" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },

  // Extra Sentence Completion — Hard
  {
    category: "verbal",
    difficulty: 3,
    stem: "The professor's arguments were so ___ that even his intellectual opponents conceded the strength of his position.",
    options: [
      { label: "A", text: "Specious" },
      { label: "B", text: "Fallacious" },
      { label: "C", text: "Irrefutable" },
      { label: "D", text: "Dubious" },
      { label: "E", text: "Tenuous" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },

  // Extra Analogy — Hard
  {
    category: "verbal",
    difficulty: 3,
    stem: "APOSTATE is to FAITH as EXPATRIATE is to:",
    options: [
      { label: "A", text: "Travel" },
      { label: "B", text: "Country" },
      { label: "C", text: "Language" },
      { label: "D", text: "Culture" },
      { label: "E", text: "Passport" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },

  // Extra Vocabulary — Hard
  {
    category: "verbal",
    difficulty: 3,
    stem: "PALIMPSEST most nearly means:",
    options: [
      { label: "A", text: "Ancient temple" },
      { label: "B", text: "Manuscript reused after erasure" },
      { label: "C", text: "Musical instrument" },
      { label: "D", text: "Religious ceremony" },
      { label: "E", text: "Architectural style" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },

  // Extra Antonym — Hard
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to PENURIOUS.",
    options: [
      { label: "A", text: "Miserly" },
      { label: "B", text: "Frugal" },
      { label: "C", text: "Thrifty" },
      { label: "D", text: "Munificent" },
      { label: "E", text: "Parsimonious" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },

  // Extra Sentence Completion
  {
    category: "verbal",
    difficulty: 2,
    stem: "The company adopted a more ___ approach to management, giving employees greater freedom to make decisions.",
    options: [
      { label: "A", text: "Autocratic" },
      { label: "B", text: "Rigid" },
      { label: "C", text: "Decentralized" },
      { label: "D", text: "Hierarchical" },
      { label: "E", text: "Controlling" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The artist's work was considered ___ because it broke away from established conventions and introduced entirely new techniques.",
    options: [
      { label: "A", text: "Traditional" },
      { label: "B", text: "Derivative" },
      { label: "C", text: "Conventional" },
      { label: "D", text: "Avant-garde" },
      { label: "E", text: "Imitative" },
    ],
    correctLabel: "D",
    tags: ["sentence-completion"],
  },

  // Extra Analogies — Medium
  {
    category: "verbal",
    difficulty: 2,
    stem: "CONDUCTOR is to ORCHESTRA as DIRECTOR is to:",
    options: [
      { label: "A", text: "Film" },
      { label: "B", text: "Stage" },
      { label: "C", text: "Cast" },
      { label: "D", text: "Script" },
      { label: "E", text: "Camera" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "RUDDER is to SHIP as STEERING WHEEL is to:",
    options: [
      { label: "A", text: "Engine" },
      { label: "B", text: "Road" },
      { label: "C", text: "Car" },
      { label: "D", text: "Tire" },
      { label: "E", text: "Highway" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },

  // Extra Vocabulary — Medium
  {
    category: "verbal",
    difficulty: 2,
    stem: "GREGARIOUS most nearly means:",
    options: [
      { label: "A", text: "Aggressive" },
      { label: "B", text: "Sociable" },
      { label: "C", text: "Greedy" },
      { label: "D", text: "Cautious" },
      { label: "E", text: "Solitary" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "CONUNDRUM most nearly means:",
    options: [
      { label: "A", text: "Solution" },
      { label: "B", text: "Answer" },
      { label: "C", text: "Puzzle" },
      { label: "D", text: "Lecture" },
      { label: "E", text: "Celebration" },
    ],
    correctLabel: "C",
    tags: ["vocabulary"],
  },

  // Extra Antonyms — Medium
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to OPAQUE.",
    options: [
      { label: "A", text: "Dense" },
      { label: "B", text: "Cloudy" },
      { label: "C", text: "Murky" },
      { label: "D", text: "Transparent" },
      { label: "E", text: "Dark" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to MUNDANE.",
    options: [
      { label: "A", text: "Ordinary" },
      { label: "B", text: "Routine" },
      { label: "C", text: "Extraordinary" },
      { label: "D", text: "Common" },
      { label: "E", text: "Everyday" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to SUCCINCT.",
    options: [
      { label: "A", text: "Brief" },
      { label: "B", text: "Concise" },
      { label: "C", text: "Short" },
      { label: "D", text: "Long-winded" },
      { label: "E", text: "Compact" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },

  // Extra Sentence Completion — Medium
  {
    category: "verbal",
    difficulty: 2,
    stem: "The evidence presented was entirely ___, based on secondhand accounts rather than direct observation.",
    options: [
      { label: "A", text: "Empirical" },
      { label: "B", text: "Anecdotal" },
      { label: "C", text: "Definitive" },
      { label: "D", text: "Scientific" },
      { label: "E", text: "Conclusive" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Despite her ___ demeanor in public, she was known among friends for her sharp wit and playful humor.",
    options: [
      { label: "A", text: "Animated" },
      { label: "B", text: "Reserved" },
      { label: "C", text: "Boisterous" },
      { label: "D", text: "Flamboyant" },
      { label: "E", text: "Outgoing" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },

  // Extra Vocabulary
  {
    category: "verbal",
    difficulty: 2,
    stem: "EPHEMERAL most nearly means:",
    options: [
      { label: "A", text: "Eternal" },
      { label: "B", text: "Short-lived" },
      { label: "C", text: "Powerful" },
      { label: "D", text: "Spiritual" },
      { label: "E", text: "Meaningful" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "RAPID most nearly means:",
    options: [
      { label: "A", text: "Slow" },
      { label: "B", text: "Fast" },
      { label: "C", text: "Steady" },
      { label: "D", text: "Gentle" },
      { label: "E", text: "Heavy" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },

  // Extra Analogy
  {
    category: "verbal",
    difficulty: 1,
    stem: "SEED is to PLANT as EGG is to:",
    options: [
      { label: "A", text: "Nest" },
      { label: "B", text: "Chicken" },
      { label: "C", text: "Shell" },
      { label: "D", text: "Breakfast" },
      { label: "E", text: "Farm" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },

  // Final extras to ensure 185+
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to RETICENT.",
    options: [
      { label: "A", text: "Reserved" },
      { label: "B", text: "Quiet" },
      { label: "C", text: "Forthcoming" },
      { label: "D", text: "Shy" },
      { label: "E", text: "Withdrawn" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "VACILLATE most nearly means:",
    options: [
      { label: "A", text: "Decide firmly" },
      { label: "B", text: "Waver" },
      { label: "C", text: "Accelerate" },
      { label: "D", text: "Celebrate" },
      { label: "E", text: "Evacuate" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to WEAK.",
    options: [
      { label: "A", text: "Feeble" },
      { label: "B", text: "Fragile" },
      { label: "C", text: "Strong" },
      { label: "D", text: "Thin" },
      { label: "E", text: "Tired" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "CATALYST is to REACTION as STIMULUS is to:",
    options: [
      { label: "A", text: "Response" },
      { label: "B", text: "Calm" },
      { label: "C", text: "Science" },
      { label: "D", text: "Laboratory" },
      { label: "E", text: "Chemical" },
    ],
    correctLabel: "A",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The new policy was met with ___ from employees who felt it would significantly increase their workload.",
    options: [
      { label: "A", text: "Praise" },
      { label: "B", text: "Gratitude" },
      { label: "C", text: "Resentment" },
      { label: "D", text: "Indifference" },
      { label: "E", text: "Celebration" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "MEND most nearly means:",
    options: [
      { label: "A", text: "Break" },
      { label: "B", text: "Repair" },
      { label: "C", text: "Sell" },
      { label: "D", text: "Bend" },
      { label: "E", text: "Paint" },
    ],
    correctLabel: "B",
    tags: ["vocabulary"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "ARCHIPELAGO is to ISLANDS as CONSTELLATION is to:",
    options: [
      { label: "A", text: "Planets" },
      { label: "B", text: "Stars" },
      { label: "C", text: "Galaxies" },
      { label: "D", text: "Moons" },
      { label: "E", text: "Telescopes" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  // Extra to reach 181+
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to COMPULSORY.",
    options: [
      { label: "A", text: "Mandatory" },
      { label: "B", text: "Optional" },
      { label: "C", text: "Required" },
      { label: "D", text: "Necessary" },
      { label: "E", text: "Obligatory" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
];
