type QuestionData = {
  category: "verbal" | "math_logic" | "spatial";
  difficulty: number;
  stem: string;
  options: { label: string; text: string }[];
  correctLabel: string;
  tags: string[];
};

export const verbalQuestions2: QuestionData[] = [
  // ─── ANTONYMS (45 questions) ───────────────────────────────────────────────

  // Antonyms — Easy (difficulty 1)
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to GENEROUS.",
    options: [
      { label: "A", text: "Kind" },
      { label: "B", text: "Stingy" },
      { label: "C", text: "Wealthy" },
      { label: "D", text: "Giving" },
      { label: "E", text: "Abundant" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to ANCIENT.",
    options: [
      { label: "A", text: "Old" },
      { label: "B", text: "Historic" },
      { label: "C", text: "Modern" },
      { label: "D", text: "Antique" },
      { label: "E", text: "Dusty" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to TIMID.",
    options: [
      { label: "A", text: "Shy" },
      { label: "B", text: "Quiet" },
      { label: "C", text: "Nervous" },
      { label: "D", text: "Bold" },
      { label: "E", text: "Gentle" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to NARROW.",
    options: [
      { label: "A", text: "Thin" },
      { label: "B", text: "Slim" },
      { label: "C", text: "Wide" },
      { label: "D", text: "Long" },
      { label: "E", text: "Short" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to SHALLOW.",
    options: [
      { label: "A", text: "Empty" },
      { label: "B", text: "Deep" },
      { label: "C", text: "Flat" },
      { label: "D", text: "Low" },
      { label: "E", text: "Thin" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  // Antonyms — Medium (difficulty 2)
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to VERBOSE.",
    options: [
      { label: "A", text: "Wordy" },
      { label: "B", text: "Lengthy" },
      { label: "C", text: "Concise" },
      { label: "D", text: "Elaborate" },
      { label: "E", text: "Detailed" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to HINDER.",
    options: [
      { label: "A", text: "Block" },
      { label: "B", text: "Obstruct" },
      { label: "C", text: "Delay" },
      { label: "D", text: "Facilitate" },
      { label: "E", text: "Prevent" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to TRANQUIL.",
    options: [
      { label: "A", text: "Peaceful" },
      { label: "B", text: "Turbulent" },
      { label: "C", text: "Serene" },
      { label: "D", text: "Calm" },
      { label: "E", text: "Still" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to ABUNDANT.",
    options: [
      { label: "A", text: "Plentiful" },
      { label: "B", text: "Rich" },
      { label: "C", text: "Scarce" },
      { label: "D", text: "Ample" },
      { label: "E", text: "Copious" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to BENEVOLENT.",
    options: [
      { label: "A", text: "Charitable" },
      { label: "B", text: "Malevolent" },
      { label: "C", text: "Generous" },
      { label: "D", text: "Kind" },
      { label: "E", text: "Warm" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to LETHARGIC.",
    options: [
      { label: "A", text: "Drowsy" },
      { label: "B", text: "Sluggish" },
      { label: "C", text: "Energetic" },
      { label: "D", text: "Tired" },
      { label: "E", text: "Lazy" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to DIMINISH.",
    options: [
      { label: "A", text: "Reduce" },
      { label: "B", text: "Shrink" },
      { label: "C", text: "Lessen" },
      { label: "D", text: "Amplify" },
      { label: "E", text: "Decrease" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to MUNDANE.",
    options: [
      { label: "A", text: "Ordinary" },
      { label: "B", text: "Dull" },
      { label: "C", text: "Routine" },
      { label: "D", text: "Common" },
      { label: "E", text: "Extraordinary" },
    ],
    correctLabel: "E",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to PRUDENT.",
    options: [
      { label: "A", text: "Reckless" },
      { label: "B", text: "Careful" },
      { label: "C", text: "Wise" },
      { label: "D", text: "Cautious" },
      { label: "E", text: "Sensible" },
    ],
    correctLabel: "A",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to ARID.",
    options: [
      { label: "A", text: "Dry" },
      { label: "B", text: "Barren" },
      { label: "C", text: "Parched" },
      { label: "D", text: "Lush" },
      { label: "E", text: "Dusty" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  // Antonyms — Hard (difficulty 3)
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to EPHEMERAL.",
    options: [
      { label: "A", text: "Fleeting" },
      { label: "B", text: "Transient" },
      { label: "C", text: "Permanent" },
      { label: "D", text: "Brief" },
      { label: "E", text: "Momentary" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to PERFIDIOUS.",
    options: [
      { label: "A", text: "Treacherous" },
      { label: "B", text: "Deceitful" },
      { label: "C", text: "Disloyal" },
      { label: "D", text: "Faithful" },
      { label: "E", text: "Cunning" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to OBSEQUIOUS.",
    options: [
      { label: "A", text: "Servile" },
      { label: "B", text: "Dominant" },
      { label: "C", text: "Fawning" },
      { label: "D", text: "Submissive" },
      { label: "E", text: "Compliant" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to PERSPICACIOUS.",
    options: [
      { label: "A", text: "Obtuse" },
      { label: "B", text: "Astute" },
      { label: "C", text: "Shrewd" },
      { label: "D", text: "Perceptive" },
      { label: "E", text: "Discerning" },
    ],
    correctLabel: "A",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to SANGUINE.",
    options: [
      { label: "A", text: "Hopeful" },
      { label: "B", text: "Cheerful" },
      { label: "C", text: "Optimistic" },
      { label: "D", text: "Confident" },
      { label: "E", text: "Pessimistic" },
    ],
    correctLabel: "E",
    tags: ["antonym"],
  },

  // ─── ANALOGIES (45 questions) ──────────────────────────────────────────────

  // Analogies — Easy (difficulty 1)
  {
    category: "verbal",
    difficulty: 1,
    stem: "PUPPY is to DOG as KITTEN is to ___.",
    options: [
      { label: "A", text: "Mouse" },
      { label: "B", text: "Cat" },
      { label: "C", text: "Bird" },
      { label: "D", text: "Fish" },
      { label: "E", text: "Rabbit" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "GLOVE is to HAND as SHOE is to ___.",
    options: [
      { label: "A", text: "Leg" },
      { label: "B", text: "Arm" },
      { label: "C", text: "Foot" },
      { label: "D", text: "Sock" },
      { label: "E", text: "Knee" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "CHAPTER is to BOOK as SCENE is to ___.",
    options: [
      { label: "A", text: "Actor" },
      { label: "B", text: "Play" },
      { label: "C", text: "Stage" },
      { label: "D", text: "Script" },
      { label: "E", text: "Movie" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "WING is to BIRD as FIN is to ___.",
    options: [
      { label: "A", text: "Fish" },
      { label: "B", text: "Whale" },
      { label: "C", text: "Shark" },
      { label: "D", text: "Ocean" },
      { label: "E", text: "Water" },
    ],
    correctLabel: "A",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "PETAL is to FLOWER as LEAF is to ___.",
    options: [
      { label: "A", text: "Garden" },
      { label: "B", text: "Root" },
      { label: "C", text: "Tree" },
      { label: "D", text: "Soil" },
      { label: "E", text: "Seed" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  // Analogies — Medium (difficulty 2)
  {
    category: "verbal",
    difficulty: 2,
    stem: "ARCHITECT is to BLUEPRINT as COMPOSER is to ___.",
    options: [
      { label: "A", text: "Instrument" },
      { label: "B", text: "Orchestra" },
      { label: "C", text: "Score" },
      { label: "D", text: "Concert" },
      { label: "E", text: "Melody" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "FAMINE is to HUNGER as DROUGHT is to ___.",
    options: [
      { label: "A", text: "Rain" },
      { label: "B", text: "Thirst" },
      { label: "C", text: "Flood" },
      { label: "D", text: "Weather" },
      { label: "E", text: "Heat" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "SCALPEL is to SURGEON as GAVEL is to ___.",
    options: [
      { label: "A", text: "Lawyer" },
      { label: "B", text: "Judge" },
      { label: "C", text: "Courtroom" },
      { label: "D", text: "Carpenter" },
      { label: "E", text: "Jury" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "CANVAS is to PAINTER as STAGE is to ___.",
    options: [
      { label: "A", text: "Director" },
      { label: "B", text: "Audience" },
      { label: "C", text: "Actor" },
      { label: "D", text: "Curtain" },
      { label: "E", text: "Theater" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "TELESCOPE is to ASTRONOMER as MICROSCOPE is to ___.",
    options: [
      { label: "A", text: "Doctor" },
      { label: "B", text: "Biologist" },
      { label: "C", text: "Engineer" },
      { label: "D", text: "Physicist" },
      { label: "E", text: "Chemist" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "RUDDER is to SHIP as STEERING WHEEL is to ___.",
    options: [
      { label: "A", text: "Tire" },
      { label: "B", text: "Road" },
      { label: "C", text: "Car" },
      { label: "D", text: "Engine" },
      { label: "E", text: "Driver" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "MARATHON is to RUNNER as RECITAL is to ___.",
    options: [
      { label: "A", text: "Audience" },
      { label: "B", text: "Musician" },
      { label: "C", text: "Stage" },
      { label: "D", text: "Song" },
      { label: "E", text: "Teacher" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "THERMOMETER is to TEMPERATURE as BAROMETER is to ___.",
    options: [
      { label: "A", text: "Wind" },
      { label: "B", text: "Humidity" },
      { label: "C", text: "Pressure" },
      { label: "D", text: "Altitude" },
      { label: "E", text: "Rain" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "PROLOGUE is to EPILOGUE as DAWN is to ___.",
    options: [
      { label: "A", text: "Morning" },
      { label: "B", text: "Noon" },
      { label: "C", text: "Dusk" },
      { label: "D", text: "Night" },
      { label: "E", text: "Sunset" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "COCOON is to BUTTERFLY as CHRYSALIS is to ___.",
    options: [
      { label: "A", text: "Caterpillar" },
      { label: "B", text: "Moth" },
      { label: "C", text: "Larva" },
      { label: "D", text: "Beetle" },
      { label: "E", text: "Pupa" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  // Analogies — Hard (difficulty 3)
  {
    category: "verbal",
    difficulty: 3,
    stem: "OLFACTORY is to SMELL as GUSTATORY is to ___.",
    options: [
      { label: "A", text: "Sight" },
      { label: "B", text: "Touch" },
      { label: "C", text: "Hearing" },
      { label: "D", text: "Taste" },
      { label: "E", text: "Balance" },
    ],
    correctLabel: "D",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "PARSIMONIOUS is to SPENDING as TACITURN is to ___.",
    options: [
      { label: "A", text: "Sleeping" },
      { label: "B", text: "Speaking" },
      { label: "C", text: "Eating" },
      { label: "D", text: "Working" },
      { label: "E", text: "Walking" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "MITIGATE is to SEVERITY as ALLEVIATE is to ___.",
    options: [
      { label: "A", text: "Pleasure" },
      { label: "B", text: "Comfort" },
      { label: "C", text: "Pain" },
      { label: "D", text: "Joy" },
      { label: "E", text: "Health" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "ICONOCLAST is to TRADITION as MAVERICK is to ___.",
    options: [
      { label: "A", text: "Innovation" },
      { label: "B", text: "Conformity" },
      { label: "C", text: "Leadership" },
      { label: "D", text: "Creativity" },
      { label: "E", text: "Independence" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "SOPORIFIC is to SLEEP as EMETIC is to ___.",
    options: [
      { label: "A", text: "Coughing" },
      { label: "B", text: "Sneezing" },
      { label: "C", text: "Vomiting" },
      { label: "D", text: "Sweating" },
      { label: "E", text: "Fainting" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },

  // ─── SYNONYMS (45 questions) ──────────────────────────────────────────────

  // Synonyms — Easy (difficulty 1)
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word means the same as QUICK?",
    options: [
      { label: "A", text: "Heavy" },
      { label: "B", text: "Fast" },
      { label: "C", text: "Tall" },
      { label: "D", text: "Dark" },
      { label: "E", text: "Soft" },
    ],
    correctLabel: "B",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word means the same as ANGRY?",
    options: [
      { label: "A", text: "Furious" },
      { label: "B", text: "Happy" },
      { label: "C", text: "Tired" },
      { label: "D", text: "Bored" },
      { label: "E", text: "Calm" },
    ],
    correctLabel: "A",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word means the same as SMALL?",
    options: [
      { label: "A", text: "Huge" },
      { label: "B", text: "Bright" },
      { label: "C", text: "Tiny" },
      { label: "D", text: "Round" },
      { label: "E", text: "Sharp" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word means the same as SCARED?",
    options: [
      { label: "A", text: "Brave" },
      { label: "B", text: "Loud" },
      { label: "C", text: "Quiet" },
      { label: "D", text: "Afraid" },
      { label: "E", text: "Strong" },
    ],
    correctLabel: "D",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word means the same as WEALTHY?",
    options: [
      { label: "A", text: "Poor" },
      { label: "B", text: "Sick" },
      { label: "C", text: "Rich" },
      { label: "D", text: "Tired" },
      { label: "E", text: "Young" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  // Synonyms — Medium (difficulty 2)
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as DILIGENT?",
    options: [
      { label: "A", text: "Lazy" },
      { label: "B", text: "Careless" },
      { label: "C", text: "Indifferent" },
      { label: "D", text: "Industrious" },
      { label: "E", text: "Casual" },
    ],
    correctLabel: "D",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as BENIGN?",
    options: [
      { label: "A", text: "Harmful" },
      { label: "B", text: "Hostile" },
      { label: "C", text: "Harmless" },
      { label: "D", text: "Dangerous" },
      { label: "E", text: "Toxic" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as CANDID?",
    options: [
      { label: "A", text: "Deceptive" },
      { label: "B", text: "Frank" },
      { label: "C", text: "Reserved" },
      { label: "D", text: "Secretive" },
      { label: "E", text: "Polite" },
    ],
    correctLabel: "B",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as PLAUSIBLE?",
    options: [
      { label: "A", text: "Impossible" },
      { label: "B", text: "Absurd" },
      { label: "C", text: "Believable" },
      { label: "D", text: "Certain" },
      { label: "E", text: "Proven" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as FUTILE?",
    options: [
      { label: "A", text: "Useless" },
      { label: "B", text: "Helpful" },
      { label: "C", text: "Strong" },
      { label: "D", text: "Vital" },
      { label: "E", text: "Clever" },
    ],
    correctLabel: "A",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as OBSCURE?",
    options: [
      { label: "A", text: "Famous" },
      { label: "B", text: "Obvious" },
      { label: "C", text: "Hidden" },
      { label: "D", text: "Bright" },
      { label: "E", text: "Popular" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as ELATED?",
    options: [
      { label: "A", text: "Depressed" },
      { label: "B", text: "Bored" },
      { label: "C", text: "Overjoyed" },
      { label: "D", text: "Indifferent" },
      { label: "E", text: "Anxious" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as METICULOUS?",
    options: [
      { label: "A", text: "Sloppy" },
      { label: "B", text: "Careless" },
      { label: "C", text: "Rash" },
      { label: "D", text: "Thorough" },
      { label: "E", text: "Quick" },
    ],
    correctLabel: "D",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as RELUCTANT?",
    options: [
      { label: "A", text: "Eager" },
      { label: "B", text: "Hesitant" },
      { label: "C", text: "Excited" },
      { label: "D", text: "Willing" },
      { label: "E", text: "Ready" },
    ],
    correctLabel: "B",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as SERENE?",
    options: [
      { label: "A", text: "Chaotic" },
      { label: "B", text: "Noisy" },
      { label: "C", text: "Stormy" },
      { label: "D", text: "Turbulent" },
      { label: "E", text: "Peaceful" },
    ],
    correctLabel: "E",
    tags: ["synonym"],
  },
  // Synonyms — Hard (difficulty 3)
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word means the same as VITUPERATE?",
    options: [
      { label: "A", text: "Praise" },
      { label: "B", text: "Berate" },
      { label: "C", text: "Support" },
      { label: "D", text: "Encourage" },
      { label: "E", text: "Admire" },
    ],
    correctLabel: "B",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word means the same as EQUANIMITY?",
    options: [
      { label: "A", text: "Panic" },
      { label: "B", text: "Composure" },
      { label: "C", text: "Anxiety" },
      { label: "D", text: "Fury" },
      { label: "E", text: "Despair" },
    ],
    correctLabel: "B",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word means the same as PERNICIOUS?",
    options: [
      { label: "A", text: "Beneficial" },
      { label: "B", text: "Helpful" },
      { label: "C", text: "Harmful" },
      { label: "D", text: "Gentle" },
      { label: "E", text: "Mild" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word means the same as PROPITIOUS?",
    options: [
      { label: "A", text: "Unlucky" },
      { label: "B", text: "Disastrous" },
      { label: "C", text: "Hostile" },
      { label: "D", text: "Favorable" },
      { label: "E", text: "Harmful" },
    ],
    correctLabel: "D",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word means the same as QUIXOTIC?",
    options: [
      { label: "A", text: "Practical" },
      { label: "B", text: "Realistic" },
      { label: "C", text: "Pragmatic" },
      { label: "D", text: "Sensible" },
      { label: "E", text: "Idealistic" },
    ],
    correctLabel: "E",
    tags: ["synonym"],
  },

  // ─── SENTENCE COMPLETION (45 questions) ────────────────────────────────────

  // Sentence Completion — Easy (difficulty 1)
  {
    category: "verbal",
    difficulty: 1,
    stem: "The weather was so ___ that we decided to stay indoors.",
    options: [
      { label: "A", text: "sunny" },
      { label: "B", text: "terrible" },
      { label: "C", text: "warm" },
      { label: "D", text: "pleasant" },
      { label: "E", text: "mild" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "She was ___ to hear that she had won the prize.",
    options: [
      { label: "A", text: "disappointed" },
      { label: "B", text: "angry" },
      { label: "C", text: "delighted" },
      { label: "D", text: "confused" },
      { label: "E", text: "bored" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "The library is a ___ place where people go to read and study.",
    options: [
      { label: "A", text: "loud" },
      { label: "B", text: "quiet" },
      { label: "C", text: "chaotic" },
      { label: "D", text: "crowded" },
      { label: "E", text: "noisy" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "The instructions were so ___ that everyone could follow them easily.",
    options: [
      { label: "A", text: "confusing" },
      { label: "B", text: "complicated" },
      { label: "C", text: "vague" },
      { label: "D", text: "clear" },
      { label: "E", text: "difficult" },
    ],
    correctLabel: "D",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "After running for an hour, the athlete was completely ___.",
    options: [
      { label: "A", text: "energized" },
      { label: "B", text: "rested" },
      { label: "C", text: "exhausted" },
      { label: "D", text: "refreshed" },
      { label: "E", text: "alert" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  // Sentence Completion — Medium (difficulty 2)
  {
    category: "verbal",
    difficulty: 2,
    stem: "The scientist's ___ research finally led to a breakthrough after years of failed experiments.",
    options: [
      { label: "A", text: "careless" },
      { label: "B", text: "hasty" },
      { label: "C", text: "persistent" },
      { label: "D", text: "superficial" },
      { label: "E", text: "random" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Despite the ___ evidence, the jury remained unconvinced of the defendant's guilt.",
    options: [
      { label: "A", text: "lacking" },
      { label: "B", text: "compelling" },
      { label: "C", text: "absent" },
      { label: "D", text: "weak" },
      { label: "E", text: "insufficient" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The diplomat's ___ approach helped resolve the conflict without further aggression.",
    options: [
      { label: "A", text: "aggressive" },
      { label: "B", text: "hostile" },
      { label: "C", text: "conciliatory" },
      { label: "D", text: "confrontational" },
      { label: "E", text: "provocative" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The committee's decision was ___, leaving no room for appeal or negotiation.",
    options: [
      { label: "A", text: "tentative" },
      { label: "B", text: "flexible" },
      { label: "C", text: "negotiable" },
      { label: "D", text: "final" },
      { label: "E", text: "uncertain" },
    ],
    correctLabel: "D",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Her ___ manner made her popular at social gatherings.",
    options: [
      { label: "A", text: "rude" },
      { label: "B", text: "hostile" },
      { label: "C", text: "affable" },
      { label: "D", text: "distant" },
      { label: "E", text: "sullen" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The medicine's ___ effects far outweighed its benefits, leading to its withdrawal.",
    options: [
      { label: "A", text: "positive" },
      { label: "B", text: "adverse" },
      { label: "C", text: "helpful" },
      { label: "D", text: "minor" },
      { label: "E", text: "therapeutic" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The new policy was designed to ___ the growing gap between rich and poor.",
    options: [
      { label: "A", text: "widen" },
      { label: "B", text: "ignore" },
      { label: "C", text: "bridge" },
      { label: "D", text: "increase" },
      { label: "E", text: "maintain" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The professor's lectures were so ___ that students often fell asleep.",
    options: [
      { label: "A", text: "engaging" },
      { label: "B", text: "tedious" },
      { label: "C", text: "fascinating" },
      { label: "D", text: "thrilling" },
      { label: "E", text: "captivating" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The ruins stood as a ___ reminder of the civilization that once thrived there.",
    options: [
      { label: "A", text: "cheerful" },
      { label: "B", text: "joyful" },
      { label: "C", text: "solemn" },
      { label: "D", text: "festive" },
      { label: "E", text: "vibrant" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The CEO's ___ leadership style encouraged employees to share ideas freely.",
    options: [
      { label: "A", text: "autocratic" },
      { label: "B", text: "democratic" },
      { label: "C", text: "tyrannical" },
      { label: "D", text: "dictatorial" },
      { label: "E", text: "oppressive" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  // Sentence Completion — Hard (difficulty 3)
  {
    category: "verbal",
    difficulty: 3,
    stem: "The author's ___ style, though initially off-putting, proved to be the very quality that distinguished her work.",
    options: [
      { label: "A", text: "conventional" },
      { label: "B", text: "idiosyncratic" },
      { label: "C", text: "mundane" },
      { label: "D", text: "typical" },
      { label: "E", text: "ordinary" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "The politician's speech was a masterclass in ___, saying much while committing to nothing specific.",
    options: [
      { label: "A", text: "precision" },
      { label: "B", text: "clarity" },
      { label: "C", text: "equivocation" },
      { label: "D", text: "honesty" },
      { label: "E", text: "candor" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "The discovery was ___, overturning decades of established scientific consensus.",
    options: [
      { label: "A", text: "incremental" },
      { label: "B", text: "trivial" },
      { label: "C", text: "marginal" },
      { label: "D", text: "paradigm-shifting" },
      { label: "E", text: "predictable" },
    ],
    correctLabel: "D",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "His ___ demeanor concealed a razor-sharp intellect that few suspected.",
    options: [
      { label: "A", text: "brilliant" },
      { label: "B", text: "imposing" },
      { label: "C", text: "unassuming" },
      { label: "D", text: "intimidating" },
      { label: "E", text: "dazzling" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "The treaty was intentionally ___, allowing each nation to interpret its terms differently.",
    options: [
      { label: "A", text: "specific" },
      { label: "B", text: "detailed" },
      { label: "C", text: "explicit" },
      { label: "D", text: "ambiguous" },
      { label: "E", text: "precise" },
    ],
    correctLabel: "D",
    tags: ["sentence-completion"],
  },

  // ─── READING COMPREHENSION / WORD CONTEXT (45 questions) ──────────────────

  // Word Context — Easy (difficulty 1)
  {
    category: "verbal",
    difficulty: 1,
    stem: "In the sentence 'The bank of the river was covered with wildflowers,' what does 'bank' mean?",
    options: [
      { label: "A", text: "A financial institution" },
      { label: "B", text: "The edge of a river" },
      { label: "C", text: "A pile of snow" },
      { label: "D", text: "A type of building" },
      { label: "E", text: "A storage container" },
    ],
    correctLabel: "B",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "In the sentence 'Please file these documents in the cabinet,' what does 'file' mean?",
    options: [
      { label: "A", text: "A metal tool" },
      { label: "B", text: "A line of people" },
      { label: "C", text: "To organize and store" },
      { label: "D", text: "A computer document" },
      { label: "E", text: "To sharpen" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "In the sentence 'The spring in the mattress broke,' what does 'spring' mean?",
    options: [
      { label: "A", text: "A season" },
      { label: "B", text: "A water source" },
      { label: "C", text: "A coiled metal piece" },
      { label: "D", text: "To jump" },
      { label: "E", text: "A type of flower" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "In the sentence 'He had to bear the weight of the heavy box,' what does 'bear' mean?",
    options: [
      { label: "A", text: "A large animal" },
      { label: "B", text: "To carry or support" },
      { label: "C", text: "Bare or empty" },
      { label: "D", text: "To give birth" },
      { label: "E", text: "A stuffed toy" },
    ],
    correctLabel: "B",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "In the sentence 'The match ended in a draw,' what does 'draw' mean?",
    options: [
      { label: "A", text: "To sketch" },
      { label: "B", text: "To pull" },
      { label: "C", text: "A tie" },
      { label: "D", text: "An attraction" },
      { label: "E", text: "A drawer" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },
  // Word Context — Medium (difficulty 2)
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'The judge will try to mediate the dispute,' what does 'mediate' mean?",
    options: [
      { label: "A", text: "To intensify" },
      { label: "B", text: "To help settle" },
      { label: "C", text: "To ignore" },
      { label: "D", text: "To postpone" },
      { label: "E", text: "To publicize" },
    ],
    correctLabel: "B",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'Her pragmatic approach to the problem impressed the team,' what does 'pragmatic' mean?",
    options: [
      { label: "A", text: "Theoretical" },
      { label: "B", text: "Impractical" },
      { label: "C", text: "Idealistic" },
      { label: "D", text: "Practical" },
      { label: "E", text: "Emotional" },
    ],
    correctLabel: "D",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'The committee decided to defer the vote until next month,' what does 'defer' mean?",
    options: [
      { label: "A", text: "To cancel" },
      { label: "B", text: "To speed up" },
      { label: "C", text: "To postpone" },
      { label: "D", text: "To reject" },
      { label: "E", text: "To finalize" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'The company's policy was deliberately ambiguous,' what does 'ambiguous' mean?",
    options: [
      { label: "A", text: "Very strict" },
      { label: "B", text: "Open to multiple interpretations" },
      { label: "C", text: "Extremely clear" },
      { label: "D", text: "Completely fair" },
      { label: "E", text: "Well-written" },
    ],
    correctLabel: "B",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'The news corroborated her version of events,' what does 'corroborated' mean?",
    options: [
      { label: "A", text: "Contradicted" },
      { label: "B", text: "Confused" },
      { label: "C", text: "Confirmed" },
      { label: "D", text: "Changed" },
      { label: "E", text: "Complicated" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'The new regulations will supersede the old ones,' what does 'supersede' mean?",
    options: [
      { label: "A", text: "Support" },
      { label: "B", text: "Strengthen" },
      { label: "C", text: "Supplement" },
      { label: "D", text: "Replace" },
      { label: "E", text: "Repeat" },
    ],
    correctLabel: "D",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'The witness recanted her earlier testimony,' what does 'recanted' mean?",
    options: [
      { label: "A", text: "Repeated" },
      { label: "B", text: "Emphasized" },
      { label: "C", text: "Withdrew" },
      { label: "D", text: "Extended" },
      { label: "E", text: "Expanded" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'The policy aims to mitigate the effects of climate change,' what does 'mitigate' mean?",
    options: [
      { label: "A", text: "Worsen" },
      { label: "B", text: "Ignore" },
      { label: "C", text: "Eliminate" },
      { label: "D", text: "Lessen" },
      { label: "E", text: "Cause" },
    ],
    correctLabel: "D",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'His actions were deemed reprehensible by the board,' what does 'reprehensible' mean?",
    options: [
      { label: "A", text: "Admirable" },
      { label: "B", text: "Acceptable" },
      { label: "C", text: "Understandable" },
      { label: "D", text: "Deplorable" },
      { label: "E", text: "Predictable" },
    ],
    correctLabel: "D",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'The novel offers a poignant portrayal of loss,' what does 'poignant' mean?",
    options: [
      { label: "A", text: "Humorous" },
      { label: "B", text: "Dull" },
      { label: "C", text: "Deeply moving" },
      { label: "D", text: "Confusing" },
      { label: "E", text: "Lengthy" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },
  // Word Context — Hard (difficulty 3)
  {
    category: "verbal",
    difficulty: 3,
    stem: "In the sentence 'The critic's encomium surprised the modest artist,' what does 'encomium' mean?",
    options: [
      { label: "A", text: "Harsh criticism" },
      { label: "B", text: "Warm praise" },
      { label: "C", text: "Formal complaint" },
      { label: "D", text: "Detailed analysis" },
      { label: "E", text: "Public apology" },
    ],
    correctLabel: "B",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "In the sentence 'The professor's didactic tone alienated some students,' what does 'didactic' mean?",
    options: [
      { label: "A", text: "Entertaining" },
      { label: "B", text: "Morally instructive" },
      { label: "C", text: "Humorous" },
      { label: "D", text: "Chaotic" },
      { label: "E", text: "Whispering" },
    ],
    correctLabel: "B",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "In the sentence 'Her laconic reply revealed nothing about her true feelings,' what does 'laconic' mean?",
    options: [
      { label: "A", text: "Emotional" },
      { label: "B", text: "Lengthy" },
      { label: "C", text: "Concise" },
      { label: "D", text: "Loud" },
      { label: "E", text: "Passionate" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "In the sentence 'The sophistry of his argument fooled many listeners,' what does 'sophistry' mean?",
    options: [
      { label: "A", text: "Wisdom" },
      { label: "B", text: "Cleverly deceptive reasoning" },
      { label: "C", text: "Simplicity" },
      { label: "D", text: "Elegance" },
      { label: "E", text: "Honesty" },
    ],
    correctLabel: "B",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "In the sentence 'The leader's hegemony over the region lasted decades,' what does 'hegemony' mean?",
    options: [
      { label: "A", text: "Weakness" },
      { label: "B", text: "Generosity" },
      { label: "C", text: "Dominance" },
      { label: "D", text: "Absence" },
      { label: "E", text: "Charity" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },

  // ─── ADDITIONAL VERBAL (79 more questions to reach 180) ────────────────────

  // More Antonyms
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to DULL.",
    options: [
      { label: "A", text: "Boring" },
      { label: "B", text: "Bright" },
      { label: "C", text: "Gray" },
      { label: "D", text: "Flat" },
      { label: "E", text: "Plain" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to SOFT.",
    options: [
      { label: "A", text: "Gentle" },
      { label: "B", text: "Smooth" },
      { label: "C", text: "Hard" },
      { label: "D", text: "Light" },
      { label: "E", text: "Quiet" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to EMPTY.",
    options: [
      { label: "A", text: "Hollow" },
      { label: "B", text: "Full" },
      { label: "C", text: "Vacant" },
      { label: "D", text: "Bare" },
      { label: "E", text: "Clear" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to FRUGAL.",
    options: [
      { label: "A", text: "Thrifty" },
      { label: "B", text: "Economical" },
      { label: "C", text: "Extravagant" },
      { label: "D", text: "Careful" },
      { label: "E", text: "Modest" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to TENACIOUS.",
    options: [
      { label: "A", text: "Yielding" },
      { label: "B", text: "Firm" },
      { label: "C", text: "Stubborn" },
      { label: "D", text: "Persistent" },
      { label: "E", text: "Determined" },
    ],
    correctLabel: "A",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to AMBIVALENT.",
    options: [
      { label: "A", text: "Undecided" },
      { label: "B", text: "Confused" },
      { label: "C", text: "Torn" },
      { label: "D", text: "Resolute" },
      { label: "E", text: "Uncertain" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to LACHRYMOSE.",
    options: [
      { label: "A", text: "Tearful" },
      { label: "B", text: "Weepy" },
      { label: "C", text: "Jovial" },
      { label: "D", text: "Mournful" },
      { label: "E", text: "Sorrowful" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to PROFLIGATE.",
    options: [
      { label: "A", text: "Wasteful" },
      { label: "B", text: "Reckless" },
      { label: "C", text: "Lavish" },
      { label: "D", text: "Frugal" },
      { label: "E", text: "Excessive" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to RECONDITE.",
    options: [
      { label: "A", text: "Obscure" },
      { label: "B", text: "Straightforward" },
      { label: "C", text: "Arcane" },
      { label: "D", text: "Esoteric" },
      { label: "E", text: "Complex" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },

  // More Analogies
  {
    category: "verbal",
    difficulty: 1,
    stem: "HAMMER is to NAIL as SCREWDRIVER is to ___.",
    options: [
      { label: "A", text: "Bolt" },
      { label: "B", text: "Wrench" },
      { label: "C", text: "Screw" },
      { label: "D", text: "Drill" },
      { label: "E", text: "Pliers" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "HOUR is to DAY as DAY is to ___.",
    options: [
      { label: "A", text: "Month" },
      { label: "B", text: "Week" },
      { label: "C", text: "Year" },
      { label: "D", text: "Minute" },
      { label: "E", text: "Night" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "NEEDLE is to THREAD as PEN is to ___.",
    options: [
      { label: "A", text: "Paper" },
      { label: "B", text: "Ink" },
      { label: "C", text: "Pencil" },
      { label: "D", text: "Book" },
      { label: "E", text: "Writer" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "CONSTELLATION is to STARS as ARCHIPELAGO is to ___.",
    options: [
      { label: "A", text: "Mountains" },
      { label: "B", text: "Islands" },
      { label: "C", text: "Rivers" },
      { label: "D", text: "Continents" },
      { label: "E", text: "Oceans" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "LIBRARY is to BOOKS as MUSEUM is to ___.",
    options: [
      { label: "A", text: "Visitors" },
      { label: "B", text: "Guides" },
      { label: "C", text: "Artifacts" },
      { label: "D", text: "Tickets" },
      { label: "E", text: "Buildings" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "CATERPILLAR is to BUTTERFLY as TADPOLE is to ___.",
    options: [
      { label: "A", text: "Fish" },
      { label: "B", text: "Lizard" },
      { label: "C", text: "Frog" },
      { label: "D", text: "Snake" },
      { label: "E", text: "Turtle" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "OASIS is to DESERT as HARBOR is to ___.",
    options: [
      { label: "A", text: "Lake" },
      { label: "B", text: "Sea" },
      { label: "C", text: "River" },
      { label: "D", text: "Beach" },
      { label: "E", text: "Pond" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "APOGEE is to NADIR as ZENITH is to ___.",
    options: [
      { label: "A", text: "Peak" },
      { label: "B", text: "Summit" },
      { label: "C", text: "Abyss" },
      { label: "D", text: "Apex" },
      { label: "E", text: "Pinnacle" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "ENTOMOLOGIST is to INSECTS as ORNITHOLOGIST is to ___.",
    options: [
      { label: "A", text: "Fossils" },
      { label: "B", text: "Plants" },
      { label: "C", text: "Stars" },
      { label: "D", text: "Birds" },
      { label: "E", text: "Rocks" },
    ],
    correctLabel: "D",
    tags: ["analogy"],
  },

  // More Synonyms
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word means the same as INTELLIGENT?",
    options: [
      { label: "A", text: "Smart" },
      { label: "B", text: "Slow" },
      { label: "C", text: "Weak" },
      { label: "D", text: "Dull" },
      { label: "E", text: "Heavy" },
    ],
    correctLabel: "A",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word means the same as BEAUTIFUL?",
    options: [
      { label: "A", text: "Ugly" },
      { label: "B", text: "Dark" },
      { label: "C", text: "Gorgeous" },
      { label: "D", text: "Rough" },
      { label: "E", text: "Loud" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word means the same as ENORMOUS?",
    options: [
      { label: "A", text: "Tiny" },
      { label: "B", text: "Huge" },
      { label: "C", text: "Thin" },
      { label: "D", text: "Short" },
      { label: "E", text: "Light" },
    ],
    correctLabel: "B",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as VORACIOUS?",
    options: [
      { label: "A", text: "Picky" },
      { label: "B", text: "Slow" },
      { label: "C", text: "Ravenous" },
      { label: "D", text: "Gentle" },
      { label: "E", text: "Quiet" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as PRAGMATIC?",
    options: [
      { label: "A", text: "Dreamy" },
      { label: "B", text: "Practical" },
      { label: "C", text: "Emotional" },
      { label: "D", text: "Reckless" },
      { label: "E", text: "Artistic" },
    ],
    correctLabel: "B",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as SPORADIC?",
    options: [
      { label: "A", text: "Constant" },
      { label: "B", text: "Regular" },
      { label: "C", text: "Frequent" },
      { label: "D", text: "Occasional" },
      { label: "E", text: "Daily" },
    ],
    correctLabel: "D",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word means the same as TRUCULENT?",
    options: [
      { label: "A", text: "Peaceful" },
      { label: "B", text: "Gentle" },
      { label: "C", text: "Aggressive" },
      { label: "D", text: "Timid" },
      { label: "E", text: "Kind" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word means the same as INEFFABLE?",
    options: [
      { label: "A", text: "Indescribable" },
      { label: "B", text: "Worthless" },
      { label: "C", text: "Ordinary" },
      { label: "D", text: "Obvious" },
      { label: "E", text: "Simple" },
    ],
    correctLabel: "A",
    tags: ["synonym"],
  },

  // More Sentence Completion
  {
    category: "verbal",
    difficulty: 1,
    stem: "The child was ___ because she lost her favorite toy.",
    options: [
      { label: "A", text: "happy" },
      { label: "B", text: "excited" },
      { label: "C", text: "upset" },
      { label: "D", text: "cheerful" },
      { label: "E", text: "amused" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "The sun was so ___ that everyone wore sunglasses.",
    options: [
      { label: "A", text: "dim" },
      { label: "B", text: "bright" },
      { label: "C", text: "cold" },
      { label: "D", text: "dark" },
      { label: "E", text: "cloudy" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Because of the heavy rain, the streets were completely ___.",
    options: [
      { label: "A", text: "dry" },
      { label: "B", text: "dusty" },
      { label: "C", text: "flooded" },
      { label: "D", text: "frozen" },
      { label: "E", text: "empty" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The researcher's findings were ___, challenging long-held assumptions about the disease.",
    options: [
      { label: "A", text: "confirmatory" },
      { label: "B", text: "revolutionary" },
      { label: "C", text: "predictable" },
      { label: "D", text: "conventional" },
      { label: "E", text: "expected" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The witness provided a ___ account that matched every detail of the security footage.",
    options: [
      { label: "A", text: "vague" },
      { label: "B", text: "contradictory" },
      { label: "C", text: "precise" },
      { label: "D", text: "confused" },
      { label: "E", text: "fictional" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The artist's work was ___, blending elements from multiple cultures and time periods.",
    options: [
      { label: "A", text: "uniform" },
      { label: "B", text: "monotonous" },
      { label: "C", text: "eclectic" },
      { label: "D", text: "traditional" },
      { label: "E", text: "plain" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "The philosopher's ___ arguments were so dense that only specialists could follow them.",
    options: [
      { label: "A", text: "simple" },
      { label: "B", text: "abstruse" },
      { label: "C", text: "trivial" },
      { label: "D", text: "clear" },
      { label: "E", text: "obvious" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Despite his ___ exterior, he harbored deep insecurities that few ever glimpsed.",
    options: [
      { label: "A", text: "vulnerable" },
      { label: "B", text: "transparent" },
      { label: "C", text: "imperturbable" },
      { label: "D", text: "anxious" },
      { label: "E", text: "fragile" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },

  // More Word Context
  {
    category: "verbal",
    difficulty: 1,
    stem: "In the sentence 'The pitcher threw a fast ball,' what does 'pitcher' mean?",
    options: [
      { label: "A", text: "A water container" },
      { label: "B", text: "A baseball player" },
      { label: "C", text: "A type of plant" },
      { label: "D", text: "A musical instrument" },
      { label: "E", text: "A cooking pot" },
    ],
    correctLabel: "B",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "In the sentence 'She had to crane her neck to see the stage,' what does 'crane' mean?",
    options: [
      { label: "A", text: "A large bird" },
      { label: "B", text: "A construction machine" },
      { label: "C", text: "To stretch" },
      { label: "D", text: "To fold" },
      { label: "E", text: "A type of paper art" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "In the sentence 'The bark of the old oak was rough,' what does 'bark' mean?",
    options: [
      { label: "A", text: "A dog's sound" },
      { label: "B", text: "A boat" },
      { label: "C", text: "The outer layer of a tree" },
      { label: "D", text: "To shout" },
      { label: "E", text: "A type of chocolate" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'The company tried to ameliorate working conditions,' what does 'ameliorate' mean?",
    options: [
      { label: "A", text: "Worsen" },
      { label: "B", text: "Ignore" },
      { label: "C", text: "Improve" },
      { label: "D", text: "Study" },
      { label: "E", text: "Document" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'The evidence was purely circumstantial,' what does 'circumstantial' mean?",
    options: [
      { label: "A", text: "Direct and conclusive" },
      { label: "B", text: "Based on indirect factors" },
      { label: "C", text: "Completely fabricated" },
      { label: "D", text: "Eyewitness-based" },
      { label: "E", text: "Scientific" },
    ],
    correctLabel: "B",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'The two theories are mutually exclusive,' what does 'mutually exclusive' mean?",
    options: [
      { label: "A", text: "They support each other" },
      { label: "B", text: "They are identical" },
      { label: "C", text: "Both can be true simultaneously" },
      { label: "D", text: "If one is true, the other must be false" },
      { label: "E", text: "They are unrelated" },
    ],
    correctLabel: "D",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "In the sentence 'The speaker used specious logic to win the debate,' what does 'specious' mean?",
    options: [
      { label: "A", text: "Sound and valid" },
      { label: "B", text: "Seemingly correct but actually wrong" },
      { label: "C", text: "Extremely complicated" },
      { label: "D", text: "Brilliantly original" },
      { label: "E", text: "Universally accepted" },
    ],
    correctLabel: "B",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "In the sentence 'The pundit offered a trenchant analysis of the policy,' what does 'trenchant' mean?",
    options: [
      { label: "A", text: "Superficial" },
      { label: "B", text: "Biased" },
      { label: "C", text: "Vigorous and incisive" },
      { label: "D", text: "Lengthy" },
      { label: "E", text: "Neutral" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },

  // More mixed verbal questions to reach 180
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to POLITE.",
    options: [
      { label: "A", text: "Courteous" },
      { label: "B", text: "Rude" },
      { label: "C", text: "Formal" },
      { label: "D", text: "Gentle" },
      { label: "E", text: "Proper" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to FRESH.",
    options: [
      { label: "A", text: "New" },
      { label: "B", text: "Clean" },
      { label: "C", text: "Stale" },
      { label: "D", text: "Cool" },
      { label: "E", text: "Crisp" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "KNIFE is to CUT as BROOM is to ___.",
    options: [
      { label: "A", text: "Dust" },
      { label: "B", text: "Sweep" },
      { label: "C", text: "Clean" },
      { label: "D", text: "Mop" },
      { label: "E", text: "Wash" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word means the same as DIFFICULT?",
    options: [
      { label: "A", text: "Easy" },
      { label: "B", text: "Simple" },
      { label: "C", text: "Hard" },
      { label: "D", text: "Clear" },
      { label: "E", text: "Light" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to CANDID.",
    options: [
      { label: "A", text: "Honest" },
      { label: "B", text: "Open" },
      { label: "C", text: "Forthright" },
      { label: "D", text: "Deceitful" },
      { label: "E", text: "Direct" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "FORGE is to BLACKSMITH as KILN is to ___.",
    options: [
      { label: "A", text: "Baker" },
      { label: "B", text: "Potter" },
      { label: "C", text: "Sculptor" },
      { label: "D", text: "Painter" },
      { label: "E", text: "Weaver" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as TENUOUS?",
    options: [
      { label: "A", text: "Strong" },
      { label: "B", text: "Solid" },
      { label: "C", text: "Weak" },
      { label: "D", text: "Robust" },
      { label: "E", text: "Firm" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The company's ___ growth over the past decade has made it a market leader.",
    options: [
      { label: "A", text: "sluggish" },
      { label: "B", text: "stagnant" },
      { label: "C", text: "exponential" },
      { label: "D", text: "minimal" },
      { label: "E", text: "declining" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'The manager decided to expedite the process,' what does 'expedite' mean?",
    options: [
      { label: "A", text: "Delay" },
      { label: "B", text: "Cancel" },
      { label: "C", text: "Complicate" },
      { label: "D", text: "Speed up" },
      { label: "E", text: "Ignore" },
    ],
    correctLabel: "D",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to CACOPHONOUS.",
    options: [
      { label: "A", text: "Discordant" },
      { label: "B", text: "Jarring" },
      { label: "C", text: "Harmonious" },
      { label: "D", text: "Noisy" },
      { label: "E", text: "Harsh" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "EULOGY is to PRAISE as DIATRIBE is to ___.",
    options: [
      { label: "A", text: "Compliment" },
      { label: "B", text: "Admiration" },
      { label: "C", text: "Criticism" },
      { label: "D", text: "Support" },
      { label: "E", text: "Agreement" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word means the same as LOQUACIOUS?",
    options: [
      { label: "A", text: "Quiet" },
      { label: "B", text: "Reserved" },
      { label: "C", text: "Talkative" },
      { label: "D", text: "Shy" },
      { label: "E", text: "Withdrawn" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "The historian's ___ account of the war drew on previously classified documents.",
    options: [
      { label: "A", text: "superficial" },
      { label: "B", text: "exhaustive" },
      { label: "C", text: "brief" },
      { label: "D", text: "cursory" },
      { label: "E", text: "incomplete" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to WEAK.",
    options: [
      { label: "A", text: "Feeble" },
      { label: "B", text: "Fragile" },
      { label: "C", text: "Powerful" },
      { label: "D", text: "Delicate" },
      { label: "E", text: "Frail" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "EAR is to HEAR as EYE is to ___.",
    options: [
      { label: "A", text: "Blink" },
      { label: "B", text: "See" },
      { label: "C", text: "Cry" },
      { label: "D", text: "Close" },
      { label: "E", text: "Wink" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word means the same as ANCIENT?",
    options: [
      { label: "A", text: "New" },
      { label: "B", text: "Modern" },
      { label: "C", text: "Old" },
      { label: "D", text: "Fresh" },
      { label: "E", text: "Current" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The negotiations reached an ___ when neither side would compromise.",
    options: [
      { label: "A", text: "agreement" },
      { label: "B", text: "impasse" },
      { label: "C", text: "conclusion" },
      { label: "D", text: "resolution" },
      { label: "E", text: "accord" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to ELOQUENT.",
    options: [
      { label: "A", text: "Articulate" },
      { label: "B", text: "Fluent" },
      { label: "C", text: "Inarticulate" },
      { label: "D", text: "Persuasive" },
      { label: "E", text: "Expressive" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "SYMPHONY is to MOVEMENTS as NOVEL is to ___.",
    options: [
      { label: "A", text: "Words" },
      { label: "B", text: "Chapters" },
      { label: "C", text: "Pages" },
      { label: "D", text: "Sentences" },
      { label: "E", text: "Letters" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "In the sentence 'Her risible performance had the audience in stitches,' what does 'risible' mean?",
    options: [
      { label: "A", text: "Tragic" },
      { label: "B", text: "Boring" },
      { label: "C", text: "Laughable" },
      { label: "D", text: "Serious" },
      { label: "E", text: "Moving" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "The team was ___ after winning the championship game.",
    options: [
      { label: "A", text: "defeated" },
      { label: "B", text: "sad" },
      { label: "C", text: "ecstatic" },
      { label: "D", text: "tired" },
      { label: "E", text: "bored" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to GARRULOUS.",
    options: [
      { label: "A", text: "Chatty" },
      { label: "B", text: "Wordy" },
      { label: "C", text: "Talkative" },
      { label: "D", text: "Reticent" },
      { label: "E", text: "Verbose" },
    ],
    correctLabel: "D",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Choose the word that is most OPPOSITE to LOUD.",
    options: [
      { label: "A", text: "Noisy" },
      { label: "B", text: "Quiet" },
      { label: "C", text: "Harsh" },
      { label: "D", text: "Sharp" },
      { label: "E", text: "Strong" },
    ],
    correctLabel: "B",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "DOCTOR is to HOSPITAL as TEACHER is to ___.",
    options: [
      { label: "A", text: "School" },
      { label: "B", text: "Student" },
      { label: "C", text: "Book" },
      { label: "D", text: "Desk" },
      { label: "E", text: "Chalk" },
    ],
    correctLabel: "A",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word means the same as HAPPY?",
    options: [
      { label: "A", text: "Sad" },
      { label: "B", text: "Angry" },
      { label: "C", text: "Joyful" },
      { label: "D", text: "Tired" },
      { label: "E", text: "Nervous" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as IMPECCABLE?",
    options: [
      { label: "A", text: "Flawed" },
      { label: "B", text: "Average" },
      { label: "C", text: "Faultless" },
      { label: "D", text: "Mediocre" },
      { label: "E", text: "Typical" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "The architect's ___ design won praise for balancing aesthetics with functionality.",
    options: [
      { label: "A", text: "clumsy" },
      { label: "B", text: "ugly" },
      { label: "C", text: "ingenious" },
      { label: "D", text: "boring" },
      { label: "E", text: "plain" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "In the sentence 'The proposal was met with tepid enthusiasm,' what does 'tepid' mean?",
    options: [
      { label: "A", text: "Passionate" },
      { label: "B", text: "Lukewarm" },
      { label: "C", text: "Extreme" },
      { label: "D", text: "Overwhelming" },
      { label: "E", text: "Intense" },
    ],
    correctLabel: "B",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word means the same as PELLUCID?",
    options: [
      { label: "A", text: "Murky" },
      { label: "B", text: "Opaque" },
      { label: "C", text: "Transparent" },
      { label: "D", text: "Dark" },
      { label: "E", text: "Cloudy" },
    ],
    correctLabel: "C",
    tags: ["synonym"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "STOIC is to EMOTION as ASCETIC is to ___.",
    options: [
      { label: "A", text: "Wealth" },
      { label: "B", text: "Luxury" },
      { label: "C", text: "Comfort" },
      { label: "D", text: "Power" },
      { label: "E", text: "Fame" },
    ],
    correctLabel: "B",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "The orator's speech was a ___ of rhetoric, designed to inflame passions rather than inform.",
    options: [
      { label: "A", text: "model" },
      { label: "B", text: "paroxysm" },
      { label: "C", text: "example" },
      { label: "D", text: "pinnacle" },
      { label: "E", text: "triumph" },
    ],
    correctLabel: "B",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "In the sentence 'The current in the river was very strong,' what does 'current' mean?",
    options: [
      { label: "A", text: "Present time" },
      { label: "B", text: "Electrical flow" },
      { label: "C", text: "Water movement" },
      { label: "D", text: "Popular trend" },
      { label: "E", text: "A type of fruit" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Choose the word that is most OPPOSITE to OSTENTATIOUS.",
    options: [
      { label: "A", text: "Flashy" },
      { label: "B", text: "Showy" },
      { label: "C", text: "Modest" },
      { label: "D", text: "Grand" },
      { label: "E", text: "Lavish" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "APPRENTICE is to MASTER as STUDENT is to ___.",
    options: [
      { label: "A", text: "Classroom" },
      { label: "B", text: "Textbook" },
      { label: "C", text: "Mentor" },
      { label: "D", text: "Desk" },
      { label: "E", text: "Homework" },
    ],
    correctLabel: "C",
    tags: ["analogy"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "The garden looked ___ after the gardener spent the whole day working on it.",
    options: [
      { label: "A", text: "neglected" },
      { label: "B", text: "dead" },
      { label: "C", text: "beautiful" },
      { label: "D", text: "messy" },
      { label: "E", text: "wild" },
    ],
    correctLabel: "C",
    tags: ["sentence-completion"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "In the sentence 'The company's Byzantine organizational structure confused new employees,' what does 'Byzantine' mean?",
    options: [
      { label: "A", text: "Simple" },
      { label: "B", text: "Modern" },
      { label: "C", text: "Extremely complex" },
      { label: "D", text: "Efficient" },
      { label: "E", text: "Transparent" },
    ],
    correctLabel: "C",
    tags: ["word-context"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Choose the word that is most OPPOSITE to MAGNANIMOUS.",
    options: [
      { label: "A", text: "Generous" },
      { label: "B", text: "Noble" },
      { label: "C", text: "Petty" },
      { label: "D", text: "Forgiving" },
      { label: "E", text: "Gracious" },
    ],
    correctLabel: "C",
    tags: ["antonym"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word means the same as UBIQUITOUS?",
    options: [
      { label: "A", text: "Rare" },
      { label: "B", text: "Everywhere" },
      { label: "C", text: "Hidden" },
      { label: "D", text: "Unique" },
      { label: "E", text: "Ancient" },
    ],
    correctLabel: "B",
    tags: ["synonym"],
  },
];
