type QuestionData = {
  category: "verbal" | "math_logic" | "spatial";
  difficulty: number;
  stem: string;
  options: { label: string; text: string }[];
  correctLabel: string;
  tags: string[];
};

// ═══════════════════════════════════════════════════════════════════════════════
// MISSING CCAT QUESTION TYPES
// - True / False / Uncertain  (verbal reasoning — 3 options)
// - Column Comparison / Attention to Detail (math_logic)
// - Word Comparison / Odd-Word-Out (verbal)
// - Syllogisms (math_logic)
// ═══════════════════════════════════════════════════════════════════════════════

export const additionalQuestions: QuestionData[] = [

  // ─── TRUE / FALSE / UNCERTAIN (50 questions) ──────────────────────────────
  // "If the first two statements are true, is the final statement true?"
  // Options: A. True  B. False  C. Uncertain

  // Easy (difficulty 1)
  {
    category: "verbal",
    difficulty: 1,
    stem: "If the first two statements are true, is the final statement true?\n\n• Sarah's mom has blonde hair.\n• Sarah's dad has blonde hair.\n• Sarah has blonde hair.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "If the first two statements are true, is the final statement true?\n\n• All dogs are animals.\n• All animals need water.\n• All dogs need water.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "If the first two statements are true, is the final statement true?\n\n• All roses are flowers.\n• Some flowers fade quickly.\n• Some roses fade quickly.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "If the first two statements are true, is the final statement true?\n\n• No fish can walk.\n• A salmon is a fish.\n• A salmon cannot walk.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "If the first two statements are true, is the final statement true?\n\n• All cats have tails.\n• Whiskers is a cat.\n• Whiskers has a tail.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "If the first two statements are true, is the final statement true?\n\n• All birds have feathers.\n• Penguins are birds.\n• Penguins have feathers.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "If the first two statements are true, is the final statement true?\n\n• Some fruits are sweet.\n• Lemons are fruits.\n• Lemons are sweet.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "If the first two statements are true, is the final statement true?\n\n• All squares have four equal sides.\n• This shape has four equal sides.\n• This shape is a square.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "If the first two statements are true, is the final statement true?\n\n• No reptiles have fur.\n• A lizard is a reptile.\n• A lizard does not have fur.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "If the first two statements are true, is the final statement true?\n\n• All teachers at Lincoln School have a degree.\n• Mrs. Garcia teaches at Lincoln School.\n• Mrs. Garcia has a degree.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },

  // Medium (difficulty 2)
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• All managers in the company have MBA degrees.\n• John works in the company.\n• John has an MBA degree.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• Every employee who completes training gets a certificate.\n• Maria completed her training last week.\n• Maria got a certificate.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• None of the applicants who scored below 70 were hired.\n• Tom scored 65.\n• Tom was not hired.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• All products sold in Store A come with a warranty.\n• The television was purchased at Store A.\n• The television came with a warranty.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• Only senior engineers can approve code merges.\n• Lisa approved a code merge yesterday.\n• Lisa is a senior engineer.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• All participants who arrived late were marked absent.\n• Kevin was marked absent.\n• Kevin arrived late.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• No one under 18 is allowed to drive.\n• Sarah is 16 years old.\n• Sarah is not allowed to drive.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• All members of the chess club are honor students.\n• No honor students have failed a class this year.\n• No members of the chess club have failed a class this year.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• All marathon runners train at least 4 days a week.\n• Alex trains 5 days a week.\n• Alex is a marathon runner.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• All packages over 10 kg require special handling.\n• This package weighs 8 kg.\n• This package does not require special handling.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• Every car in the lot has been inspected.\n• No uninspected cars can be sold.\n• Every car in the lot can be sold.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• All rooms on the 3rd floor have been renovated.\n• Room 305 is on the 3rd floor.\n• Room 305 has been renovated.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• All tickets for the concert are sold out.\n• Brian wants to attend the concert.\n• Brian cannot attend the concert.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• All employees who work overtime get paid extra.\n• None of the interns work overtime.\n• No interns get paid extra.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },

  // Hard (difficulty 3)
  {
    category: "verbal",
    difficulty: 3,
    stem: "If the first two statements are true, is the final statement true?\n\n• All graduates from Program X got jobs within 6 months.\n• Everyone who got a job within 6 months had a GPA above 3.0.\n• All graduates from Program X had a GPA above 3.0.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "If the first two statements are true, is the final statement true?\n\n• All premium members get free shipping.\n• Some premium members also get early access.\n• All people with free shipping are premium members.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "If the first two statements are true, is the final statement true?\n\n• All candidates who passed both interviews were given offers.\n• Rachel passed the first interview but was not given an offer.\n• Rachel did not pass the second interview.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "If the first two statements are true, is the final statement true?\n\n• No student who plagiarized passed the ethics course.\n• All students who passed the ethics course received a diploma.\n• Thomas did not receive a diploma, so he plagiarized.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "If the first two statements are true, is the final statement true?\n\n• No one who missed more than 3 classes passed the course.\n• Amy passed the course.\n• Amy missed fewer than 4 classes.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "If the first two statements are true, is the final statement true?\n\n• Only licensed professionals can prescribe medication.\n• Dr. Smith prescribed medication to a patient.\n• Dr. Smith is a licensed professional.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "If the first two statements are true, is the final statement true?\n\n• All houses on Elm Street were built before 1960.\n• No house built before 1960 has original central air conditioning.\n• The house at 45 Elm Street has central air conditioning that was added later.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "If the first two statements are true, is the final statement true?\n\n• All research papers submitted after the deadline were rejected.\n• Professor Lee's paper was rejected.\n• Professor Lee submitted the paper after the deadline.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "If the first two statements are true, is the final statement true?\n\n• All partners at the firm bill at least 2000 hours per year.\n• Associates bill between 1500 and 1900 hours.\n• Jennifer billed 2100 hours, so she is a partner.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "If the first two statements are true, is the final statement true?\n\n• All flights from Terminal A are international.\n• Some international flights require a visa.\n• All flights from Terminal A require a visa.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "If the first two statements are true, is the final statement true?\n\n• Only employees with security clearance can access Floor 5.\n• Everyone on Floor 5 has a keycard.\n• Mark has a keycard, so he has security clearance.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• No vegetarian dishes on the menu contain meat.\n• The pasta primavera is a vegetarian dish on the menu.\n• The pasta primavera does not contain meat.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "If the first two statements are true, is the final statement true?\n\n• All dogs bark.\n• Rex is a dog.\n• Rex barks.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "If the first two statements are true, is the final statement true?\n\n• All squares are rectangles.\n• All rectangles have four sides.\n• All squares have four sides.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• Some engineers in the team know Python.\n• All team members know Java.\n• Some engineers know both Python and Java.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "If the first two statements are true, is the final statement true?\n\n• All applicants with 5+ years of experience were shortlisted.\n• Some shortlisted applicants were invited for interviews.\n• Some applicants with 5+ years of experience were invited for interviews.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "If the first two statements are true, is the final statement true?\n\n• Every student in the class has a textbook.\n• Emma is a student in the class.\n• Emma has a textbook.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• Most people who exercise regularly are healthy.\n• Sam exercises regularly.\n• Sam is healthy.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "If the first two statements are true, is the final statement true?\n\n• All items in Warehouse B are insured.\n• Some insured items are fragile.\n• All items in Warehouse B are fragile.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• All children in the park are wearing helmets.\n• Tommy is in the park.\n• Tommy is wearing a helmet.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "If the first two statements are true, is the final statement true?\n\n• No one who failed the background check was hired.\n• All hired employees received a laptop.\n• David received a laptop, so he passed the background check.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "If the first two statements are true, is the final statement true?\n\n• All bikes have two wheels.\n• This vehicle has two wheels.\n• This vehicle is a bike.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "C",
    tags: ["true-false-uncertain"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If the first two statements are true, is the final statement true?\n\n• All books on the top shelf are hardcovers.\n• \"War and Peace\" is on the top shelf.\n• \"War and Peace\" is a hardcover.",
    options: [
      { label: "A", text: "True" },
      { label: "B", text: "False" },
      { label: "C", text: "Uncertain" },
    ],
    correctLabel: "A",
    tags: ["true-false-uncertain"],
  },

  // ─── COLUMN COMPARISON / ATTENTION TO DETAIL (30 questions) ───────────────
  // Compare left and right columns, count exact matches

  // Easy (difficulty 1)
  {
    category: "verbal",
    difficulty: 1,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) Stonebridge Investments → Stonebridge Investments\n2) Lakeside Consultants LLC → Lakeside Consultants LLC\n3) Pineview Medical Group → Pineview Medical Groups\n4) Valley Forge Realty → Valley Forge Reality\n5) Timberline Financial → Timberline Finance",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "B",
    tags: ["column-comparison"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) 847-392-5610 → 847-392-5610\n2) 312-558-7201 → 312-558-7201\n3) 630-441-8893 → 630-441-8893\n4) 773-209-6145 → 773-209-6154\n5) 219-887-3302 → 219-887-3302",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "D",
    tags: ["column-comparison"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) John Peterson → John Peterson\n2) Sarah Mitchell → Sara Mitchell\n3) David Thompson → David Thompson\n4) Lisa Rodriguez → Lisa Rodrigues\n5) Mark Williams → Mark Williams",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "C",
    tags: ["column-comparison"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) New York → New York\n2) Los Angeles → Los Angles\n3) Chicago → Chicago\n4) Houston → Huston\n5) Phoenix → Phoenix",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "C",
    tags: ["column-comparison"],
  },

  // Medium (difficulty 2)
  {
    category: "verbal",
    difficulty: 2,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) ACCT-78245-XKP → ACCT-78245-XKP\n2) INVS-93017-BRL → INVS-93017-BLR\n3) PRCH-44829-MNQ → PRCH-44829-MNQ\n4) RFND-61503-JHT → RFND-61503-JHT\n5) DPST-20876-WCF → DPST-20876-WFC",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "C",
    tags: ["column-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) Dr. Katherine M. Sullivan → Dr. Katherine M. Sullivan\n2) Prof. James L. Worthington → Prof. James L. Worthington\n3) Ms. Patricia A. Chen-Nakamura → Ms. Patricia A. Chen-Nakamura\n4) Mr. Robert E. Fitzgerald III → Mr. Robert E. Fitzgerald III\n5) Dr. Samantha R. Okonkwo-Patel → Dr. Samantha R. Okonkwo-Pattel",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "D",
    tags: ["column-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) 1247 W. Broadmoor Blvd → 1247 W. Broadmoor Blvd\n2) 892 N. Lakeshore Dr, Apt 15B → 892 N. Lakeshore Dr, Apt 15B\n3) 3506 E. Commonwealth Ave → 3506 E. Commonweath Ave\n4) 7741 S. Ridgewater Pkwy → 7741 S. Ridgewater Pkwy\n5) 2089 NW Hawthorn Ct, Ste 4 → 2089 NW Hawthorne Ct, Ste 4",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "C",
    tags: ["column-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) $12,487.93 → $12,487.93\n2) $8,391.07 → $8,391.70\n3) $45,216.58 → $45,216.58\n4) $3,904.62 → $3,904.62\n5) $67,832.41 → $67,823.41",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "C",
    tags: ["column-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) Mediterranean Sea → Mediterranean Sea\n2) Schwarzenegger → Schwarzenegger\n3) Albuquerque → Albequerque\n4) Liechtenstein → Liechtenstein\n5) Worcestershire → Worcestershire",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "D",
    tags: ["column-comparison"],
  },

  // Hard (difficulty 3)
  {
    category: "verbal",
    difficulty: 3,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) XK7-9P2-LM4-QBN-803 → XK7-9P2-LM4-QBN-803\n2) FJ3-8W6-RT1-YHK-502 → FJ3-8W6-RT1-YKH-502\n3) BV9-4D5-NP7-CSG-216 → BV9-4D5-NP7-CSG-216\n4) ML2-7X8-KQ3-WAT-941 → ML2-7X8-KQ3-WAT-941\n5) HS6-1G4-ZE9-DJR-758 → HS6-1G4-ZE9-DRJ-758",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "C",
    tags: ["column-comparison"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) Psych. Dept., Rm 412-B → Psych. Dept., Rm 412-B\n2) Biochem. Lab, Fl. 3, Ste 307-A → Biochem. Lab, Fl. 3, Ste 307-A\n3) Admin. Ofc., Bldg C, Rm 118 → Admin. Ofc., Bldg C, Rm 181\n4) Research Wing, Lvl 2, Bay 9 → Research Wing, Lvl 2, Bay 9\n5) Eng. Annex, Sec. D, Cube 44 → Eng. Annex, Sec. D, Cube 44",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "D",
    tags: ["column-comparison"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) ISBN 978-0-13-468599-1 → ISBN 978-0-13-468599-1\n2) ISBN 978-1-4919-5013-8 → ISBN 978-1-4919-5031-8\n3) ISBN 978-0-596-51774-8 → ISBN 978-0-596-51774-8\n4) ISBN 978-3-16-148410-0 → ISBN 978-3-16-148410-0\n5) ISBN 978-0-07-802215-7 → ISBN 978-0-07-802251-7",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "C",
    tags: ["column-comparison"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) jennifer.oconnor@westfield.edu → jennifer.oconnor@westfield.edu\n2) m.takahashi-jones@corp.co.jp → m.takahashi-jones@corp.co.jp\n3) dr.s.krishnamurthy@nhs.uk → dr.s.krishnamurthy@nhs.uk\n4) carlos.rodriguez.2@gmail.com → carlos.rodriquez.2@gmail.com\n5) p.van.der.berg@outlook.nl → p.van.der.berg@outlook.nl",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "D",
    tags: ["column-comparison"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) Apple → Apple\n2) Banana → Bannana\n3) Cherry → Cherry\n4) Mango → Mango\n5) Orange → Orange",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "D",
    tags: ["column-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) 04/15/1989 → 04/15/1989\n2) 11/23/1995 → 11/23/1995\n3) 08/07/2001 → 08/07/2010\n4) 02/29/2000 → 02/29/2000\n5) 12/31/2024 → 12/31/2024",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "D",
    tags: ["column-comparison"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "How many of the five items in the left-hand column are exactly the same as the corresponding entry in the right-hand column?\n\nLeft-Hand Column → Right-Hand Column\n1) Gewürztraminer → Gewürztraminer\n2) François Müller → Françios Müller\n3) São Paulo, Brasil → São Paulo, Brasil\n4) Résumé → Résumé\n5) naïve café → naïve café",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "D",
    tags: ["column-comparison"],
  },

  // ─── WORD COMPARISON / ODD-WORD-OUT (40 questions) ────────────────────────
  // Which word does NOT belong with the others?

  // Easy (difficulty 1)
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Apple" },
      { label: "B", text: "Banana" },
      { label: "C", text: "Carrot" },
      { label: "D", text: "Orange" },
      { label: "E", text: "Grape" },
    ],
    correctLabel: "C",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Piano" },
      { label: "B", text: "Guitar" },
      { label: "C", text: "Violin" },
      { label: "D", text: "Drum" },
      { label: "E", text: "Easel" },
    ],
    correctLabel: "E",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Dog" },
      { label: "B", text: "Cat" },
      { label: "C", text: "Hamster" },
      { label: "D", text: "Eagle" },
      { label: "E", text: "Rabbit" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Red" },
      { label: "B", text: "Blue" },
      { label: "C", text: "Green" },
      { label: "D", text: "Square" },
      { label: "E", text: "Yellow" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Shirt" },
      { label: "B", text: "Pants" },
      { label: "C", text: "Jacket" },
      { label: "D", text: "Socks" },
      { label: "E", text: "Sofa" },
    ],
    correctLabel: "E",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Jupiter" },
      { label: "B", text: "Mars" },
      { label: "C", text: "Venus" },
      { label: "D", text: "Moon" },
      { label: "E", text: "Saturn" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Monday" },
      { label: "B", text: "Wednesday" },
      { label: "C", text: "Friday" },
      { label: "D", text: "March" },
      { label: "E", text: "Sunday" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Hammer" },
      { label: "B", text: "Screwdriver" },
      { label: "C", text: "Wrench" },
      { label: "D", text: "Pliers" },
      { label: "E", text: "Lamp" },
    ],
    correctLabel: "E",
    tags: ["word-comparison"],
  },

  // Medium (difficulty 2)
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Whale" },
      { label: "B", text: "Dolphin" },
      { label: "C", text: "Shark" },
      { label: "D", text: "Seal" },
      { label: "E", text: "Walrus" },
    ],
    correctLabel: "C",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Inch" },
      { label: "B", text: "Foot" },
      { label: "C", text: "Yard" },
      { label: "D", text: "Pound" },
      { label: "E", text: "Mile" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Monarchy" },
      { label: "B", text: "Democracy" },
      { label: "C", text: "Republic" },
      { label: "D", text: "Dictatorship" },
      { label: "E", text: "Constitution" },
    ],
    correctLabel: "E",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Simile" },
      { label: "B", text: "Metaphor" },
      { label: "C", text: "Hyperbole" },
      { label: "D", text: "Paragraph" },
      { label: "E", text: "Alliteration" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Sonnet" },
      { label: "B", text: "Haiku" },
      { label: "C", text: "Limerick" },
      { label: "D", text: "Novel" },
      { label: "E", text: "Ballad" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Celsius" },
      { label: "B", text: "Fahrenheit" },
      { label: "C", text: "Kelvin" },
      { label: "D", text: "Kilogram" },
      { label: "E", text: "Rankine" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Surgeon" },
      { label: "B", text: "Dentist" },
      { label: "C", text: "Pharmacist" },
      { label: "D", text: "Architect" },
      { label: "E", text: "Pediatrician" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Telescope" },
      { label: "B", text: "Microscope" },
      { label: "C", text: "Periscope" },
      { label: "D", text: "Stethoscope" },
      { label: "E", text: "Kaleidoscope" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Evaporation" },
      { label: "B", text: "Condensation" },
      { label: "C", text: "Precipitation" },
      { label: "D", text: "Irrigation" },
      { label: "E", text: "Sublimation" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },

  // Hard (difficulty 3)
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Pragmatic" },
      { label: "B", text: "Practical" },
      { label: "C", text: "Realistic" },
      { label: "D", text: "Dogmatic" },
      { label: "E", text: "Sensible" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Allegory" },
      { label: "B", text: "Parable" },
      { label: "C", text: "Fable" },
      { label: "D", text: "Epitaph" },
      { label: "E", text: "Myth" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Photosynthesis" },
      { label: "B", text: "Respiration" },
      { label: "C", text: "Fermentation" },
      { label: "D", text: "Combustion" },
      { label: "E", text: "Osmosis" },
    ],
    correctLabel: "E",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Euphoria" },
      { label: "B", text: "Elation" },
      { label: "C", text: "Ecstasy" },
      { label: "D", text: "Apathy" },
      { label: "E", text: "Bliss" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Oligarchy" },
      { label: "B", text: "Plutocracy" },
      { label: "C", text: "Aristocracy" },
      { label: "D", text: "Bureaucracy" },
      { label: "E", text: "Theocracy" },
    ],
    correctLabel: "D",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Couplet" },
      { label: "B", text: "Quartet" },
      { label: "C", text: "Triplet" },
      { label: "D", text: "Quintet" },
      { label: "E", text: "Pamphlet" },
    ],
    correctLabel: "E",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which word does NOT belong with the others?",
    options: [
      { label: "A", text: "Addition" },
      { label: "B", text: "Subtraction" },
      { label: "C", text: "Division" },
      { label: "D", text: "Multiplication" },
      { label: "E", text: "Equation" },
    ],
    correctLabel: "E",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which pair of words is MOST similar in meaning?",
    options: [
      { label: "A", text: "Brave — Cowardly" },
      { label: "B", text: "Happy — Elated" },
      { label: "C", text: "Dark — Light" },
      { label: "D", text: "Fast — Slow" },
      { label: "E", text: "Hot — Cold" },
    ],
    correctLabel: "B",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which pair of words is MOST similar in meaning?",
    options: [
      { label: "A", text: "Hostile — Friendly" },
      { label: "B", text: "Rigid — Flexible" },
      { label: "C", text: "Candid — Frank" },
      { label: "D", text: "Ancient — Modern" },
      { label: "E", text: "Sparse — Dense" },
    ],
    correctLabel: "C",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which pair of words is MOST similar in meaning?",
    options: [
      { label: "A", text: "Ephemeral — Eternal" },
      { label: "B", text: "Meticulous — Careless" },
      { label: "C", text: "Gregarious — Sociable" },
      { label: "D", text: "Frugal — Extravagant" },
      { label: "E", text: "Benevolent — Malicious" },
    ],
    correctLabel: "C",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which pair of words is MOST similar in meaning?",
    options: [
      { label: "A", text: "Verbose — Concise" },
      { label: "B", text: "Obstinate — Stubborn" },
      { label: "C", text: "Lethargic — Energetic" },
      { label: "D", text: "Opaque — Transparent" },
      { label: "E", text: "Austere — Lavish" },
    ],
    correctLabel: "B",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which pair of words is MOST similar in meaning?",
    options: [
      { label: "A", text: "Abundant — Scarce" },
      { label: "B", text: "Novel — Ordinary" },
      { label: "C", text: "Diligent — Industrious" },
      { label: "D", text: "Tranquil — Turbulent" },
      { label: "E", text: "Bold — Timid" },
    ],
    correctLabel: "C",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which pair of words is MOST similar in meaning?",
    options: [
      { label: "A", text: "Big — Small" },
      { label: "B", text: "Quick — Fast" },
      { label: "C", text: "Up — Down" },
      { label: "D", text: "Hot — Cold" },
      { label: "E", text: "Old — New" },
    ],
    correctLabel: "B",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which pair of words is MOST opposite in meaning?",
    options: [
      { label: "A", text: "Prudent — Careful" },
      { label: "B", text: "Affluent — Impoverished" },
      { label: "C", text: "Candid — Honest" },
      { label: "D", text: "Diligent — Hardworking" },
      { label: "E", text: "Benign — Gentle" },
    ],
    correctLabel: "B",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which pair of words is MOST opposite in meaning?",
    options: [
      { label: "A", text: "Generous — Kind" },
      { label: "B", text: "Expand — Contract" },
      { label: "C", text: "Happy — Joyful" },
      { label: "D", text: "Bright — Luminous" },
      { label: "E", text: "Strong — Powerful" },
    ],
    correctLabel: "B",
    tags: ["word-comparison"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which pair of words is MOST opposite in meaning?",
    options: [
      { label: "A", text: "Laconic — Verbose" },
      { label: "B", text: "Astute — Shrewd" },
      { label: "C", text: "Arduous — Difficult" },
      { label: "D", text: "Resilient — Tough" },
      { label: "E", text: "Pragmatic — Practical" },
    ],
    correctLabel: "A",
    tags: ["word-comparison"],
  },

  // ─── SYLLOGISMS (20 questions) ────────────────────────────────────────────

  {
    category: "math_logic",
    difficulty: 1,
    stem: "All teachers are graduates. All graduates are educated. Therefore:",
    options: [
      { label: "A", text: "All teachers are educated" },
      { label: "B", text: "All educated people are teachers" },
      { label: "C", text: "Some graduates are not teachers" },
      { label: "D", text: "No teachers are educated" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "A",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "All metals conduct electricity. Copper is a metal. Therefore:",
    options: [
      { label: "A", text: "Copper does not conduct electricity" },
      { label: "B", text: "Copper conducts electricity" },
      { label: "C", text: "All things that conduct electricity are copper" },
      { label: "D", text: "Some metals do not conduct electricity" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "B",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "No insects are mammals. All bees are insects. Therefore:",
    options: [
      { label: "A", text: "Some bees are mammals" },
      { label: "B", text: "All mammals are insects" },
      { label: "C", text: "No bees are mammals" },
      { label: "D", text: "Some insects are mammals" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "C",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "All cars have engines. All engines need fuel. Therefore:",
    options: [
      { label: "A", text: "All cars need fuel" },
      { label: "B", text: "Some engines are not in cars" },
      { label: "C", text: "No cars need fuel" },
      { label: "D", text: "All fuel is for cars" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "A",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "All roses are flowers. Some flowers fade quickly. Therefore:",
    options: [
      { label: "A", text: "All roses fade quickly" },
      { label: "B", text: "No roses fade quickly" },
      { label: "C", text: "Some roses may fade quickly" },
      { label: "D", text: "All flowers are roses" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "C",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "No politicians are trustworthy. All senators are politicians. Therefore:",
    options: [
      { label: "A", text: "Some senators are trustworthy" },
      { label: "B", text: "No senators are trustworthy" },
      { label: "C", text: "All trustworthy people are senators" },
      { label: "D", text: "Some politicians are senators" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "B",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "All lawyers passed the bar exam. Some people who passed the bar exam work in government. Therefore:",
    options: [
      { label: "A", text: "All lawyers work in government" },
      { label: "B", text: "No lawyers work in government" },
      { label: "C", text: "Some lawyers may work in government" },
      { label: "D", text: "All government workers are lawyers" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "C",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "All mammals breathe air. No fish breathe air. Therefore:",
    options: [
      { label: "A", text: "No fish are mammals" },
      { label: "B", text: "Some fish are mammals" },
      { label: "C", text: "All air-breathers are mammals" },
      { label: "D", text: "Some mammals are fish" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "A",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Some doctors are researchers. All researchers publish papers. Therefore:",
    options: [
      { label: "A", text: "All doctors publish papers" },
      { label: "B", text: "Some doctors publish papers" },
      { label: "C", text: "No doctors publish papers" },
      { label: "D", text: "All people who publish papers are doctors" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "B",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "All X are Y. No Y are Z. Some Z are W. Therefore:",
    options: [
      { label: "A", text: "No X are Z" },
      { label: "B", text: "All W are X" },
      { label: "C", text: "Some X are W" },
      { label: "D", text: "All Z are X" },
      { label: "E", text: "Some Y are W" },
    ],
    correctLabel: "A",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "No A are B. All B are C. Some C are D. Therefore:",
    options: [
      { label: "A", text: "No A are C" },
      { label: "B", text: "Some D are B" },
      { label: "C", text: "Some C are not A" },
      { label: "D", text: "All D are A" },
      { label: "E", text: "All A are D" },
    ],
    correctLabel: "C",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "All managers are leaders. Some leaders are not effective communicators. All effective communicators are persuasive. Therefore:",
    options: [
      { label: "A", text: "All managers are persuasive" },
      { label: "B", text: "Some managers may not be effective communicators" },
      { label: "C", text: "No leaders are persuasive" },
      { label: "D", text: "All persuasive people are managers" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "B",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Some P are Q. All Q are R. No R are S. Therefore:",
    options: [
      { label: "A", text: "Some P are not S" },
      { label: "B", text: "All P are S" },
      { label: "C", text: "No P are R" },
      { label: "D", text: "All S are P" },
      { label: "E", text: "Some R are P" },
    ],
    correctLabel: "A",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "All CEOs are decision-makers. All decision-makers face risks. Some risk-takers are innovators. Therefore:",
    options: [
      { label: "A", text: "All CEOs are innovators" },
      { label: "B", text: "All CEOs face risks" },
      { label: "C", text: "No decision-makers are innovators" },
      { label: "D", text: "Some innovators are CEOs" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "B",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "All smartphones have screens. Some screens are OLED. Therefore:",
    options: [
      { label: "A", text: "All smartphones have OLED screens" },
      { label: "B", text: "No smartphones have OLED screens" },
      { label: "C", text: "Some smartphones may have OLED screens" },
      { label: "D", text: "All OLED screens are in smartphones" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "C",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "All chefs can cook. Some people who can cook are nutritionists. No nutritionists recommend junk food. Therefore:",
    options: [
      { label: "A", text: "No chefs recommend junk food" },
      { label: "B", text: "Some chefs are nutritionists" },
      { label: "C", text: "All nutritionists are chefs" },
      { label: "D", text: "Some people who can cook do not recommend junk food" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "D",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "All licensed drivers passed a driving test. No one under 16 can take a driving test. Alex is 14. Therefore:",
    options: [
      { label: "A", text: "Alex is a licensed driver" },
      { label: "B", text: "Alex cannot be a licensed driver" },
      { label: "C", text: "Alex will never be a licensed driver" },
      { label: "D", text: "Alex failed the driving test" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "B",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "Some athletes are tall. All basketball players are athletes. Therefore:",
    options: [
      { label: "A", text: "All basketball players are tall" },
      { label: "B", text: "Some basketball players may be tall" },
      { label: "C", text: "No basketball players are tall" },
      { label: "D", text: "All tall people are basketball players" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "B",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "All planets orbit a star. Earth is a planet. The Sun is a star. Therefore:",
    options: [
      { label: "A", text: "Earth orbits the Sun" },
      { label: "B", text: "Earth orbits a star" },
      { label: "C", text: "All stars have planets" },
      { label: "D", text: "The Sun orbits Earth" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "B",
    tags: ["syllogism"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "All prime numbers greater than 2 are odd. 7 is a prime number greater than 2. Therefore:",
    options: [
      { label: "A", text: "7 is even" },
      { label: "B", text: "7 is odd" },
      { label: "C", text: "All odd numbers are prime" },
      { label: "D", text: "2 is odd" },
      { label: "E", text: "None of these conclusions follow" },
    ],
    correctLabel: "B",
    tags: ["syllogism"],
  },

  // ─── SPELLING / DETAIL (10 questions) ─────────────────────────────────────
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which of these words is spelled INCORRECTLY?",
    options: [
      { label: "A", text: "Accommodate" },
      { label: "B", text: "Necessary" },
      { label: "C", text: "Occurence" },
      { label: "D", text: "Separate" },
      { label: "E", text: "Definitely" },
    ],
    correctLabel: "C",
    tags: ["attention-to-detail"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "Which of these words is spelled INCORRECTLY?",
    options: [
      { label: "A", text: "Surveillance" },
      { label: "B", text: "Bureaucracy" },
      { label: "C", text: "Conscientious" },
      { label: "D", text: "Mischievious" },
      { label: "E", text: "Recommendation" },
    ],
    correctLabel: "D",
    tags: ["attention-to-detail"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "Which of these words is spelled INCORRECTLY?",
    options: [
      { label: "A", text: "Acquiesce" },
      { label: "B", text: "Supercede" },
      { label: "C", text: "Liaison" },
      { label: "D", text: "Hemorrhage" },
      { label: "E", text: "Sacrilegious" },
    ],
    correctLabel: "B",
    tags: ["attention-to-detail"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "How many of the following words are spelled correctly?\n\nReceive, Beleive, Achieve, Decieve, Conceive",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
      { label: "E", text: "5" },
    ],
    correctLabel: "C",
    tags: ["attention-to-detail"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If these items are sorted alphabetically, which comes THIRD?\n\nPerimeter, Peninsula, Pendulum, Penetrate, Penalty",
    options: [
      { label: "A", text: "Perimeter" },
      { label: "B", text: "Peninsula" },
      { label: "C", text: "Pendulum" },
      { label: "D", text: "Penetrate" },
      { label: "E", text: "Penalty" },
    ],
    correctLabel: "D",
    tags: ["attention-to-detail"],
  },
  {
    category: "verbal",
    difficulty: 2,
    stem: "If these names are sorted alphabetically by LAST name, which would come FIRST?\n\n1) Patricia Gonzalez\n2) Robert Franklin\n3) Maria Gutierrez\n4) James Ferguson\n5) Linda Gallagher",
    options: [
      { label: "A", text: "Patricia Gonzalez" },
      { label: "B", text: "Robert Franklin" },
      { label: "C", text: "Maria Gutierrez" },
      { label: "D", text: "James Ferguson" },
      { label: "E", text: "Linda Gallagher" },
    ],
    correctLabel: "D",
    tags: ["attention-to-detail"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "A shipping manifest lists: 24 crates × $189.50 each = $4,548.00\n\nIs this calculation correct?",
    options: [
      { label: "A", text: "Yes, the calculation is correct" },
      { label: "B", text: "No, the correct total is $4,458.00" },
      { label: "C", text: "No, the correct total is $4,538.00" },
      { label: "D", text: "No, the correct total is $4,648.00" },
      { label: "E", text: "No, the correct total is $4,488.00" },
    ],
    correctLabel: "A",
    tags: ["attention-to-detail"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which of the following codes is DIFFERENT from the others?",
    options: [
      { label: "A", text: "XK7-9P2-LM4" },
      { label: "B", text: "XK7-9P2-LM4" },
      { label: "C", text: "XK7-9P2-LM4" },
      { label: "D", text: "XK7-9P2-ML4" },
      { label: "E", text: "XK7-9P2-LM4" },
    ],
    correctLabel: "D",
    tags: ["attention-to-detail"],
  },
  {
    category: "verbal",
    difficulty: 1,
    stem: "Which of these phone numbers is DIFFERENT from the others?",
    options: [
      { label: "A", text: "(555) 867-5309" },
      { label: "B", text: "(555) 867-5309" },
      { label: "C", text: "(555) 867-5309" },
      { label: "D", text: "(555) 867-5390" },
      { label: "E", text: "(555) 867-5309" },
    ],
    correctLabel: "D",
    tags: ["attention-to-detail"],
  },
  {
    category: "verbal",
    difficulty: 3,
    stem: "A form requires dates in MM/DD/YYYY format. Which entry is INCORRECT?",
    options: [
      { label: "A", text: "01/15/2024" },
      { label: "B", text: "12/31/2023" },
      { label: "C", text: "06/30/2024" },
      { label: "D", text: "2024/03/15" },
      { label: "E", text: "09/01/2024" },
    ],
    correctLabel: "D",
    tags: ["attention-to-detail"],
  },

  // ─── SEATING / ORDERING ARRANGEMENTS (15 questions) ───────────────────────
  // Logic puzzles about positions, order, and seating

  {
    category: "math_logic",
    difficulty: 2,
    stem: "Nina, Oliver, Paige, Quinn, and Ryan are seated in a row.\n\n• Nina is sitting to the right of Oliver.\n• Ryan is sitting immediately to the left of Paige.\n• Quinn is seated first in line.\n\nIf Oliver is seated fourth in line, which of the following can be true about Paige's position?",
    options: [
      { label: "A", text: "Paige is first" },
      { label: "B", text: "Paige is second" },
      { label: "C", text: "Paige is third" },
      { label: "D", text: "Paige is fourth" },
      { label: "E", text: "Paige is last" },
    ],
    correctLabel: "C",
    tags: ["seating-arrangement"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "Five people — Amy, Ben, Cara, Dan, and Eve — are standing in a line.\n\n• Amy is first.\n• Ben is last.\n• Cara is immediately after Amy.\n\nWhat position is Cara in?",
    options: [
      { label: "A", text: "First" },
      { label: "B", text: "Second" },
      { label: "C", text: "Third" },
      { label: "D", text: "Fourth" },
      { label: "E", text: "Fifth" },
    ],
    correctLabel: "B",
    tags: ["seating-arrangement"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Six students — A, B, C, D, E, and F — are seated around a circular table.\n\n• A sits opposite D.\n• B sits to the left of A.\n• C sits opposite F.\n\nWho sits to the right of D?",
    options: [
      { label: "A", text: "A" },
      { label: "B", text: "B" },
      { label: "C", text: "C" },
      { label: "D", text: "E" },
      { label: "E", text: "F" },
    ],
    correctLabel: "E",
    tags: ["seating-arrangement"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Four runners finished a race. Their names are Tom, Uma, Vic, and Wendy.\n\n• Tom finished before Wendy.\n• Vic finished after Uma but before Tom.\n• Uma finished first.\n\nIn what position did Tom finish?",
    options: [
      { label: "A", text: "First" },
      { label: "B", text: "Second" },
      { label: "C", text: "Third" },
      { label: "D", text: "Fourth" },
      { label: "E", text: "Cannot be determined" },
    ],
    correctLabel: "C",
    tags: ["seating-arrangement"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Seven employees — G, H, I, J, K, L, M — sit in a row of seven desks.\n\n• G sits at one end.\n• J sits exactly in the middle.\n• H sits immediately to the right of G.\n• L sits immediately to the left of M.\n• K does not sit next to J.\n\nWhich of the following MUST be true?",
    options: [
      { label: "A", text: "H sits second from the left" },
      { label: "B", text: "I sits at the other end" },
      { label: "C", text: "K sits next to G" },
      { label: "D", text: "L sits in position 5 or 6" },
      { label: "E", text: "M sits at one end" },
    ],
    correctLabel: "A",
    tags: ["seating-arrangement"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "Three books — Math, Science, and English — are stacked on top of each other.\n\n• Math is not on top.\n• Science is below English.\n\nWhich book is on top?",
    options: [
      { label: "A", text: "Math" },
      { label: "B", text: "Science" },
      { label: "C", text: "English" },
      { label: "D", text: "Cannot be determined" },
      { label: "E", text: "None of the above" },
    ],
    correctLabel: "C",
    tags: ["seating-arrangement"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Five houses are in a row, numbered 1 through 5 from left to right. Each house is a different color: Red, Blue, Green, Yellow, White.\n\n• The Red house is to the left of the Blue house.\n• The Green house is house number 3.\n• The Yellow house is at one end.\n• The White house is next to the Green house.\n\nWhich house is Blue?",
    options: [
      { label: "A", text: "House 1" },
      { label: "B", text: "House 2" },
      { label: "C", text: "House 3" },
      { label: "D", text: "House 4" },
      { label: "E", text: "House 5" },
    ],
    correctLabel: "E",
    tags: ["seating-arrangement"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Six people — P, Q, R, S, T, U — are seated in a row.\n\n• P is not at either end.\n• Q is three seats away from R.\n• S is immediately to the right of P.\n• T is at one end.\n• U is between Q and R.\n\nWhat position is P in?",
    options: [
      { label: "A", text: "Second" },
      { label: "B", text: "Third" },
      { label: "C", text: "Fourth" },
      { label: "D", text: "Fifth" },
      { label: "E", text: "Cannot be determined" },
    ],
    correctLabel: "B",
    tags: ["seating-arrangement"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "Alice, Bob, and Charlie are standing in a line at the store.\n\n• Alice is not last.\n• Charlie is ahead of Bob.\n\nWhat is the order from first to last?",
    options: [
      { label: "A", text: "Alice, Charlie, Bob" },
      { label: "B", text: "Charlie, Alice, Bob" },
      { label: "C", text: "Charlie, Bob, Alice" },
      { label: "D", text: "Alice, Bob, Charlie" },
      { label: "E", text: "Cannot be determined" },
    ],
    correctLabel: "E",
    tags: ["seating-arrangement"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Eight athletes — A through H — finish a race. No ties occurred.\n\n• A finished before B but after C.\n• D finished immediately after E.\n• F finished last.\n• G finished before C.\n• H finished before G.\n\nWhat is the earliest position B could have finished?",
    options: [
      { label: "A", text: "Third" },
      { label: "B", text: "Fourth" },
      { label: "C", text: "Fifth" },
      { label: "D", text: "Sixth" },
      { label: "E", text: "Seventh" },
    ],
    correctLabel: "C",
    tags: ["seating-arrangement"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Five friends — Mia, Noah, Olivia, Peter, and Quinn — are seated in a cinema row.\n\n• Mia is at one end.\n• Noah is next to Olivia.\n• Peter is not next to Mia.\n• Quinn is in the middle seat.\n\nWho is sitting next to Mia?",
    options: [
      { label: "A", text: "Noah" },
      { label: "B", text: "Olivia" },
      { label: "C", text: "Peter" },
      { label: "D", text: "Quinn" },
      { label: "E", text: "Noah or Olivia" },
    ],
    correctLabel: "E",
    tags: ["seating-arrangement"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A meeting has 5 people — V, W, X, Y, Z — sitting around a circular table.\n\n• V is between W and X.\n• Y is not next to W.\n• Z is next to Y.\n\nWho is sitting directly across from W?",
    options: [
      { label: "A", text: "V" },
      { label: "B", text: "X" },
      { label: "C", text: "Y" },
      { label: "D", text: "Z" },
      { label: "E", text: "Cannot be determined" },
    ],
    correctLabel: "C",
    tags: ["seating-arrangement"],
  },

  // ─── LETTER SERIES (15 questions) ─────────────────────────────────────────
  // Find the next group of letters in the series

  {
    category: "math_logic",
    difficulty: 1,
    stem: "What would be the next group of letters in the following series?\n\ncst ... dtu ... euv ... fvw ... ?",
    options: [
      { label: "A", text: "gwx" },
      { label: "B", text: "hwx" },
      { label: "C", text: "gxy" },
      { label: "D", text: "gwy" },
      { label: "E", text: "hyw" },
    ],
    correctLabel: "A",
    tags: ["letter-series"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What would be the next group of letters in the following series?\n\nab ... cd ... ef ... gh ... ?",
    options: [
      { label: "A", text: "hi" },
      { label: "B", text: "ij" },
      { label: "C", text: "jk" },
      { label: "D", text: "ik" },
      { label: "E", text: "hj" },
    ],
    correctLabel: "B",
    tags: ["letter-series"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What would be the next group of letters in the following series?\n\naz ... by ... cx ... dw ... ?",
    options: [
      { label: "A", text: "eu" },
      { label: "B", text: "ew" },
      { label: "C", text: "ev" },
      { label: "D", text: "fx" },
      { label: "E", text: "fv" },
    ],
    correctLabel: "C",
    tags: ["letter-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What would be the next group of letters in the following series?\n\nace ... bdf ... ceg ... dfh ... ?",
    options: [
      { label: "A", text: "egi" },
      { label: "B", text: "efg" },
      { label: "C", text: "egh" },
      { label: "D", text: "fgi" },
      { label: "E", text: "fhi" },
    ],
    correctLabel: "A",
    tags: ["letter-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What would be the next group of letters in the following series?\n\nza ... yb ... xc ... wd ... ?",
    options: [
      { label: "A", text: "ue" },
      { label: "B", text: "ve" },
      { label: "C", text: "vf" },
      { label: "D", text: "xe" },
      { label: "E", text: "we" },
    ],
    correctLabel: "B",
    tags: ["letter-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What would be the next group of letters in the following series?\n\nabc ... bce ... ceg ... dgi ... ?",
    options: [
      { label: "A", text: "ehk" },
      { label: "B", text: "eik" },
      { label: "C", text: "fik" },
      { label: "D", text: "ehj" },
      { label: "E", text: "eij" },
    ],
    correctLabel: "B",
    tags: ["letter-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What would be the next group of letters in the following series?\n\nAZ ... CX ... EV ... GT ... ?",
    options: [
      { label: "A", text: "HR" },
      { label: "B", text: "IS" },
      { label: "C", text: "IR" },
      { label: "D", text: "HS" },
      { label: "E", text: "JS" },
    ],
    correctLabel: "C",
    tags: ["letter-series"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What would be the next group of letters in the following series?\n\nabd ... bce ... cdf ... deg ... ?",
    options: [
      { label: "A", text: "efi" },
      { label: "B", text: "efh" },
      { label: "C", text: "egh" },
      { label: "D", text: "dfh" },
      { label: "E", text: "fgh" },
    ],
    correctLabel: "B",
    tags: ["letter-series"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What would be the next group of letters in the following series?\n\nACF ... BDG ... CEH ... DFI ... ?",
    options: [
      { label: "A", text: "EGJ" },
      { label: "B", text: "EGK" },
      { label: "C", text: "FHK" },
      { label: "D", text: "EHJ" },
      { label: "E", text: "FGJ" },
    ],
    correctLabel: "A",
    tags: ["letter-series"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What would be the next letter in the following series?\n\nA ... C ... E ... G ... ?",
    options: [
      { label: "A", text: "H" },
      { label: "B", text: "I" },
      { label: "C", text: "J" },
      { label: "D", text: "K" },
      { label: "E", text: "L" },
    ],
    correctLabel: "B",
    tags: ["letter-series"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "What would be the next group of letters in the following series?\n\nmno ... lmn ... klm ... jkl ... ?",
    options: [
      { label: "A", text: "ijk" },
      { label: "B", text: "hij" },
      { label: "C", text: "jkl" },
      { label: "D", text: "hik" },
      { label: "E", text: "ghi" },
    ],
    correctLabel: "A",
    tags: ["letter-series"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What would be the next group of letters in the following series?\n\naaa ... bbb ... ddd ... ggg ... ?",
    options: [
      { label: "A", text: "hhh" },
      { label: "B", text: "jjj" },
      { label: "C", text: "kkk" },
      { label: "D", text: "lll" },
      { label: "E", text: "iii" },
    ],
    correctLabel: "C",
    tags: ["letter-series"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What would be the next group of letters in the following series?\n\nZA ... YB ... XC ... WD ... ?",
    options: [
      { label: "A", text: "UE" },
      { label: "B", text: "VE" },
      { label: "C", text: "VF" },
      { label: "D", text: "UF" },
      { label: "E", text: "WE" },
    ],
    correctLabel: "B",
    tags: ["letter-series"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "What would be the next letter in the following series?\n\nZ ... X ... V ... T ... ?",
    options: [
      { label: "A", text: "S" },
      { label: "B", text: "R" },
      { label: "C", text: "Q" },
      { label: "D", text: "P" },
      { label: "E", text: "O" },
    ],
    correctLabel: "B",
    tags: ["letter-series"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "What would be the next group of letters in the following series?\n\nABC ... ACE ... AEG ... AGI ... ?",
    options: [
      { label: "A", text: "AIK" },
      { label: "B", text: "AHJ" },
      { label: "C", text: "AHK" },
      { label: "D", text: "AIJ" },
      { label: "E", text: "AJK" },
    ],
    correctLabel: "A",
    tags: ["letter-series"],
  },

  // ─── GRAPH / DATA INTERPRETATION (15 questions) ───────────────────────────
  // Reading data from described charts and graphs

  {
    category: "math_logic",
    difficulty: 1,
    stem: "A line graph shows website traffic over a week:\n\nMon: 10,000 | Tue: 15,000 | Wed: 25,000 | Thu: 40,000 | Fri: 20,000 | Sat: 5,000 | Sun: 10,000\n\nWhat is the difference in thousands of visitors between the day with the highest traffic and the day with the lowest traffic?",
    options: [
      { label: "A", text: "20" },
      { label: "B", text: "25" },
      { label: "C", text: "30" },
      { label: "D", text: "35" },
      { label: "E", text: "40" },
    ],
    correctLabel: "D",
    tags: ["graph-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A bar chart shows quarterly sales:\n\nQ1: $120K | Q2: $150K | Q3: $180K | Q4: $200K\n\nWhat is the total annual sales?",
    options: [
      { label: "A", text: "$600K" },
      { label: "B", text: "$620K" },
      { label: "C", text: "$650K" },
      { label: "D", text: "$680K" },
      { label: "E", text: "$700K" },
    ],
    correctLabel: "C",
    tags: ["graph-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A pie chart shows a company's expenses:\n\nSalaries: 40% | Rent: 25% | Marketing: 15% | Supplies: 10% | Other: 10%\n\nIf total expenses are $500,000, how much is spent on Rent and Marketing combined?",
    options: [
      { label: "A", text: "$150,000" },
      { label: "B", text: "$175,000" },
      { label: "C", text: "$200,000" },
      { label: "D", text: "$225,000" },
      { label: "E", text: "$250,000" },
    ],
    correctLabel: "C",
    tags: ["graph-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Monthly revenue data for two products:\n\nProduct A: Jan $30K, Feb $35K, Mar $40K, Apr $45K\nProduct B: Jan $50K, Feb $45K, Mar $40K, Apr $35K\n\nIn which month did both products have equal revenue?",
    options: [
      { label: "A", text: "January" },
      { label: "B", text: "February" },
      { label: "C", text: "March" },
      { label: "D", text: "April" },
      { label: "E", text: "They never had equal revenue" },
    ],
    correctLabel: "C",
    tags: ["graph-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Employee count by department:\n\nEngineering: 45 | Sales: 30 | Marketing: 20 | HR: 10 | Finance: 15\n\nWhat percentage of employees work in Engineering?",
    options: [
      { label: "A", text: "30%" },
      { label: "B", text: "33%" },
      { label: "C", text: "37.5%" },
      { label: "D", text: "40%" },
      { label: "E", text: "45%" },
    ],
    correctLabel: "C",
    tags: ["graph-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Sales data for 3 regions over 4 quarters (in $M):\n\nNorth: Q1=2.0, Q2=2.5, Q3=3.0, Q4=3.5\nSouth: Q1=1.5, Q2=2.0, Q3=2.5, Q4=3.0\nWest: Q1=3.0, Q2=2.5, Q3=2.0, Q4=1.5\n\nWhich region showed the greatest percentage increase from Q1 to Q4?",
    options: [
      { label: "A", text: "North" },
      { label: "B", text: "South" },
      { label: "C", text: "West" },
      { label: "D", text: "North and South tied" },
      { label: "E", text: "All three showed equal change" },
    ],
    correctLabel: "B",
    tags: ["graph-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A table shows test scores for 5 students:\n\nAlice: 85 | Bob: 72 | Carol: 91 | Dave: 68 | Eve: 79\n\nWhat is the average score?",
    options: [
      { label: "A", text: "77" },
      { label: "B", text: "78" },
      { label: "C", text: "79" },
      { label: "D", text: "80" },
      { label: "E", text: "81" },
    ],
    correctLabel: "C",
    tags: ["graph-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Production data (units per day):\n\nWeek 1: Mon 100, Tue 120, Wed 110, Thu 130, Fri 90\nWeek 2: Mon 110, Tue 130, Wed 120, Thu 140, Fri 100\n\nWhat was the percentage increase in total weekly production from Week 1 to Week 2?",
    options: [
      { label: "A", text: "Approximately 5%" },
      { label: "B", text: "Approximately 9%" },
      { label: "C", text: "Approximately 12%" },
      { label: "D", text: "Approximately 15%" },
      { label: "E", text: "Approximately 18%" },
    ],
    correctLabel: "B",
    tags: ["graph-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "A stacked bar chart shows device usage for a website:\n\n2022: Desktop 60%, Mobile 30%, Tablet 10%\n2023: Desktop 45%, Mobile 45%, Tablet 10%\n\nIf the site had 200,000 visitors in 2022 and 300,000 in 2023, how many MORE mobile visitors were there in 2023 than 2022?",
    options: [
      { label: "A", text: "55,000" },
      { label: "B", text: "65,000" },
      { label: "C", text: "75,000" },
      { label: "D", text: "85,000" },
      { label: "E", text: "95,000" },
    ],
    correctLabel: "C",
    tags: ["graph-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Budget allocation (in thousands):\n\n2023: R&D $400, Marketing $300, Operations $250, Admin $150\n2024: R&D $500, Marketing $350, Operations $200, Admin $150\n\nWhich category showed the largest absolute increase from 2023 to 2024?",
    options: [
      { label: "A", text: "R&D" },
      { label: "B", text: "Marketing" },
      { label: "C", text: "Operations" },
      { label: "D", text: "Admin" },
      { label: "E", text: "R&D and Marketing tied" },
    ],
    correctLabel: "A",
    tags: ["graph-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Monthly customer complaints:\n\nJan: 45 | Feb: 38 | Mar: 52 | Apr: 41 | May: 35 | Jun: 29\n\nWhat is the trend from January to June?",
    options: [
      { label: "A", text: "Steadily increasing" },
      { label: "B", text: "Steadily decreasing" },
      { label: "C", text: "Generally decreasing with a spike in March" },
      { label: "D", text: "No clear trend" },
      { label: "E", text: "Increasing then decreasing" },
    ],
    correctLabel: "C",
    tags: ["graph-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 1,
    stem: "A store tracks daily ice cream sales:\n\nMon: 50 | Tue: 60 | Wed: 55 | Thu: 70 | Fri: 80 | Sat: 120 | Sun: 100\n\nOn which day were sales closest to the weekly average?",
    options: [
      { label: "A", text: "Monday" },
      { label: "B", text: "Wednesday" },
      { label: "C", text: "Thursday" },
      { label: "D", text: "Friday" },
      { label: "E", text: "Sunday" },
    ],
    correctLabel: "D",
    tags: ["graph-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "Conversion rates by marketing channel:\n\nEmail: 2,000 clicks, 120 conversions\nSocial Media: 5,000 clicks, 200 conversions\nSearch Ads: 3,000 clicks, 210 conversions\nDirect: 1,000 clicks, 90 conversions\n\nWhich channel has the highest conversion rate?",
    options: [
      { label: "A", text: "Email" },
      { label: "B", text: "Social Media" },
      { label: "C", text: "Search Ads" },
      { label: "D", text: "Direct" },
      { label: "E", text: "Email and Search Ads tied" },
    ],
    correctLabel: "D",
    tags: ["graph-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 2,
    stem: "Student enrollment by year:\n\n2019: 1,200 | 2020: 1,100 | 2021: 950 | 2022: 1,050 | 2023: 1,300\n\nBetween which two consecutive years was the largest change in enrollment?",
    options: [
      { label: "A", text: "2019 to 2020" },
      { label: "B", text: "2020 to 2021" },
      { label: "C", text: "2021 to 2022" },
      { label: "D", text: "2022 to 2023" },
      { label: "E", text: "2019 to 2020 and 2022 to 2023 tied" },
    ],
    correctLabel: "D",
    tags: ["graph-interpretation"],
  },
  {
    category: "math_logic",
    difficulty: 3,
    stem: "A company's revenue and expenses (in millions):\n\n2021: Revenue $10M, Expenses $8M\n2022: Revenue $12M, Expenses $10M\n2023: Revenue $15M, Expenses $11M\n\nIn which year was the profit margin (profit/revenue) the highest?",
    options: [
      { label: "A", text: "2021" },
      { label: "B", text: "2022" },
      { label: "C", text: "2023" },
      { label: "D", text: "2021 and 2022 tied" },
      { label: "E", text: "All three years were equal" },
    ],
    correctLabel: "C",
    tags: ["graph-interpretation"],
  },
];
